### ISSUE TITLE
How to debug with the Mqtt.Android.Service?

### ISSUE THREAD

**Issue by giskook** [eclipse-paho/paho.mqtt.java#168]
Hello,
I am new to both android and mqtt client.I cant find a email-list so I asked here and stackoverflow(https://stackoverflow.com/questions/35379720/org-eclipse-paho-android-service-how-the-sample-code-run).How can I get  the reason why the client is not connected to a server?
Thanks,
zhangkai.

**Comment by jpwsutton** [comment]
When connecting, you can usually work out why the connection failed by looking at the MqttException that is thrown:

```
try {
    mqttAndroidClient.connect(null, listener);
} catch (MqttException ex) {
    System.out.println(ex.getCause());
    System.out.println(ex.getReasonCode());
    System.out.println(ex.getMessage());
    ex.printStackTrace();
}

```
