### ISSUE TITLE
Is paho only support broadcasting subscrbe?

### ISSUE THREAD

**Issue by shangdiyisi** [eclipse-paho/paho.mqtt.java#176]
Is paho only support broadcasting subscrbe?

**Comment by jpwsutton** [comment]
Hi, The Paho Java library fully supports MQTT 3.1.1. I'm not sure what you mean by broadcasting subscribe though... Do you mean wildcards? E.g. subscribing to '#' or something like '/+/temperature'? In which case it does.

**Comment by shangdiyisi** [comment]
The broadcast subscription means that all consumers with the same CID will receive the message. Actually i don't know much about MQTT, How may subscribe way does MQTT have?

**Comment by jpwsutton** [comment]
So MQTT is a Pub Sub protocol, if your consumers subscribe to a topic e.g. '/test' (Or a topic using wildcards that encompasses that topic e.g. '/#'). They will all receive every message sent to that topic.
