### ISSUE TITLE
MqttDefaultFilePersistence.open does not implement it's interface properly

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.java#178]
In `MqttClientPersistence.open` the documentation says that if the persistent store is already open then it should just return. However, in `MqttDefaultFilePersistence.open` if the store is already open then it throws a `MqttPersistenceException.REASON_CODE_PERSISTENCE_IN_USE` Exception.

What should the proper behaviour be? Simply return with no Exception? Or Should I change the Documentation in the interface?

For reference, `MemoryPersistence` does not throw an exception, but does wipe out the existing Memory Persistence.

**Comment by kyo313** [comment]
I also find this bug

**Comment by jpwsutton** [comment]
As the exception was removed in Release 1.1.0 without any complaint, I'm assuming that following the documentation was the correct implementation.

**Comment by sxhebing** [comment]
It will produce an error when connect to server again after disconnected. I found that the persistence will close when a client disconnect from broker:
//This will be called when a client application disconnects from the broker
but not close when a client disconnect by application,so I add next code on MqttConnection.java in disconnect method:
`try {
        myClient.disconnect(invocationContext, listener);
} catch (Exception e) {
        handleException(resultBundle, e);
}
//Fix bug： connect to server failed after disconnected
if(persistence != null){
        try {
	        persistence.close();
        } catch (MqttPersistenceException e) {
        	e.printStackTrace();
        }
}`
