### ISSUE TITLE
MQTT calback does not get closed

### ISSUE THREAD

**Issue by kyo313** [eclipse-paho/paho.mqtt.java#180]
I am using the MQTT Api in my project to read data. (org.eclipse.paho org.eclipse.paho.client.mqttv3)

When I am closing the client, the mqttcallback is still active. I close mqtt by calling unsubscribe(...), disconnect() and close() on the object.

I tried setting the callback to null as well. Nothing helps.

**Comment by jpwsutton** [comment]
If there are any messages inflight when you close the connection, the client will attempt to resolve them first before closing the socket. Could this be what's happening on your client? However once close() fully returns, there shouldn't be any on the mqttCallback and you should be able to dispose of the object safely.

What is actually happening? Are you still receiving incoming messages from a subscription? Or is the  deliveryComplete callback being called upon successfully publishing a message?
