### ISSUE TITLE
Mqtt crash on Samsung Galaxy S3

### ISSUE THREAD

**Issue by baole** [eclipse-paho/paho.mqtt.java#184]
Device: Samsung Galaxy S3, Api 18

I try to connect to Mqtt server and Mqtt throws following messages

> 02-29 14:43:02.775 15361-15361/net.sample W/System.err: MqttException (0) - javax.net.ssl.SSLException: Connection closed by peer
> 02-29 14:43:02.775 15361-15361/net.sample W/System.err: at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
> 02-29 14:43:02.775 15361-15361/net.tandem W/System.err: at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:633)
> 02-29 14:43:02.775 15361-15361/net.tandem W/System.err: at java.lang.Thread.run(Thread.java:841)
> 02-29 14:43:02.785 15361-15361/net.tandem W/System.err: Caused by: javax.net.ssl.SSLException: Connection closed by peer
> 02-29 14:43:02.785 15361-15361/net.tandem W/System.err: at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
> 02-29 14:43:02.785 15361-15361/net.tandem W/System.err: at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:398)
> 02-29 14:43:02.785 15361-15361/net.tandem W/System.err: at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:93)
> 02-29 14:43:02.796 15361-15361/net.tandem W/System.err: at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:619)
> 02-29 14:43:02.796 15361-15361/net.tandem W/System.err: ... 1 more
> 02-29 14:43:02.796 15361-15361/net.tandem D/Tandem: Debug 

Any one can help me?

**Comment by jpwsutton** [comment]
The 'javax.net.ssl.SSLException: Connection closed by peer' would suggest that there is something wrong with your TLS certificate exchange. Are you just using a server certificate? Or are you using client certificates as well?  It might be worth looking into wether the server / client is correctly configured to use the right certificates.

**Comment by baole** [comment]
Hi @jpwsutton,

I'm sorry for my late response.

I don't use custom TLS certificate. This issue happens only on Android 4.x while working flawlessly on Android 5.0+. I post some SSL logs below. Do you have any idea why this issue occurred?

```
I/System.out: [socket][13] connection xxx:443;LocalPort=47595(30000)
I/System.out: [CDS]connect[xxx:443] tm:30
D/Posix: [Posix_connect Debug]Process net.tandem :443 
I/System.out: [socket][/192.168.178.188:47595] connected
I/System.out: [CDS]rx timeout:30000
D/NativeCrypto: ssl=0x55fd2440 NativeCrypto_SSL_do_handshake fd=0x1e900005 shc=0x20800009 timeout_millis=30000 client_mode=1 npn=0x0
D/NativeCrypto: doing handshake ++
D/NativeCrypto: ssl=0x55fd2440 info_callback where=0x10 ret=1
D/NativeCrypto: ssl=0x55fd2440 handshake start in UNKWN  before/connect initialization
D/NativeCrypto: ssl=0x55fd2440 info_callback ignored
D/NativeCrypto: ssl=0x55fd2440 info_callback where=0x1001 ret=1
D/NativeCrypto: ssl=0x55fd2440 SSL_connect:UNKWN  before/connect initialization
D/NativeCrypto: ssl=0x55fd2440 info_callback ignored
D/NativeCrypto: ssl=0x55fd2440 info_callback where=0x1001 ret=1
D/NativeCrypto: ssl=0x55fd2440 SSL_connect:23WCHA SSLv2/v3 write client hello A
D/NativeCrypto: ssl=0x55fd2440 info_callback ignored
D/NativeCrypto: ssl=0x55fd2440 info_callback where=0x1002 ret=-1
D/NativeCrypto: ssl=0x55fd2440 SSL_connect:error exit in 23RSHA SSLv2/v3 read server hello A
D/NativeCrypto: ssl=0x55fd2440 info_callback ignored
D/NativeCrypto: doing handshake -- ret=-1
D/NativeCrypto: ssl=0x55fd2440 NativeCrypto_SSL_do_handshake ret=-1 errno=11 sslError=2 timeout_millis=30000
D/NativeCrypto: doing handshake ++
D/NativeCrypto: doing handshake -- ret=0
D/NativeCrypto: ssl=0x55fd2440 NativeCrypto_SSL_do_handshake ret=0 errno=0 sslError=5 timeout_millis=30000
E/NativeCrypto: Unknown error during handshake
D/NativeCrypto: ssl=0x55fd2440 NativeCrypto_SSL_do_handshake clean error => 0
D/NativeCrypto: ssl=0x55fd2440 NativeCrypto_SSL_interrupt
D/NativeCrypto:  sslNotify, appData=0x55fd3f40 ret=1
D/NativeCrypto:  sslNotify, appData=0x55fd3f40 ret=1
I/System.out: [CDS]close[47595]
I/System.out: close [socket][/0.0.0.0:47595]
D/NativeCrypto: ssl=0x0 NativeCrypto_SSL_interrupt
D/AlarmPingSender: Unregister alarmreceiver to MqttService604e3ca4-bf
E/Tandem: MqttApi onFailure org.eclipse.paho.android.service.MqttTokenAndroid@42732038 /net.tandem.ext.mqtt.MqttApi$ConnectActionListener.onFailure(MqttApi.java:152)
W/System.err: MqttException (0) - javax.net.ssl.SSLException: Connection closed by peer
W/System.err:     at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
W/System.err:     at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:604)
W/System.err:     at java.lang.Thread.run(Thread.java:848)
W/System.err: Caused by: javax.net.ssl.SSLException: Connection closed by peer
W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:405)
W/System.err:     at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:89)
W/System.err:     at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:590)

```

**Comment by sshilko** [comment]
GCM cyphers only supported API 20+
http://developer.android.com/reference/javax/net/ssl/SSLSocket.html

think u can close this

**Comment by jpwsutton** [comment]
Thanks @sshilko I agree.
@baole If possible, see if you can change the certificate you're using to be something other than GCM and you should have better luck with older versions of android.

For reference, I used the following command to check the certificate you're using on the server mentioned in the log:

`openssl s_client -connect 50.19.81.147:443 -showcerts`

**Comment by slaupster** [comment]
Could try this:

https://developer.android.com/training/articles/security-gms-provider.html

as this does it here:

https://github.com/ibm-watson-iot/iot-starter-for-android/blob/5aba20eb463120edf6739d39a7b68c772218d200/app/src/main/java/com/ibm/iot/android/iotstarter/fragments/LoginPagerFragment.java#L256

to connect to Watson IoT which has a GCM cert.
