### ISSUE TITLE
JSR/RET are not supported with computeFrames option

### ISSUE THREAD

**Issue by dev-ladmusician** [eclipse-paho/paho.mqtt.java#185]
i am working my application with paho mqtt.
my android studio version is 2.0 RC1 
and cannot build my project.

**Comment by jpwsutton** [comment]
Hi, Have you tried using the current development version of the android service? This can be found here: https://github.com/eclipse/paho.mqtt.android.

Also, if you have any error logs they would be useful in diagnosing why you can't build your project.

**Comment by dev-ladmusician** [comment]
thank u so much for replying. i did not see new development version. it was helpful to me
