### ISSUE TITLE
Batch api for input messages

### ISSUE THREAD

**Issue by bangarharshit** [eclipse-paho/paho.mqtt.java#186]
Hey Guys,

I am writing a messaging client on top of Paho. Here is a simple optimization I am thinking (could be super useful to mqtt protocol as a whole) - batch messages as whole. For messages with QOS1 and QOS2 we are serving 100s of messages every time  a client goes online and then 100s of acks (we can save 99 acks this way). We are fixing our server to batch these messages (simply by sending List<Message> instead of message and expecting both List<Message> and message). I checked commsreceiver and mqttinputstream and looks to me it is possible. But no such low level api is exposed to end developer. I am developing it as a feature for my app and wanted to know if feels to be an important feature. I can think of acking the last/last+first message to effectively ack all these on server.  Any feedback is welcome.

**Comment by icraggs** [comment]
Hi,

is this the same as serializing an array (or other object) into the MQTT payload, and then deserializing at the other end?  Is there something else to it?

**Comment by bangarharshit** [comment]
Slightly different from that. What I am talking is List<Message> where Message = {payload, topic}. The case you mentioned is {List<payload>, topic}.  I wanted to batch across  topics.

Batching just in payload is hard across topics.

**Comment by jpwsutton** [comment]
Hi, When you publish a message, you can only publish it to one topic at a time, if you want to send messages to different topics, you will have to send them in separate publishes. But as said above, you could still batch messages for a specific topic.

**Comment by bangarharshit** [comment]
Makes sense. Closing it.
