### ISSUE TITLE
Calls to `connect` multiple times result to receives messages multiple times.

### ISSUE THREAD

**Issue by MRezaNasirloo** [eclipse-paho/paho.mqtt.java#191]
Hi, I'm using paho client and paho service for android.
What is  the proper way to reconnect when connection is not available for a while?

Before in version `1.2.0`, I used `MqttAndroidClient` `connect()` method after checking `isConnected()` returns `false`, which was ok, however after a network change or network reconnection, every new messages received the times it called `connect()` on `MqttAndroidClient` object.

For now I'm suing the `1.3.0-SNAPSHOT` auto reconnect feature, things are better now, however I have kind of the same issue on network change and reconnection, but it happens only on networks change and reconnection not when new messages is received as before.

For instance when I turn off and turn on back the wifi, it receives the last few messages again.

thanks.

**Comment by jpwsutton** [comment]
Hi, Are you subscribing / publishing with QoS 1? This could explain sending / receiving multiple messages after a disconnect: http://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels

**Comment by MRezaNasirloo** [comment]
Thank you @jpwsutton,

Is changing the QoS number from 1 to 2 sufficient? or should I change other portion of the client code? Because I don't see any change in its behavior!!!

**Comment by Mrzy** [comment]
My QoS number is 2, but when i reconnected wifi, it seems to exist multi-instance of MqttConnection, lead to received multi-message!!

**Comment by Mrzy** [comment]
please ignore my pre-comment. I didn't use this develop branch lib, and use modified by me based on master branch lib. May be strongly my problem.

**Comment by MRezaNasirloo** [comment]
Changing Qos number from 1 to 2 actually fixed the problem. my bad
