### ISSUE TITLE
MqttAndroidClient registerReceiver multi times

### ISSUE THREAD

**Issue by dynastyX** [eclipse-paho/paho.mqtt.java#193]
Hi, I'm using paho client and paho service for android.

after the app was launched , I called 

```
org.eclipse.paho.android.service.MqttAndroidClient#connect(org.eclipse.paho.client.mqttv3.MqttConnectOptions, java.lang.Object, org.eclipse.paho.client.mqttv3.IMqttActionListener)
```

to connect to server , it works well
when network change and after network reconnected , I called the **connect** again(same client) to do reconnection.

It seems the 

```
org.eclipse.paho.android.service.MqttAndroidClient#registerReceiver
```

was called again after **connect** this time. It cause **onReceive** to receive same action, which my callback method was called multi time for a same event ..

thanks.

**Comment by jpwsutton** [comment]
There is some code in the android client that partially attempts to automate reconnection upon network change. Once the network is reconnected, the Service will trigger a reconnect attempt automatically. This could be clashing with your own connect and thus causing the multiple onReceive calls..

**Comment by jpwsutton** [comment]
https://github.com/eclipse/paho.mqtt.android/blob/master/org.eclipse.paho.android.service/src/main/java/org/eclipse/paho/android/service/MqttService.java#L805

**Comment by dynastyX** [comment]
thanks! jpwsutton

but my connection required *\* cleanSession = true *\* 

https://github.com/eclipse/paho.mqtt.android/blob/master/org.eclipse.paho.android.service/src/main/java/org/eclipse/paho/android/service/MqttConnection.java#L1000

```
if (disconnected && !cleanSession) {
```

so the reconnection will not be excuted...

**Comment by jpwsutton** [comment]
Do you see the same behaviour in the SNAPSHOT version of the service as well?

**Comment by jpwsutton** [comment]
This issue was moved to eclipse/paho.mqtt.android#82
