### ISSUE TITLE
NPE when MqttAsyncClient is closed after unsuccessful connect

### ISSUE THREAD

**Issue by surmay** [eclipse-paho/paho.mqtt.java#194]
Steps to reproduce:
Call `MqttAsyncClient.connect()`
Immediately after `IMqttActionListener.onFailure()` is called, call `MqttAsyncClient.close()`

Issue:
`MqttAsyncClient.connect()` creates the `shutdownConnection$ConnectBG` Runnable, which attempts to connect to the server. At the end of this Runnable, if we were unable to connect, `ClientComms.shutdownConnection()` is called. `shutdownConnection()` synchronizes on conLock, but only at the beginning of the method.

If ClientComms.close() is then called, `tokenStore` becomes null. `ClientComms.shutdownConnection()` then throws NPE.

I cannot find anything at the end of `shutdownConnection()` to listen for in my application code to ensure that the Runnable is finished processing before calling `close()`

Stacktrace:
`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.eclipse.paho.client.mqttv3.internal.CommsTokenStore.quiesce(org.eclipse.paho.client.mqttv3.MqttException)' on a null object reference
       at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:334)
       at org.eclipse.paho.client.mqttv3.internal.CommsCallback.asyncOperationComplete(CommsCallback.java:430)
       at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:380)
       at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:668)
       at java.lang.Thread.run(Thread.java:818)`

**Comment by jpwsutton** [comment]
@surmay Did you find this bug in both the released version and the SNAPSHOT? I'm unable to recreate this in the develop branch. Have you tried using that?

Here is the code that I used to try this:

```
package issue_194;

import org.eclipse.paho.client.mqttv3.IMqttActionListener;
import org.eclipse.paho.client.mqttv3.IMqttToken;
import org.eclipse.paho.client.mqttv3.MqttAsyncClient;
import org.eclipse.paho.client.mqttv3.MqttException;

public class App {

    public static void main(String[] args)  {
        try {
        System.out.println("Creating Client to nowhere.");
        MqttAsyncClient client = new MqttAsyncClient("tcp://127.0.0.1:9999", "bob");
        System.out.println("Calling Connect");
        client.connect(null, new IMqttActionListener() {

            @Override
            public void onSuccess(IMqttToken asyncActionToken) {
                System.out.println("Connected");
            }

            @Override
            public void onFailure(IMqttToken asyncActionToken, Throwable exception) {
                System.out.println("Failed to connect, immediately calling close()");
                try {
                    client.close();
                    System.out.println("Client was closed successfully");
                } catch (MqttException e) {
                    System.err.println("Exception thrown closing connection: " + e.getMessage());
                    e.printStackTrace();
                }
            }
        });

        } catch (MqttException e) {
            System.err.println("Exception thrown generally: " + e.getMessage());
            e.printStackTrace();
        }

    }

}

```

And my log:

```
Creating Client to nowhere.
Calling Connect
Failed to connect, immediately calling close()
Client was closed successfully

```

**Comment by surmay** [comment]
@jpwsutton I am seeing the issue on SNAPSHOT - I have not tried the 1.0.2 release version.

I have never been able to actually observe the crash during development - only when distributing the application out to others. It seems to be a relatively low occurrence rate - maybe 1 crash in ~100 hours of use.

I will work on a reproducible test case.

**Comment by surmay** [comment]
@jpwsutton - I am still not able to reproduce the issues that we are seeing in the field. We are running on Android devices, so I believe that it also has to do with unreliable connections, which are difficult to test.

I have gone back over the source code and created a pull request to add a isClosed() check to shutdownConnection. From our stacktraces, we believe that there are multiple calls to shutdownConnection() - and if one of the calls occurs after close(), there is no guard to keep it from running.

Let me know if you have any concerns with the change.

**Comment by jpwsutton** [comment]
@surmay I agree, I think that check won't hurt anything and is probably a safe idea to have in any case. I've merged the change in. Assuming the Dev build passes tonight, it will be in the SNAPSHOT library tomorrow morning.

**Comment by surmay** [comment]
Thanks! Our crashes have stopped with the new SNAPSHOT, so this looks like it is resolved
