### ISSUE TITLE
NPE in CONNECTIVITY_CHANGE intent

### ISSUE THREAD

**Issue by brstgt** [eclipse-paho/paho.mqtt.java#198]
See crash here:

http://crashes.to/s/f3bbeae1080

**Comment by jpwsutton** [comment]
Hi, We need more information before we can take a look at this:
- What version of the library are you using? 1.0.2? Or 1.0.3-SNAPSHOT?
- Are you using the plain Java client? Or the Android Service?

If you're using 1.0.2, you may want to try the 1.0.3 snapshot version as that has had numerous improvements, especially to the automatic reconnect functionality.

**Comment by brstgt** [comment]
Hi!

We use 1.0.2 and Android (you can see that in the linked crashlogs).
I saw in #189 (probably mine is a dupe) that this issue should be fixed in the SNAPSHOT.
So sorry for the possible duplicate.

If 1.0.3 has many improvements, why don't you release it on maven? I think this would help alot.
1.0.2 is quite old (Dec 2015). When I am going to use a library, I always first check an existing maven version, cause 1. I guess it is stable, 2. it is much easier to integrate into projects.

Thanks for your help!

P.S. I don't know why I submitted this issue to the JAVA repo and not to the Android repo. Sorry!

**Comment by jpwsutton** [comment]
Hi, No worries at all, things are a bit confusing right now as we're coming up to our new release. Once we release alongside Eclipse Neon in May, the 1.0.3 client will be uploaded to Maven Central as the new 'latest release' so it should be very easy to get hold of then.

**Comment by jpwsutton** [comment]
This issue was moved to eclipse/paho.mqtt.android#81
