### ISSUE TITLE
Android Service features supported in 1.2.0 (Neon)?

### ISSUE THREAD

**Issue by gholadr** [eclipse-paho/paho.mqtt.java#200]
Not clear whether 1.2.0 supports the following for Android specifically:

 Clean session. The ability to remember which topics the client subscribed to so no need to re-subscribe on subsequent reconnect sessions. Using getSessionPresent throws an NPE (#175) so this does not seem to be implemented currently? 

Offline support. This requires persistence support on the client side. I'm using MqttDefaultFilePersistence when creating a new MqttAndroidClient with QoS 2 but somehow i'm not getting the MQTT messages that were sent while the app was offline.  Is this officially supported?

Automatic Reconnect. Is this feature available for the java client but not the Android version? I've tried setting `setAutomaticReconnect(true)` but it does not appear to have any effect on anything currently.

**Comment by jpwsutton** [comment]
Hi,
A few months back we moved the android code in develop out into a new GitHub repository: https://github.com/eclipse/paho.mqtt.android and for the SNAPSHOT library, Automatic Reconnect and Offline buffering are now enabled. The Clean Session bug is planned to be fixed before neon as well and hopefully I'll be able to take a look at that in the next few days.

**Comment by gholadr** [comment]
I'm using SNAPSHOT lib as per your instruction in #175 and using the maven rep that points to the snapshot libs. 

is there some documentation on automatic reconnect? maybe I've missed something.

offline buffering is something else though isnt it, thats when the client wants to publish something but is offline? what happens when the client is subscribed to a topic and is offline?

**Comment by gholadr** [comment]
I finally got it working. 

Is there a reason why this connect method from MqttAndroidClient is not specifically requesting a Context object (vs. a generic Object)

```
public IMqttToken connect(Object userContext,
            IMqttActionListener callback) throws MqttException {
```

This tripped me up for days as I was passing the MqttConnectOptions object, but the connect method was expecting a Context object.

**Comment by jpwsutton** [comment]
The idea is that the user can put whatever they like in the userContext Object, so a generic Object is more suited than anything else.
