### ISSUE TITLE
Deadlock while trying to connect to a unavailable server.

### ISSUE THREAD

**Issue by alaendle** [eclipse-paho/paho.mqtt.java#202]
If I try to connect to a server that isn't available I think I've encountered a deadlock.
Just take a look at the stack traces:

Root Thread [1](WAITING)
   java.lang.Object.wait line: not available [native method]
   java.lang.Object.wait line: not available 
   org.eclipse.paho.client.mqttv3.internal.Token.waitForResponse line: 141 
   org.eclipse.paho.client.mqttv3.internal.Token.waitForCompletion line: 108 
   org.eclipse.paho.client.mqttv3.MqttToken.waitForCompletion line: 67 
   org.eclipse.paho.client.mqttv3.MqttClient.connect line: 236 
   org.eclipse.paho.client.mqttv3.util.Publish.publish line: 36 
   org.eclipse.paho.client.mqttv3.util.Publish.publish line: 13 

MQTT Snd: paho1462537712313 [7](WAITING)
   java.lang.Object.wait line: not available [native method]
   java.lang.Object.wait line: not available 
   org.eclipse.paho.client.mqttv3.internal.ClientState.get line: 645 
   org.eclipse.paho.client.mqttv3.internal.CommsSender.run line: 98 

MQTT Rec: paho1462537712313 [6](WAITING)
   java.lang.Object.wait line: not available [native method]
   java.lang.Thread.join line: not available 
   java.lang.Thread.join line: not available 
   org.eclipse.paho.client.mqttv3.internal.CommsSender.stop line: 81 
   org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection line: 325 
   org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run line: 146 

My workaround is to replace the following lines in CommsSender.stop (line 78ff)
-                       // first notify get routine to finish
-                       clientState.notifyQueueLock();
-                       // Wait for the thread to finish.
-                       sendThread.join();

with
-                       while(sendThread.isAlive()) {
-                           // first notify get routine to finish
-                           clientState.notifyQueueLock();
-                           // Wait for the thread to finish.
-                           sendThread.join(100);
-                       }

The behaviour is 100% reproducible (but only on the Oracle Aurora JVM). I'm not sure if the workaround is o.k.. Please let me know if you need further information or if I could contribute in some other way to solve this problem.

**Comment by jpwsutton** [comment]
This fix is now in the develop branch and will be build into a SNAPSHOT later this evening. It should then be released later this month with our Neon Release.

**Comment by alaendle** [comment]
Thx - I'm looking forward to the new release ;-)
