### ISSUE TITLE
manual acks broken in Android

### ISSUE THREAD

**Issue by mockturtl** [eclipse-paho/paho.mqtt.java#205]
The documentation for [`MqttAndroidClient#acknowledgeMessage(String messageId)`](https://github.com/eclipse/paho.mqtt.java/blob/v1.0.2/org.eclipse.paho.android.service/org.eclipse.paho.android.service/src/org/eclipse/paho/android/service/MqttAndroidClient.java#L1301) suggests casting the message to `ParcelableMqttMessage` to access the id, but this class is package-private as of [@25eefc8](https://github.com/eclipse/paho.mqtt.java/commit/25eefc8ece57cd2f4c53f79c14c50fc6aa4c2702#diff-f5eee4bd94cec448063f413a89aece57L48).

**Comment by jpwsutton** [comment]
This looks like a mistake, [ParcelableMqttMessage](https://github.com/eclipse/paho.mqtt.android/blob/master/org.eclipse.paho.android.service/src/main/java/org/eclipse/paho/android/service/ParcelableMqttMessage.java#L48) does extend MqttMessage, but as MqttMessage is public, there shouldn't be any reason for it to not be public.. I don't think there is a problem with undoing that change so I'll do that now.

**Comment by jpwsutton** [comment]
This issue was moved to eclipse/paho.mqtt.android#80
