### ISSUE TITLE
Android studio compilation issue for inner classes used

### ISSUE THREAD

**Issue by pavan2you** [eclipse-paho/paho.mqtt.java#206]
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.eclipse.paho.client.mqttv3.persist.MqttDefaultFilePersistence$1) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is _not_ an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.eclipse.paho.client.mqttv3.persist.MqttDefaultFilePersistence$2) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is _not_ an inner class.

**Comment by jpwsutton** [comment]
Hi, what are the steps to re-create this error?

**Comment by pavan2you** [comment]
Hi,
Steps:
1. Please create a new project in Android Studio 
2. Include eclipse paho android library in build gradle like this.
    `compile('org.eclipse.paho:org.eclipse.paho.android.service:1.0.2') {
        exclude module: 'support-v4'
    }`
3. Build and run
4. Observe above logs from messages tab. It prompts 16 errors but still BUILD IS SUCCESSFUL. 

Thanks
Pavan

**Comment by gholadr** [comment]
I'm experiencing the same problem since I've upgraded to Android Studio 2.1. I'm using SNAPSHOT release.

**Comment by jpwsutton** [comment]
This issue was moved to eclipse/paho.mqtt.android#79

**Comment by sojue** [comment]
https://github.com/eclipse/paho.mqtt.java/issues/213
