### ISSUE TITLE
 WebSocket support for the Java client

### ISSUE THREAD

**Issue by ravimittal99** [eclipse-paho/paho.mqtt.java#208]
Is there a java(/android) client that supports MQTT over websockets? 

Checked https://github.com/inventit/mqtt-websocket-java 

But, it has eclipse-jetty dependency.

**Comment by jpwsutton** [comment]
Yup, this one does! (The Android client uses the Java client under the covers and so also supports it)

Example of how to use WebSockets here: https://github.com/jpwsutton/EclipsePahoMavenExample/blob/master/src/main/java/org/eclipse/paho/App.java

tl;dr - replace 'tcp://' with 'ws://' in the broker URI (and make sure you use the right port)

**Comment by ravimittal99** [comment]
Gradle support?

**Comment by jpwsutton** [comment]
Gradle is just a build process, the Java and Android clients are available as JARs and so would support wither maven or gradle without any issues.

**Comment by ravimittal99** [comment]
I succesfully created an android client which works over tcp. There's another javascript client over websockets. They both aren't able to exchange messages. Any work around to get them work ? or do i need to create a client using websockets?

**Comment by jpwsutton** [comment]
As long as you are connected to the same MQTT broker, and subscribing / publishing to the same topic, they should receive messages from each other. E.g.

Android Client Subscribes to 'myTopic'
Javascript Client Publishes to 'myTopic'

**Comment by ravimittal99** [comment]
But it doesn't happen. I see two androids exchanging messages and two javascript clients exchanging messages. all of them are connected to the same broker( As far as i understand, tcp://mydomain.com:1883 and  ws://mydomain.com/9001 are both same broker. Isn't it?).

**Comment by jpwsutton** [comment]
Well that depends on the broker, what broker are you using? For instance if it is Mosquitto, you need to have the configuration for websockets and normal tcp MQTT in the same configuration file and only have one mosquitto instance running.

E.g.

```
listener 1883
protocol mqtt

listener 9001
protocol websockets
```

**Comment by ravimittal99** [comment]
Well, here is my config file if you wanna have a look into:

```
listener 9001
protocol websockets
listener 1883
protocol mqtt
persistence true
persistence_location /var/lib/mosquitto/
persistence_file mosquitto.db
log_dest syslog
log_dest stdout
log_dest topic
log_type error
log_type warning
log_type notice
log_type information
connection_messages true
log_timestamp true
allow_anonymous true
password_file /etc/mosquitto/pwfile
```

And here is the response from the server on restarting with these settings:

```
1463649104: mosquitto version 1.4.8 (build date 2016-05-13 12:53:34+0530) starting
1463649104: Config loaded from /etc/mosquitto/mosquitto.conf.
1463649104: Opening websockets listen socket on port 9001.
1463649104: Opening ipv4 listen socket on port 1883.
1463649104: Opening ipv6 listen socket on port 1883.

```

**Comment by jpwsutton** [comment]
Looks good to me, what topics are your clients publishing and subscribing to?

**Comment by ravimittal99** [comment]
android client1 subscribes to "topic1" and publishes to "topic2"
android client2 subscribes to "topic2" and publishes to "topic1" (they both are exchanging messages properly)

javascript client1 subscribes to "topic1" and publishes to "topic2"
javascript client2 subscribes to "topic2" and publishes to "topic1"(they both are exchanging messages properly)

android doesn't receive messages published by javascript client and vice versa.

**Comment by jpwsutton** [comment]
I cant think of any reason why the clients would fail to send and receive messages. I've just tested this with my own phone and the JavaScript test client. To rule out the clients you're using, Try pointing your Android phone at iot.eclipse.org:1883 and use the Javascript client utility here: http://www.eclipse.org/paho/clients/js/utility/index.html.

If using the iot.eclipse.org server works correctly, then it is likely that there is a problem with how you've configured your mosquitto server. If that's the case, I recommend asking here: https://www.eclipse.org/forums/index.php/f/270/ or on the mosquitto github:https://github.com/eclipse/mosquitto

**Comment by jpwsutton** [comment]
@ravimittal99 Any luck with this? Can I close the issue?
