### ISSUE TITLE
why there is no max_inflight_messages_set() method in android client ?

### ISSUE THREAD

**Issue by saherelm** [eclipse-paho/paho.mqtt.java#212]
i see this method in [Python Client - documentation](https://www.eclipse.org/paho/clients/python/docs/) but there isn't any method in android client for doing same work as the method done ...

**Comment by jpwsutton** [comment]
The ability to set max inflight messages was added to the develop branch a while back, which will be released sometime in the next week: https://github.com/eclipse/paho.mqtt.java/blob/develop/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/MqttConnectOptions.java#L242

The documentation will also be updated then.
