### ISSUE TITLE
gradle 2.0+ build error on android

### ISSUE THREAD

**Issue by sqrt1764** [eclipse-paho/paho.mqtt.java#213]
- [ x ] Bug exists Release Version 1.0.2 ( Master Branch)
- [ x ] Bug exists in Snapshot Version 1.0.3 (Develop Branch)

---
### Build-time error on android.

A gradle update came with a new issue with a mqtt-lib that is being used.
##### The error:

```
(...)
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources
:app:prePackageMarkerForDebug
:app:transformClassesWithDexForDebug
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.eclipse.paho.client.mqttv3.persist.MqttDefaultFilePersistence$2) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.eclipse.paho.client.mqttv3.persist.MqttDefaultFilePersistence$1) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
:app:mergeDebugJniLibFolders UP-TO-DATE
:app:transformNative_libsWithMergeJniLibsForDebug
:app:processDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDebug
:app:validateDebugSigning
:app:packageDebug
:app:zipalignDebug
:app:assembleDebug
```
### The fix.

Suggested fix was a no-go.
One of the libraries dependencies required it to be compiled with java1-4
& a newer version was not an option.
In the end the issue was solved by getting rid the classes that caused the errors and
turning them into a regular classes.
##### The new classes

``` java
package org.eclipse.paho.client.mqttv3.persist;

import java.io.File;
import java.io.FilenameFilter;

public class PersistanceFilenameFilter implements FilenameFilter {

    private final String fileExtension;

    public PersistanceFilenameFilter(String fileExtension) {
        this.fileExtension = fileExtension;
    }

    public boolean accept(File dir, String name) { return name.endsWith(fileExtension); }

}
```

``` java
package org.eclipse.paho.client.mqttv3.persist;

import java.io.File;
import java.io.FileFilter;

public class PersistanceFileFilter implements FileFilter {

    private final String fileExtension;

    public PersistanceFileFilter(String fileExtension) {
        this.fileExtension = fileExtension;
    }

    public boolean accept(File f) {
        return f.getName().endsWith(fileExtension);
    }
}
```

---

These classes replace anonymous inner classes in `MqttDefaultFilePersistence` class.

---

``` java
private static final FilenameFilter FILE_FILTER = new FilenameFilter() {
    public boolean accept(File dir, String name) {
        return name.endsWith(MESSAGE_FILE_EXTENSION);
    }
};
```

was replaced with the `PersistanceFilenameFilter` class...

``` java
private static FilenameFilter FILENAME_FILTER;
```

``` java
private static FilenameFilter getFilenameFilter() {
    if (FILENAME_FILTER == null) {
        FILENAME_FILTER = new PersistanceFilenameFilter(MESSAGE_FILE_EXTENSION);
    }

    return FILENAME_FILTER;
}
```

---

``` java
private void restoreBackups(File dir) throws MqttPersistenceException {
    File[] files = dir.listFiles(new FileFilter() {
        public boolean accept(File f) {
            return f.getName().endsWith(MESSAGE_BACKUP_FILE_EXTENSION);
        }
    });
    //... unmodified part has been removed
}
```

was replaced with `PersistanceFileFilter` class...

``` java
private void restoreBackups(File dir) throws MqttPersistenceException {
    File[] files = dir.listFiles(new PersistanceFileFilter(MESSAGE_BACKUP_FILE_EXTENSION));
    //... unmodified part has been removed
}
```

---

Nothing else was changed in the libraries code.
The library was still compiled with the target of java1-4.

---

---

Hoping this fix is correct & it helps people & someone updates the lib itself so that everyone on android doesn't have to recompile it themselves.

**Comment by roy651** [comment]
@jpwsutton Thanks for the fix (it's not in the unstable snapshot yet, so I built it manually)
However, you should know that there still exist a couple of more occurrences of similar troubling inner classes, since the Android Studio still reports them (see below).

Why not follow through and fix the compilation as recommended in the warning? 

> The recommended solution is to recompile the class from source, using an up-to-date compiler and without specifying any "-target" type options

Warning message:

> Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
> Error:(org.eclipse.paho.client.mqttv3.MqttAsyncClient$1) that doesn't come with an
> Error:associated EnclosingMethod attribute. This class was probably produced by a
> Error:compiler that did not target the modern .class file format. The recommended
> Error:solution is to recompile the class from source, using an up-to-date compiler
> Error:and without specifying any "-target" type options. The consequence of ignoring
> Error:this warning is that reflective operations on this class will incorrectly
> Error:indicate that it is _not_ an inner class.
> Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
> Error:(org.eclipse.paho.client.mqttv3.MqttAsyncClient$2) that doesn't come with an
> Error:associated EnclosingMethod attribute. This class was probably produced by a
> Error:compiler that did not target the modern .class file format. The recommended
> Error:solution is to recompile the class from source, using an up-to-date compiler
> Error:and without specifying any "-target" type options. The consequence of ignoring
> Error:this warning is that reflective operations on this class will incorrectly
> Error:indicate that it is _not_ an inner class.
> Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
> Error:(org.eclipse.paho.client.mqttv3.internal.ClientComms$1) that doesn't come with an
> Error:associated EnclosingMethod attribute. This class was probably produced by a
> Error:compiler that did not target the modern .class file format. The recommended
> Error:solution is to recompile the class from source, using an up-to-date compiler
> Error:and without specifying any "-target" type options. The consequence of ignoring
> Error:this warning is that reflective operations on this class will incorrectly
> Error:indicate that it is _not_ an inner class.
> Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
> Error:(org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketNetworkModule$1) that doesn't come with an
> Error:associated EnclosingMethod attribute. This class was probably produced by a
> Error:compiler that did not target the modern .class file format. The recommended
> Error:solution is to recompile the class from source, using an up-to-date compiler
> Error:and without specifying any "-target" type options. The consequence of ignoring
> Error:this warning is that reflective operations on this class will incorrectly
> Error:indicate that it is _not_ an inner class.
> Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
> Error:(org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule$1) that doesn't come with an
> Error:associated EnclosingMethod attribute. This class was probably produced by a
> Error:compiler that did not target the modern .class file format. The recommended
> Error:solution is to recompile the class from source, using an up-to-date compiler
> Error:and without specifying any "-target" type options. The consequence of ignoring
> Error:this warning is that reflective operations on this class will incorrectly
> Error:indicate that it is _not_ an inner class.

**Comment by jpwsutton** [comment]
I've updated the target version from 1.2 (Java 1.4) to 1.7 in build.xml in the java-1.7+ branch here: https://github.com/eclipse/paho.mqtt.java/commit/42e247077e6ad8e85cc88324523daa47beeb6220

This branch will be merged back into develop once the 1.3.0 has been released in November this year.

**Comment by gotev** [comment]
Resolved all compilation warnings using Gradle 2.2.3. All my modifications are here: https://github.com/iGenius-Srl/paho.mqtt.java/issues/1

I forked the master repo and made the needed changes. I can make a PR

**Comment by jpwsutton** [comment]
@gotev If you could make a PR against the develop branch, that would be fantastic. Thank you!

**Comment by gotev** [comment]
@jpwsutton ok, I'll do that as soon as I can. Probabily in the next week

**Comment by mbchandru** [comment]
inner classes, since the Android Studio still reports....
When 1.3.0 release will happen to solve the inner classes reported by Android Studio.
Please at least put the changes, in 1.1.0 snapshot, for use.
