### ISSUE TITLE
Release 1.1.0 unavailable on https://repo.eclipse.org/content/repositories/paho-releases/

### ISSUE THREAD

**Issue by gholadr** [eclipse-paho/paho.mqtt.java#217]
As per the documentation, the latest release version is 1.1.0 but I do not see it on the official paho-releases repo (https://repo.eclipse.org/content/repositories/paho-releases/)?

**Comment by jpwsutton** [comment]
Hi, 

Yes this is a problem to do with the release build mechanism, We modified it to work with maven central, but now it wont work with the main eclipse repository. If nobody else gets a chance to look at it, I'll try and fix it once I get a chance.

**Comment by gholadr** [comment]
ok, great, thanks, will just grab 1.1.0 from maven. Plan on going live with it soon. Ok to use org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.0 with org.eclipse.paho.android.service:1.0.2?

**Comment by jpwsutton** [comment]
I've now re-jigged the build to deploy to both OSSRH and repo.eclipse.org.
The libraries are now available: https://repo.eclipse.org/content/repositories/paho-releases/org/eclipse/paho/

**Comment by gholadr** [comment]
@jpwsutton  Looks like the repo URL above is dead again?
