### ISSUE TITLE
Not compatible with JRE 1.4.2 

### ISSUE THREAD

**Issue by GeoppWicke** [eclipse-paho/paho.mqtt.java#218]
- [x ] Bug exists Release Version 1.0.2 ( Master Branch)
- [ x] Bug exists in Snapshot Version 1.0.3 (Develop Branch)

There are several  issues (near than 10)  that are not compatibility with the JRE 1.4.2 specification. Like:
- Using function `System.nanoTime()`
- Using  constructor `new Timer(String arg)`
- Using function `String.format(....)`
- ...

There are two ways to solve it. The first is to make all compatible and the second to change the documentation and may be compiler settings. 
For my own I preferred the first way and made all compatible.  If that is compatible with the project goal. I am able to contribute and submit it.

**Comment by jpwsutton** [comment]
@GeoppWicke Thanks for spotting this, currently the goal is to maintain compatibility with JRE 1.4.2 and so we will need to make those calls compatible with the spec. We may decide to split away in the future and drop support in favour of taking advantage of newer JRE features, but for the time-being it's important that we don't break backwards compatibility.

**Comment by jpwsutton** [comment]
Having looked at JRE 1.4.2 more closely I think that once we've released the next milestone we should stop supporting JRE 1.4.2 and JRE 1.5 as they are both now very old and out of support. Not to mention the insane number of vulnerabilities that they both have:
- http://www.cvedetails.com/vulnerability-list/vendor_id-5/product_id-1083/version_id-74361/SUN-JDK-1.4.2.html
- https://www.cvedetails.com/vulnerability-list/vendor_id-5/product_id-1526/version_id-104598/SUN-JRE-1.5.0.html

Implementing new features is also becoming a pain as we have to constantly make sure we are maintaining 1.4.2 compatibility (Which is probably how these slipped through the net).

**Comment by GeoppWicke** [comment]
I agree. But have a notice I already have compatible version. I only have to commit.

**Comment by jpwsutton** [comment]
@GeoppWicke that's great, if you sign the CLA and then add a pull request for the develop branch I'll be able to merge it in.

**Comment by jpwsutton** [comment]
I went ahead and managed to get a vm running with a 1.4.2 JDK so that I could find any bits of source code that would not work in Java 1.4.2. I've commented out the original code and left a `// Cannot use for Java 1.4.2` comment there. Once the next release goes out, I'll undo these changes.
