### ISSUE TITLE
Message not buffered for publish before initial connect

### ISSUE THREAD

**Issue by KenBarr** [eclipse-paho/paho.mqtt.java#233]
I am trying to test new Java Paho API features in mqttv3-1.1.0.jar and am having a problem with DisconnectBuffer for offline publishing.

If I create an  MqttAsyncClient and setBufferOpts() then connect and publish, I get a "Client is not connected" exception on publish.  I would have thought the message would buffer until initial connection completes, but it does not.  If I publish after  connectionComplete() callback then message is published correctly.

Code is attached:
[SimpleMqttClient.zip](https://github.com/eclipse/paho.mqtt.java/files/399758/SimpleMqttClient.zip)

Stack trace is:
Client is not connected (32104)
    at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
    at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java:166)
    at org.eclipse.paho.client.mqttv3.MqttAsyncClient.publish(MqttAsyncClient.java:1027)
    at org.eclipse.paho.client.mqttv3.MqttAsyncClient.publish(MqttAsyncClient.java:1005)
    at com.solacesystems.cto.SimpleMqttClient.runClient(SimpleMqttClient.java:119)
    at com.solacesystems.cto.SimpleMqttClient.main(SimpleMqttClient.java:63)

**Comment by jpwsutton** [comment]
Hi, This was the original design of the Offline Buffering functionality #9 and is consistent with other clients.

**Comment by KenBarr** [comment]
Are you saying the API methods for the features was releases in 1.1.0, but the actual functionality is not available until 1.2.0?The auto-reconnect seems to work in 1.1.0 api, just not the offline publishing.
Where do I find mqttv3-1.2.0.jar?   I was looking here:
https://repo.eclipse.org/content/repositories/paho-releases/org/eclipse/paho/org.eclipse.paho.client.mqttv3/

```
On Thursday, August 4, 2016 4:39 AM, James Sutton <notifications@github.com> wrote:
```

 Hi, This was the original design of the Offline Buffering functionality #9 and is consistent with other clients.—

**Comment by jpwsutton** [comment]
No, the API and functionality are available in 1.1.0. But publishing a message to the buffer before the first connection has completed is not part of the design and so will not work. Before you can use the offline buffer, you must have at least successfully connected once.

**Comment by KenBarr** [comment]
Thank you very much for your help.  Is it possible to turn this into a low priority feature request and put on backlog?  I do not see publish before initial connect as a corner case. Without this feature it will likely mean that for async clients, a guard will have to be built around each publish to ensure initial connection has happened, or the application will have to block itself on initial connect.

I understand that subscribe has the same problem, but subscription add is usually more controlled within the application.

Please close or push to backlog as you see fit.

**Comment by jpwsutton** [comment]
Thanks, this is a good point and something that we didn't initially consider too much, I'll push this to the backlog for further discussion in the community.

**Comment by masc3d** [comment]
I would require this feature as well plus full automatic reconnect including initial for an android application.

I'm currently thinking about either providing a pull request or wrapping reconnection/persistence around the client. I would prefer having this in paho, but if fundamental/design changes are required in order to have this, I'd probably rather wrap it up as I need it pretty soon.

Any feedback how intrusive you would classify implementing this would be much appreciated.

**Comment by jpwsutton** [comment]
This has been added in PR #354
