### ISSUE TITLE
Can't build from source

### ISSUE THREAD

**Issue by IceFireg** [eclipse-paho/paho.mqtt.java#238]
Hello,actually I am a novice in mqtt. Recently I download your code from here and want to use it to write a client, but there was something wrong when I build.
![2016-08-13 16-55-08](https://cloud.githubusercontent.com/assets/18031253/17642393/070885d2-6177-11e6-9385-8ee787b1826c.png)
I added the repository definition and the dependency definition shown below to my pom.xml. However I did not install eclipse. 
Could you tell me where I did wrong and how to fix this problem?

**Comment by miketran78727** [comment]
@IceFireg It looks like you are building from source after cloning from github. So, why do you need to modify the pom.xml in paho.mqtt.java-master directory?  Could you just run:

```
mvn package -DskipTests
```

**Comment by IceFireg** [comment]
@miketran78727 Thanks for your advice. However the problem also exists. This time I did not modify the pom.xml. Here are the master and the relese1.1.0 versions. They both went wrong.
![2016-08-16 17-18-40](https://cloud.githubusercontent.com/assets/18031253/17694342/f77588c0-63d5-11e6-9911-a2cb7fb56c2e.png)
![2016-08-16 17-18-58](https://cloud.githubusercontent.com/assets/18031253/17694351/fd66d298-63d5-11e6-951e-e2cbebe23754.png)

**Comment by miketran78727** [comment]
@IceFireg I suspect this is related to maven version 2.  Could you please make sure that you are using the latest version of maven for your Linux distribution.

**Comment by IceFireg** [comment]
@miketran78727 Thank you for your suggestion again. My maven version is 2.2.1. Then I tried using _mvn clean install -U_ to update maven, but I failed because the pom is not right.
![2016-08-17 21-18-54](https://cloud.githubusercontent.com/assets/18031253/17737861/955c37d2-64c1-11e6-96c1-e7b76900f7a0.png)
So I wonder if my version is the latest and what should I do next? What's more, do you know other source to write mqtt?
Thanks for any solution.

**Comment by miketran78727** [comment]
@IceFireg There are many ways to upgrade maven to latest stable version.  If your Linux distribution does not provide a way to upgrade maven, then you will have to manually upgrade maven yourself.  Here is an example : https://gist.github.com/npatta01/512404dee5cd7fd26ac1#file-maven-333-sh

**Comment by IceFireg** [comment]
@miketran78727 Thank you for your help. Now I have already built successfully.

**Comment by miketran78727** [comment]
@IceFireg Great.  I am glad to help out whenever I can.  Please close this issue. Thanks.
