### ISSUE TITLE
How to build the own jar

### ISSUE THREAD

**Issue by sunfeng90** [eclipse-paho/paho.mqtt.java#241]
In Android Studio, I got the problem:
# " Error:indicate that it is _not_ an inner class.

Error:this warning is that reflective operations on this class will incorrectly
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lorg/eclipse/paho/client/mqttv3/MqttCallback;
Error:compiler that did not target the modern .class file format. The recommended
Error:(org.eclipse.paho.client.mqttv3.persist.MqttDefaultFilePersistence$2) that doesn't come with an
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.eclipse.paho.client.mqttv3.persist.MqttDefaultFilePersistence$1) that doesn't come with an
Error:this warning is that reflective operations on this class will incorrectly
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:indicate that it is _not_ an inner class.
:app:transformClassesWithDexForDebug FAILED
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.

> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_77\bin\java.exe'' finished with non-zero exit value 2"

So I want to generate my own jar.How to generate?

**Comment by jpwsutton** [comment]
I've not seen this error before when using the Java client in Android Studio, have you considered using the purpose built Android Service instead? https://github.com/eclipse/paho.mqtt.android

If you wish to build your own jar, just follow the instructions in our README.md: https://github.com/eclipse/paho.mqtt.java#building-from-source

**Comment by sunfeng90** [comment]
OK，Thx
