### ISSUE TITLE
Deadlock in Websocket Disconnect

### ISSUE THREAD

**Issue by dobermai** [eclipse-paho/paho.mqtt.java#244]
Please fill out the form below before submitting, thank you!
- [x] Bug exists Release Version 1.1.0 ( Master Branch)
- [x] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Develop Branch)

When Paho sends a DISCONNECT message and has no chance to close the socket itself (e.g. because the broker closes the socket before or something bad happened between the DISCONNECT and socket close), Paho deadlocks forever. This is a critical bug we observed that caused client applications to get unresponsive forever.

We have a fix and are going to submit a Pull Request.

Analysis:

There is a Deadlock in the `org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketReceiver`.
When `MqttAsyncClient.disconnect()` is called, it will create a new thread, that eventually calls WebSocketReceiver.stop().
The stop method waits until the receiver Thread is rejoined.

```
public void stop() {
   ...
   synchronized (lifecycle) {
       ...
      // Wait for the thread to finish
      receiverThread.join();
       ...
   }
   ...
}
```

In case the receiver thread catches an exception, it will also try to execute the stop method before finishing.

```
public void run() {
   final String methodName = "run";
   while (running && (input != null)) {
      try {
               ...
      } catch (IOException ex) {
         // Exception occurred whilst reading the stream.
         this.stop();
      }
   }
}

```

Since a part of the stop method is synchronized, both of the [WebSocketReceiver.stop()](url) calls will never return.

**Comment by jpwsutton** [comment]
@dobermai This was included in the nightly build last night: https://hudson.eclipse.org/paho/view/Java%20Client/job/paho-java-dev-nightly/1056/ and so will be available to test in: https://repo.eclipse.org/content/repositories/paho-snapshots/org/eclipse/paho/org.eclipse.paho.client.mqttv3/1.1.1-SNAPSHOT/org.eclipse.paho.client.mqttv3-1.1.1-20160901.041436-24.jar
