### ISSUE TITLE
Add the ability to simulate an unclean disconnect 

### ISSUE THREAD

**Issue by mattrpav** [eclipse-paho/paho.mqtt.java#247]
It would be really handy to have an API call to simulate an unclean disconnect in order for the LW message to be triggered. This would also close a functionality gap between the FuseSource MQTT Java client, which has the ability to do this.

Please fill out the form below before submitting, thank you!
- [X] Bug exists Release Version 1.1.0 ( Master Branch)
- [X] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Develop Branch)

If this is a bug regarding the Android Service, please rasie the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

Reference: https://bugs.eclipse.org/bugs/show_bug.cgi?id=499935

**Comment by mattrpav** [comment]
Any feedback on this PR?

**Comment by jpwsutton** [comment]
PR Merged.
