### ISSUE TITLE
repo.eclipse.org is dying too often lately

### ISSUE THREAD

**Issue by noordawod** [eclipse-paho/paho.mqtt.java#248]
Whoever is managing this/these server(s), maybe it's time to commission new one(s). I've noticed that the service at repo.eclipse.org is dying every few days, causing the build process to stuck forever.

Thank you.

Please fill out the form below before submitting, thank you!
- [ ] Bug exists Release Version 1.1.0 ( Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Develop Branch)

If this is a bug regarding the Android Service, please raise the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

PS: You have an English error in the form above: you write "rasie" instead of "raise".

**Comment by jpwsutton** [comment]
This problem has been noticed over on bugs.eclipse.org too and a bug has been raised requesting that repo.eclipse.org is given a higher SLA(https://wiki.eclipse.org/IT_SLA)  level: https://bugs.eclipse.org/bugs/show_bug.cgi?id=500244.

Hopefully that goes ahead and then we'll have some better uptime.
