### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by IceFireg** [eclipse-paho/paho.mqtt.java#252]
Hello, I am a beginner in mqtt. As the title shows, after I downloaded this code and built it, I created a new java file under the _**org.eclipse.paho.sample.mqttv3app/src/main/java/org/eclipse/paho/sample/mqttv3app**_directory. Then I put my code into it in order to achieve my functions. However I found I can't run it. What should I do?

**Comment by miketran78727** [comment]
I am not sure what problem you are experiencing.  For beginners, I suggest to look at the Getting Started section of this paho.mqtt.java repository https://github.com/eclipse/paho.mqtt.java  There are many links that you can explore.

**Comment by IceFireg** [comment]
For example, if I want to create a mqtt client, what should I do?

**Comment by miketran78727** [comment]
You would write the application code (publisher/receiver). For example the following code (publisher) connects and publish message ""Message from MqttPublishSample" to topic "MQTT Examples"

You will need to write similar code for receiver to subscribe to topic "MQTT Examples" and it will receive the message.

```
import org.eclipse.paho.client.mqttv3.MqttClient;
import org.eclipse.paho.client.mqttv3.MqttConnectOptions;
import org.eclipse.paho.client.mqttv3.MqttException;
import org.eclipse.paho.client.mqttv3.MqttMessage;
import org.eclipse.paho.client.mqttv3.persist.MemoryPersistence;

public class MqttPublishSample {

    public static void main(String[] args) {

        String topic        = "MQTT Examples";
        String content      = "Message from MqttPublishSample";
        int qos             = 2;
        String broker       = "tcp://iot.eclipse.org:1883";
        String clientId     = "JavaSample";
        MemoryPersistence persistence = new MemoryPersistence();

        try {
            MqttClient sampleClient = new MqttClient(broker, clientId, persistence);
            MqttConnectOptions connOpts = new MqttConnectOptions();
            connOpts.setCleanSession(true);
            System.out.println("Connecting to broker: "+broker);
            sampleClient.connect(connOpts);
            System.out.println("Connected");
            System.out.println("Publishing message: "+content);
            MqttMessage message = new MqttMessage(content.getBytes());
            message.setQos(qos);
            sampleClient.publish(topic, message);
            System.out.println("Message published");
            sampleClient.disconnect();
            System.out.println("Disconnected");
            System.exit(0);
        } catch(MqttException me) {
            System.out.println("reason "+me.getReasonCode());
            System.out.println("msg "+me.getMessage());
            System.out.println("loc "+me.getLocalizedMessage());
            System.out.println("cause "+me.getCause());
            System.out.println("excep "+me);
            me.printStackTrace();
        }
    }
}
```

**Comment by IceFireg** [comment]
I have tried, but I failed.
![2016-08-30 15-22-36](https://cloud.githubusercontent.com/assets/18031253/18079936/ce45bf60-6ec5-11e6-9b1a-d749211ce6d3.png)
Why??

**Comment by miketran78727** [comment]
I am not sure how you setup your java development environment.  I cannot read the characters on your console. I suggest that you use eclipse IDE.  Import the this paho.mqtt.java project into eclipse.  That will simplify your Java development

**Comment by IceFireg** [comment]
Thanks for your advice. After I imported, some errors appeared.
![2016-08-31 21-26-58](https://cloud.githubusercontent.com/assets/18031253/18130600/31094a16-6fc2-11e6-9a02-a9e491fcbb7d.png)
I wonder if these errors will affect my program?

**Comment by jpwsutton** [comment]
I think those errors show when you haven't installed a particular plugin in eclipse. They won't stop you running your sample, but you should be able to get rid of them by looking at the resolution and clicking to install the missing plugins.

**Comment by user-mw** [comment]
1. Download Eclipse IDE (the last version is NEON).
2. Create new java project.
3. Transform your project to maven project (Configure->Convert to Maven project).
4. Find file pom.xml and add content that you see in "Downloading" in special sections (repositories and dependencies). You must do it using text editor (not Eclipse).
5. Close your Eclipse and Run again. You must see dependencies. After that you can copy code in "Getting Started" to your project. Run it and see that message was sent to the broker.
