### ISSUE TITLE
Outdated Online JavaDoc Resource

### ISSUE THREAD

**Issue by bartmark** [eclipse-paho/paho.mqtt.java#253]
The JavaDoc accessible by http://www.eclipse.org/paho/files/javadoc/ is outdated.
I got this link from http://www.eclipse.org/paho/clients/java/ in the section Documentation.

For e.g. the interface MqttCallbackExtended is missing and the subscribe methods in IMqttClient don't reflect the possibility with an IMqttMessageListener as a callback.

![image](https://cloud.githubusercontent.com/assets/20068649/18120636/e467f1dc-6f60-11e6-9f09-2b06666cd382.png)

**Comment by jpwsutton** [comment]
Thanks for spotting this, I've uploaded the latest javadoc onto the eclipse.org site here: https://www.eclipse.org/paho/files/javadoc/index.html
