### ISSUE TITLE
Question about multithreading in subscription

### ISSUE THREAD

**Issue by jxcheng008** [eclipse-paho/paho.mqtt.java#264]
I am new in MQTT. I try to create multithread client cluster. When I setup the subscription, the message publised with QoS 2 is  ##duplicate. How can I avoid the duplicate message when doing the multithreading subscription?

**Comment by jpwsutton** [comment]
Hi, When you say you are doing multithreaded subscriptions, do you mean that you have multiple instances of the Paho client and you are making the same subscription with each one?

If this is the case, then getting duplicates is expected, you will need to remove the duplicates yourself in your application logic. 

You could look into changing your application slightly where you have only one instance of the Paho client that simply puts incoming messages onto a queue that your multiple worker threads can then consume, this would remove the possibility of getting duplicate messages.

**Comment by jxcheng008** [comment]
Yes, I have multiple instances of the Paho client and making the same subscription with each one.

**Comment by jxcheng008** [comment]
yes, I have multiple instances of the Paho client with same subscription for each one. 
Is it possible to use the message ID to determine whether a message is been processed or not by using QoS 2 for both publication and subscription?

**Comment by jpwsutton** [comment]
As the Message ID is something that the Paho client uses internally, it is not guaranteed that one incoming message will have the same ID across all clients. So it's unadvisable to use this to see if you have already processed the message from another client.

**Comment by miketran78727** [comment]
One suggestion is to put your own message identifier in the payload.

Note that if the MQTT broker has shared subscriptions capability, the applications do not have handle duplicated messages because only one subscriber will receive the message. See http://www.hivemq.com/blog/mqtt-client-load-balancing-with-shared-subscriptions/

**Comment by jxcheng008** [comment]
thanks very much!
