### ISSUE TITLE
use pure ip as host in sslsocket way . the dns lookups use many time .

### ISSUE THREAD

**Issue by fuminwen** [eclipse-paho/paho.mqtt.java#269]
Please fill out the form below before submitting, thank you!
- [Yes ] Bug exists Release Version 1.1.0 ( Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Develop Branch)

If this is a bug regarding the Android Service, please rasie the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

in TCPNetworkModule.java and the start() function.
when use a pure ip and use ssl way (next call to SSLNetworkModule) , it can case a reverse DNS lookup problem. this action make a long wait before ssl HandShake when the tcp has conneted. In the time it wait the devics will send dns request and it can be see in wireshark.
However , it is a issu by manys sumbit in stackoverflow such 
[http://stackoverflow.com/questions/3193936/how-to-disable-javas-ssl-reverse-dns-lookup/13067916#13067916](url)

Condise this :::

SocketAddress sockaddr = null;
if (AddressUtils.isIPAdress(host)) {
    sockaddr = new InetSocketAddress(
            InetAddress.getByAddress("", AddressUtils.ipv4Address2BinaryArray(host)), port);
} else {
    sockaddr = new InetSocketAddress(host, port);
}
socket = factory.createSocket();
socket.connect(sockaddr, conTimeout*1000);

**Comment by jpwsutton** [comment]
Thanks for finding this issue.
This sounds like the best way forward, however I've not seen this AddressUtils class before, I'm guessing it's just pseudocode?
We also need to make sure that we work with both IPV4 and IPV6.

**Comment by fuminwen** [comment]
yes , AddressUtils just a java-easy-utils-source in my project for trans some ip's action . As you say, it should confirm the problem in ipv6 . When I was in the validation of my idea , I just use a ipv4 way to confirm it . However in the complete solution it must include both.

**Comment by jpwsutton** [comment]
I've had a look through the various APIs in InetAddress, and it looks this will accomplish what we need whilst maintaining simplicity:

`SocketAddress sockaddr = new InetSocketAddress(InetAddress.getByName(host), port);`

http://docs.oracle.com/javase/6/docs/api/java/net/InetAddress.html#getByName(java.lang.String)

getByName will check that the IP address is valid, if it is, it will return straight away without doing any lookup.
