### ISSUE TITLE
repo.eclipse.org DOWN

### ISSUE THREAD

**Issue by Byteschmiede** [eclipse-paho/paho.mqtt.java#271]
Hi there,

The Maven Repository is down and i can't build my app. Please fix that :)

Thanks

**Comment by jpwsutton** [comment]
A bug against eclipse has already been raised here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=502356, the repository should be back online as soon as possible.

**Comment by jpwsutton** [comment]
Also, keep in mind that you can also use Maven Central: http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.eclipse.paho%22
