### ISSUE TITLE
When paho reconnected,the pesistence will invalid

### ISSUE THREAD

**Issue by LuniChang** [eclipse-paho/paho.mqtt.java#277]
Please fill out the form below before submitting, thank you!
- [ ] Bug exists Release Version 1.1.0 ( Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Develop Branch)

If this is a bug regarding the Android Service, please rasie the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

Hi
I'm using the paho as MQTT client in Android to connect the mosquitto .
Thought I had set the "persistence true" and "options.setCleanSession(false)".
I publish a message When I shutdown the wifi that my MQTT client has disconnected,
but it dose't receive any message after it has reconnected.

I'm use paho v1.1 and mosquitto v1.4.10.
I'm also issue this problem in mosquitto's page.
Sorry for my bad English.

Thanks.

**Comment by jpwsutton** [comment]
Persistence is actually used for persisting QoS 1 and 2 messages in the case of an application crash. What you want to be using as well is the DisconnectedBuffer.

Ass you need to do is create a new DisconnectedBufferOptions object (https://www.eclipse.org/paho/files/javadoc/org/eclipse/paho/client/mqttv3/DisconnectedBufferOptions.html), make sure you enable it in the Options.

And then set it in the MqttAsyncClient (https://www.eclipse.org/paho/files/javadoc/org/eclipse/paho/client/mqttv3/MqttAsyncClient.html#setBufferOpts-org.eclipse.paho.client.mqttv3.DisconnectedBufferOptions-)

The Disconnected Buffer will queue up messages sent from your android device whilst the network is disconnected and will then send them once the connection is re-established.

If you want to make sure you receive messages to any subscriptions also on the device, make sure you are subscribing with QoS 1 or 2

**Comment by LuniChang** [comment]
Thank you very much.
I had just set the "subscribe" in qos 2,but didn't set the "publish" in qos 2.
Now , it has worked.
