### ISSUE TITLE
Get messages

### ISSUE THREAD

**Issue by user-mw** [eclipse-paho/paho.mqtt.java#279]
Hello to everybody. Is it possible to get messages from topic that my client subscribed?
And is it possible to get clientID that send messages? I can't find something like that in documentation.

**Comment by miketran78727** [comment]
Please take a look at sample code: https://github.com/eclipse/paho.mqtt.java/blob/master/org.eclipse.paho.sample.mqttv3app/src/main/java/org/eclipse/paho/sample/mqttv3app/Sample.java

The application receives messages in the callback `public void messageArrived(String topic, MqttMessage message)`: see https://github.com/eclipse/paho.mqtt.java/blob/master/org.eclipse.paho.sample.mqttv3app/src/main/java/org/eclipse/paho/sample/mqttv3app/Sample.java#L349

No, the client ID is not part of the message.  If you want the receivers to know the client ID of the publisher, you can put the client ID in the payload and the receivers will need to parse the payload to get the client ID of the publisher.

**Comment by user-mw** [comment]
Thank you for your reply, but I still can't understand how can I use in the client sample [here](https://eclipse.org/paho/clients/java/) (Getting started section). Please help again. It is very interesting task for me.

**Comment by miketran78727** [comment]
The tiny sample on this web page https://eclipse.org/paho/clients/java/  is a simple publisher.   Therefore, the code does not need to implement MqttCallback  interface.  Please see sample code: https://github.com/eclipse/paho.mqtt.java/blob/master/org.eclipse.paho.sample.mqttv3app/src/main/java/org/eclipse/paho/sample/mqttv3app/Sample.java

**Comment by user-mw** [comment]
Everything is fine. Thank you for help and for your work.
