### ISSUE TITLE
how to get subscribe topic data

### ISSUE THREAD

**Issue by daniel6435** [eclipse-paho/paho.mqtt.java#281]
hi

i try to receive the subscribe topic data and show it in text view. Below is the code for publish and subscribe.

The publish code:
sampleClient.publish(topic, message);

The subscribe code:
sampleClient.subscribe(topic, qos);

and how to get the subscribed data.

thanks

**Comment by KiuIras** [comment]
You must implement _messageArrived_ callback:

public void messageArrived(String topic, MqttMessage message) throws MqttException {
    // Called when a message arrives from the server that matches any
    // subscription made by the client
    String time = new Timestamp(System.currentTimeMillis()).toString();
    System.out.println("Time:\t" +time +
                           "  Topic:\t" + topic +
                           "  Message:\t" + new String(message.getPayload()) +
                           "  QoS:\t" + message.getQos());
}

[sample code](https://github.com/eclipse/paho.mqtt.java/blob/master/org.eclipse.paho.sample.mqttv3app/src/main/java/org/eclipse/paho/sample/mqttv3app/Sample.java)

**Comment by daniel6435** [comment]
hi KiuIras,

I am not very familiar with android coding, so below is my code when the button clicked will publish the message to server and subscribe it.

 btn1.setOnClickListener(new Button.OnClickListener() {
            @Override
            public void onClick(View v) {

```
            try {
                MqttClient sampleClient = new MqttClient(broker, clientId, persistence);
                MqttConnectOptions connOpts = new MqttConnectOptions();
                connOpts.setCleanSession(true);
                System.out.println("Connecting to broker: " + broker);
                sampleClient.connect(connOpts);
                System.out.println("Connected");
                System.out.println("Publishing message: " + content);
                MqttMessage message = new MqttMessage(content.getBytes());
                sampleClient.publish(topic, message);
                System.out.println("Message published");
                sampleClient.subscribe(topic, 1);
                sampleClient.disconnect();

            } catch (MqttException me) {
                System.out.println("reason " + me.getReasonCode());
                System.out.println("msg " + me.getMessage());
                System.out.println("loc " + me.getLocalizedMessage());
                System.out.println("cause " + me.getCause());
                System.out.println("excep " + me);
                me.printStackTrace();
            }


        }
    });
```

so for the messageArrived function where i need to call this function

thank a lot~

**Comment by KiuIras** [comment]
I have no experience with Android coding but I suppose that your activity should implements _MqttCallback_ interface.
Then you must define _messageArrived_ method: you can retrieve messages received on subscribed topics here.
[docs](https://www.eclipse.org/paho/files/javadoc/org/eclipse/paho/client/mqttv3/MqttCallback.html#messageArrived-java.lang.String-org.eclipse.paho.client.mqttv3.MqttMessage-)

I have no idea if it is the right way, but it should works.

**Comment by miketran78727** [comment]
Perhaps follow an example in the Android repository will help?
Example: https://github.com/eclipse/paho.mqtt.android/tree/master/paho.mqtt.android.example

**Comment by livsmelly** [comment]
Hey guys,

I was wondering if you could elaborate on this. I understand you need a callback function, however what if I wanted to save the contents of the payload as a variable? 

For the callback method (Message arrived) you cannot get it to return the payload as a String... so how would you go about doing this?
