### ISSUE TITLE
Javadoc error in IMqttClient

### ISSUE THREAD

**Issue by KiuIras** [eclipse-paho/paho.mqtt.java#282]
Documentation for publish (String topic, MqttMessage message) says that it can throws _java.lang.IllegalArgumentException_ if QoS value is not 0, 1 or 2 but this method doesn't have a QoS parameter.
[Javadoc](https://www.eclipse.org/paho/files/javadoc/org/eclipse/paho/client/mqttv3/IMqttClient.html#publish-java.lang.String-org.eclipse.paho.client.mqttv3.MqttMessage-)
- [x] Bug exists Release Version 1.1.0 ( Master Branch)
- [x] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Develop Branch)

**Comment by jpwsutton** [comment]
Thanks for spotting this, PR #283 merged into develop now.
