### ISSUE TITLE
The "reconnect()" function in MqttClient will not work properly

### ISSUE THREAD

**Issue by e8035669** [eclipse-paho/paho.mqtt.java#284]
hi everyone
i use MqttClient and implements MqttCallback
When connectionLost() called i use reconnect() function all the connection will close.

I found source code in MqttAsyncClient reconnection() function, it call stopReconnectCycle() and you said "we don`t want to spam the server"
at MqttAsyncClient.java line 1120 reconnectTimer.cancel();
this function call will get Null pointer Exception

if i use auto reconnect ,this function call can be called perfectly

**Comment by jpwsutton** [comment]
This was fixed in the develop branch from issue #249. You can get this by using the SNAPSHOT build currently.
