### ISSUE TITLE
tag is missing for version 1.1.0?

### ISSUE THREAD

**Issue by andy3005** [eclipse-paho/paho.mqtt.java#293]
Hi, 

I have just checked the available tags in the repository and missed a tag for the version 1.1.0. It is also missing in the release overview here https://github.com/eclipse/paho.mqtt.java/releases (although it is available in maven central). Is there any special reason why the tag for the version doesn't exist and why it is not mentioned on the list of releases? For all others e.g. v1.0.2 there is a tag existing and it is mentioned in the release overview.

Thanks, Andy

**Comment by jpwsutton** [comment]
Hi Andy,

Thanks for spotting that, It looks like I forgot to do a `git push --tags` back when we released. I've now pushed the tag up which matches the commit ID of the artifacts in the repositories. 
Build: https://hudson.eclipse.org/paho/view/Java%20Client/job/paho-java-master-release/39/
