### ISSUE TITLE
WebSocketHandshake.verifyWebSocketKey - sec-websocket-accept not properly validated

### ISSUE THREAD

**Issue by andy3005** [eclipse-paho/paho.mqtt.java#295]
- [X] Bug exists Release Version 1.1.0 ( Master Branch)
- [X] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Develop Branch)

Hi,

the sec-websocket-accept header is not checked against the original key issued by the client. The following statement just checks the key with itself instead of the accept key sent in the response.

if(!encodedSha1Bytes.equals(encodedSha1Bytes)){
			throw new HandshakeFailedException();
		}	

	private void verifyWebSocketKey(String key, String accept) throws NoSuchAlgorithmException, HandshakeFailedException{
		// We build up the accept in the same way the server should
		// then we check that the response is the same.
		byte[] sha1Bytes = sha1(key + ACCEPT_SALT);
		String encodedSha1Bytes = Base64.encodeBytes(sha1Bytes).trim();
		**if(!encodedSha1Bytes.equals(encodedSha1Bytes)){**
			throw new HandshakeFailedException();
		}	
	}

Cheers, Andy

**Comment by jpwsutton** [comment]
Thanks @andy3005 I've fixed the verifyWebSocketKey method to check agains the accept key:

```
if(!encodedSha1Bytes.equals(accept.trim())){
			throw new HandshakeFailedException();
		}
```
