### ISSUE TITLE
Underlying TCP/IP connection isn't closed (FYN) calling close() method

### ISSUE THREAD

**Issue by ppatierno** [eclipse-paho/paho.mqtt.java#297]
Please fill out the form below before submitting, thank you!

- [x] Bug exists Release Version 1.1.0 ( Master Branch)
- [x] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Develop Branch)

I see that calling the close() method on the MqttClient class instance, doesn't send the FYN on the underlying TCP/IP connection. It happens only with disconnect() after sending the DISCONNECT method.
I think that close() should close the underlying TCP/IP connection in the right way.

**Comment by ppatierno** [comment]
From the source code (close() method in ClientComms), it seems that you can't call close() before disconnect() so an exception with "client is connected" is thrown. Is it a wanted behaviour ?

It means that if application catch the exception, the client is still usable because nothing happens at TCP/IP level.

In my scenario I'm using the Java client for testing purpose and I need a "brute disconnection", so having client closes the TCP/IP connection (with FYN, ...) without sending DISCONNECT before (that should be a "clean disconnection").

Could be useful having a "force" parameter to close() method in order to force closing TCP/IP connection even without disconnect ?

**Comment by jpwsutton** [comment]
@ppatierno Thanks, this sounds like a good idea, I'll pop it on the current milestone as it should be a fairly minor change to the API.
