### ISSUE TITLE
Question regarding 

### ISSUE THREAD

**Issue by milosjovac** [eclipse-paho/paho.mqtt.java#305]
Hi all,

Documentation in README.md states that "The latest release version is 1.1.0". I can see that you have release 1.2.0 [completed](https://github.com/eclipse/paho.mqtt.java/milestone/1?closed=1). Is there a reason why this version is not available via [Maven Repository](https://mvnrepository.com/artifact/org.eclipse.paho/org.eclipse.paho.client.mqttv3)?

I can also see that [people are using v1.2.0](https://github.com/eclipse/paho.mqtt.java/issues/272). How can I obtain this version? I wanted to build from source but when I browse [develop branch](https://github.com/eclipse/paho.mqtt.java/blob/develop/pom.xml#L7) there is 1.1.1-SNAPSHOT version only.

Thanks,
Milos Jovac

**Comment by jpwsutton** [comment]
@milosjovac Sorry, it's a bit confusing. The 1.2.0 version refers to the Eclipse Project release version that encompasses all of the Paho Clients (http://projects.eclipse.org/projects/technology.paho).

The latest release is 1.1.0 (Master Branch), and the Snapshot release is 1.1.1 (develop branch)

**Comment by milosjovac** [comment]
Oh, I see. Thank you for clarification.
