### ISSUE TITLE
not able to create more than 3k connection with RabbitMq

### ISSUE THREAD

**Issue by lotiyahardik** [eclipse-paho/paho.mqtt.java#306]
Hello, 

i'm  Using Mqtt client v3 , with Rabbitmq3.6.6

am getting exception related to Memory Error.

java.lang.OutOfMemoryError: unable to create new native thread 

my snippet code is as under

> int max_connections =4000;
> String broker = "tcp://xxx.xxx.x.xx:1883";
> String clientId = "Publisher";
> String content="Hii";
> int qos=1;
> String topic="Cluster";
> 
> 
> MemoryPersistence persistence = new MemoryPersistence();
> MqttClient sampleClient[] = new MqttClient[max_connections];
> 
> Thread t[] = new Thread[max_connections];
> MqttConnectOptions connOpts = new MqttConnectOptions();
> connOpts.setCleanSession(true);
> 
> for (int i = 0; i < max_connections; i++) {
>     try {
>         sampleClient[i] = new MqttClient(broker, clientId + "" + i, persistence);
>         sampleClient[i].connect(connOpts);
>     } catch (MqttException ex) {
>         ex.printStackTrace();
>         return;
>     } 
> } 

In ubuntu PC upto 3k only and Win PC 7k only 
any system level configuration requires for the same?
or In paho client I missed some thing?

**Comment by jpwsutton** [comment]
Each instance of a client uses 3+ threads in java and takes up memory. You will need to increase the amount of memory that the JVM has access too and potentially the available memory on the PC as well. I'm guessing that you're trying to stress test RabbitMQ? You might be able to squeeze out more connections by using the Paho C client instead, or the embedded C client as that is single threaded and both have smaller footprints than the Java client.

**Comment by lotiyahardik** [comment]
ok jpwsutton, thanks for your quick reply, Just I want to know as I described WinPc and UbuntuPc. its huge difference while creating a connection. 
Its related to missing configuration in Ubuntu?

**Comment by jpwsutton** [comment]
It could also be that linux and windows have different maximum thread limits. You would need to look at the ulimits on your ubuntu machine to see what the limit is, I'm not sure how Windows manages threads..

**Comment by lotiyahardik** [comment]
OK, Yes I checked this one in Ubuntu, 
and in that I updated 'max user processes'= unlimited

Then I restart PC and check this limit, but still same Exception getting.

**Comment by jpwsutton** [comment]
In this case, it might just be that you're hitting a hard limit in the OS. My only advice is to not make so many clients on one machine. As there isn't any real use case for this, I don't think it's an issue with the client itself.
