### ISSUE TITLE
transformClassesWithJarMergingForDebug'.

### ISSUE THREAD

**Issue by kangdawei** [eclipse-paho/paho.mqtt.java#308]
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoIcsImpl.class

**Comment by jpwsutton** [comment]
Hi, How is this related to the Java client?
