### ISSUE TITLE
Sync MqttClient receiver thread deadlock

### ISSUE THREAD

**Issue by milosjovac** [eclipse-paho/paho.mqtt.java#310]
- [ YES ] Bug exists Release Version 1.1.0 ( Master Branch)
- [ YES ] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Develop Branch)

When publishing message with Qos 0 from within MqttCallback.messageArrived callback method, receiving thread freezes.

Test class:

    import org.eclipse.paho.client.mqttv3.*;
    import javax.net.ssl.SSLContext;
    import javax.net.ssl.SSLSocketFactory;
    import java.util.UUID;
    import java.util.concurrent.BlockingQueue;
    import java.util.concurrent.LinkedBlockingQueue;

    public class MqttDeadLockTest {
    private static final String broker = "ssl://MY_SECURE_BROKER:8883";
    private BlockingQueue<String> keepMainAlive = new LinkedBlockingQueue<>();

    public static void main(String[] args) throws InterruptedException {
        new MqttDeadLockTest().start().keepMainAlive.take();
    }

    private MqttDeadLockTest start() {
        try {
            MqttClient mqttClient = new MqttClient(broker, "Test_" + UUID.randomUUID().toString(), null);
            mqttClient.setCallback(new MqttCallback() {
                @Override
                public void connectionLost(Throwable throwable) {
                    System.out.println("Connection lost");
                }

                @Override
                public void messageArrived(String s, MqttMessage mqttMessage) throws Exception {
                    System.out.println("Message arrived");
                    MqttMessage responseMsg = new MqttMessage();
                    responseMsg.setPayload("Random payload".getBytes());
                    responseMsg.setQos(0);
                    System.out.println("Sending response");
                    // After publishing Qos 0 message inside messageArrived callback method
                    // receiving thread freezes and no new messages can go trough.
                    // Qos 1 and 2 works just fine
                    mqttClient.publish("iot/TEST/pubTopic", responseMsg);
                }

                @Override
                public void deliveryComplete(IMqttDeliveryToken iMqttDeliveryToken) {
                    System.out.println("Delivery complete");
                }
            });

            // Setting up SSLSocketFactory
            SSLContext sc = SSLContext.getInstance("TLSv1");
            sc.init(null, null, null);
            SSLSocketFactory ssf = sc.getSocketFactory();

            // Setting up connection options
            MqttConnectOptions connOpts = new MqttConnectOptions();
            connOpts.setSocketFactory(ssf);

            // CONNECT
            mqttClient.connect(connOpts);

            // Subscribe
            mqttClient.subscribe("iot/TEST/subTopic");
        } catch (Exception e) {
            System.out.println("Error starting MqttClient " + e.getCause());
        }

        return this;
    }}

For sending test mqtt messages (mqtt-spy)[https://kamilfb.github.io/mqtt-spy/] is used.

Test steps: 
- Start provided test class with broker url updated
- Start mqtt-spy and connect to the same broker url
- Subscribe mqtt-spy to the [following topics](http://prnt.sc/dk6o1b):
-- iot/TEST/pubTopic
-- iot/TEST/subTopic
- Publish multiple messages from mqtt-spy to the topic: iot/TEST/subTopic

Expected behavior:
1. mqtt-spy publishes multiple messages to the topic: iot/TEST/subTopic
2. IDE receives multiple messages from the topic: iot/TEST/subTopic
3. IDE publishes multiple messages to the topic: iot/TEST/pubTopic
4. mqtt-spy receives multiple messages from the topic: iot/TEST/pubTopic
5. MqttClient receiving thread is running

Snapshot tests
-
Test result for Qos 0:
1. [PASS](http://prnt.sc/dk6emv)
2. [FAIL](http://prnt.sc/dk6d7q)
3. [FAIL](http://prnt.sc/dk6d7q)
4. [FAIL](http://prntscr.com/dk74so)
5. [PASS](http://prnt.sc/dk6dei) - Running but will never receive new messages

Test results for Qos 1 and 2:
1. [PASS](http://prnt.sc/dk6emv)
2. [PASS](http://prnt.sc/dk6e3u)
3. [PASS](http://prnt.sc/dk6e3u)
4. [PASS](http://prnt.sc/dk6emv)
5. [PASS](ttp://prnt.sc/dk6dei) - Running and will receive new messages

Stable tests
-
1. [PASS](http://prnt.sc/dk6emv)
2. [FAIL](http://prnt.sc/dk6d7q)
3. [FAIL](http://prnt.sc/dk6d7q)
4. [FAIL](http://prntscr.com/dk74so)
5. FAIL - Permanent WAIT occurs

Test results for Qos 1 and 2:
1. [PASS](http://prnt.sc/dk6emv)
2. [PASS](http://prnt.sc/dk6e3u)
3. [PASS](http://prnt.sc/dk6e3u)
4. [PASS](http://prnt.sc/dk6emv)
5. [PASS](http://prnt.sc/dk6dei) - Running and will receive new messages

**Comment by miketran78727** [comment]
Correct me if I am wrong here.  The synchronous client is not designed to publish response messages in its callback messageArrived().  In our tests, the client can be both publisher and subscriber, but they are on different thread because we know publish will block.

**Comment by milosjovac** [comment]
> The synchronous client is not designed to publish response messages in its callback messageArrived().

@miketran78727 You might be right. Sending QoS 1 & 2 messages from inside messageArrived() callback works, but it doesn't mean QoS 0 should. Or even with 1 & 2 working that sending from callback is a good practice. I was most probably on the wrong lead. 

Anyhow it would be fun to understand why it is not the opposite, 0 working and 1 & 2 blocking, since their sending strategies are "more strict". 

> In our tests, the client can be both publisher and subscriber, but they are on different thread because we know publish will block.

Separate threads was the solution for me too.

**Comment by icraggs** [comment]
Ok, I think this is done.  The async client allows for more asynchronous behaviour, I'd like to note.
