### ISSUE TITLE
Unable to retrieve more than 120 retained messages a time 

### ISSUE THREAD

**Issue by sylvek** [eclipse-paho/paho.mqtt.java#311]
I did a simple test. 
I've published 4000 retained messages into my mosquitto broker. 
I subscribe the parent topic.. 
Only 120 messages are received.

I did the same test with "mqtt-java", and it received the all messages. 

- [x] Bug exists Release Version 1.1.0 ( Master Branch)
- [x] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Develop Branch)

**Comment by jpwsutton** [comment]
Could you show us some code that can re-create this please?

**Comment by sylvek** [comment]
Hey thank you for your time @jpwsutton … this is my JUnit test.

```
@Test
    public void should_handle_all_messages_from_native_mqtt_client() throws MqttException, InterruptedException
    {
        // Given
        final AtomicInteger incomingMessages = new AtomicInteger();
        final MqttClient client = new MqttClient("tcp://127.0.0.1:1883", "test", new MemoryPersistence());
        client.setCallback(new MqttCallbackExtended() {
            @Override
            public void connectionLost(Throwable cause)
            {
            }

            @Override
            public void messageArrived(String topic, MqttMessage message) throws Exception
            {
                incomingMessages.incrementAndGet();
            }

            @Override
            public void deliveryComplete(IMqttDeliveryToken token)
            {
            }

            @Override
            public void connectComplete(boolean reconnect, String serverURI)
            {
            }
        });
        client.connect();

        // When
        for (int i = 0; i < HUGE_AMOUNT_OF_MESSAGE; i++) {
            client.publish("test/test/" + i, "a message".getBytes(), 1, true);
        }

        // Then
        Thread.sleep(15_000L);
        client.subscribe("test/test/+", 1);
        Assertions.assertThat(incomingMessages.get()).isEqualTo(HUGE_AMOUNT_OF_MESSAGE);
    }
```
returns 120 instead of 4000, of… if i put the client.subscribe before my publish loop, it's working properly. (but i want to retrieve retained messages)

i have done a test with this client https://github.com/fusesource/mqtt-client and it works.

**Comment by sylvek** [comment]
i've tried with a more delay for my Thread.sleep (yes https://github.com/awaitility/awaitility is better) and i had the same result.

**Comment by sylvek** [comment]
from CommsReceiver.java, this part of code is called exactly 120 times.
and the last topic received is "test/test/120" (regarding to my unit test)

```
…
				} else {
					// A new message has arrived
					clientState.notifyReceivedMsg(message);
				}
…
```

**Comment by sylvek** [comment]
with an ActiveMQ (5.10) instead of a Mosquitto, i receive exactly 1001 messages.
maybe Paho Java Client does not read messages fast enough?

with an ActiveMQ (5.14) everything works... i'm a little bit confused, how may i explain it?

**Comment by jpwsutton** [comment]
If changing the broker yields different results, it may be due to a bug in the broker itself. I've tested this against the Paho Test broker (https://github.com/eclipse/paho.mqtt.testing) and was able to publish retained messages to over 400 topics and then subscribe and receive those messages. (I gave up after 500 messages).
You might want to follow up with the Mosquitto Project (https://github.com/eclipse/mosquitto) as I think it's a broker specific bug.

**Comment by sylvek** [comment]
Bonne année @jpwsutton !
i'm currently doing other tests and i have some 

```
! org.eclipse.paho.client.mqttv3.MqttException: Client non connecté
! at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
! at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java:166)
! at org.eclipse.paho.client.mqttv3.MqttAsyncClient.subscribe(MqttAsyncClient.java:835)
! at org.eclipse.paho.client.mqttv3.MqttClient.subscribe(MqttClient.java:322)
! at org.eclipse.paho.client.mqttv3.MqttClient.subscribe(MqttClient.java:315)
```

maybe this issue is similar .. by the way thank you for your time, i'm closing this issue by now.
