### ISSUE TITLE
rescheduleReconnectCycle causing java.lang.IllegalStateException: Timer was canceled

### ISSUE THREAD

**Issue by miketran78727** [eclipse-paho/paho.mqtt.java#325]
Please fill out the form below before submitting, thank you!

- [ x ] Bug exists Release Version 1.1.0 ( Master Branch)
- [ x ] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Develop Branch)

11	Caused by: java.lang.IllegalStateException: Timer was canceled
12	at java.util.Timer.scheduleImpl(Timer.java:561)
13	at java.util.Timer.schedule(Timer.java:459)
14	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.rescheduleReconnectCycle(MqttAsyncClient.java:1146)org.eclipse.paho.client.mqttv3
15	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.access$9(MqttAsyncClient.java:1141)org.eclipse.paho.client.mqttv3
16	at org.eclipse.paho.client.mqttv3.MqttAsyncClient$2.onFailure(MqttAsyncClient.java:1103)org.eclipse.paho.client.mqttv3
17	at org.eclipse.paho.client.mqttv3.internal.ConnectActionListener.onFailure(ConnectActionListener.java:161)org.eclipse.paho.client.mqttv3
18	at org.eclipse.paho.client.mqttv3.internal.ConnectActionListener.connect(ConnectActionListener.java:189)org.eclipse.paho.client.mqttv3
19	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.connect(MqttAsyncClient.java:579)org.eclipse.paho.client.mqttv3
20	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.attemptReconnect(MqttAsyncClient.java:1084)org.eclipse.paho.client.mqttv3
21	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.reconnect(MqttAsyncClient.java:1064)org.eclipse.paho.client.mqttv3
User is using a snapshot build develop branch.  I believe this rare race condition did occur because the application uses both automatic reconnect feature and call reconnect() directly.  

I suspect that this could happen in 2 scenarios:
 -  The server probably did CONNACK on CONNECT request on one thread and the server closed the first connection on the second CONNECT.
 - The application called reconnect() immediately after connectionLost(). The reconnect timer was cancelled because reconnect() was called. Then in onFailure() we rescheduled next attempt to connect .
 
I will submit a fix for this issue.

**Comment by miketran78727** [comment]
https://docs.oracle.com/javase/7/docs/api/java/util/Timer.html#cancel%28%29
````
public void cancel()

Terminates this timer, discarding any currently scheduled tasks. Does not interfere with a currently executing task (if it exists). Once a timer has been terminated, its execution thread terminates gracefully, and no more tasks may be scheduled on it. 
````
Therefore, reconnectTimer should be set to null after calling cancel() https://github.com/eclipse/paho.mqtt.java/blob/develop/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/MqttAsyncClient.java#L1221

**Comment by corneyl** [comment]
Shouldn't this issue be closed as the fix is released?

**Comment by jpwsutton** [comment]
Thanks @corneyl, good point!
