### ISSUE TITLE
Paho breaks SSL in a strange way, leading to a handshake_failure with a HTTP CONNECT proxy

### ISSUE THREAD

**Issue by holyjak** [eclipse-paho/paho.mqtt.java#335]
I can successfully connect to a MQTT server through a HTTP proxy supporting `HTTP CONNECT` thanks to a custom `SocketFactory` when creating sockets and sending HTTP requests manually. So it should also work with Paho - but it doesn't. Paho's attempt to connect ends up with a 

> javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

So I guess Paho does something strange to the JVM's SSL setup. The error doesn't contain enough details and I don't know Paho's code and JVM's SSL handling well enough to be able to troubleshoot this on my own, though I would be happy to assist as much as I can.

I have created an [example project to demonstrate the issue](https://github.com/jakubholynet/paho-handshake-error) including the [`ManualHttpsConnectionExample.java`](https://github.com/jakubholynet/paho-handshake-error/blob/master/src/main/java/experiment/ManualHttpsConnectionExample.java) that successfully connects to the MQTT server and the [`PahoSubscribeExample.java`](https://github.com/jakubholynet/paho-handshake-error/blob/master/src/main/java/experiment/PahoSubscribeExample.java) that fails to do so. To replicate the problem:

    git clone git@github.com:jakubholynet/paho-handshake-error.git
    cd ./paho-handshake-error
    mvn compile; mvn exec:java -Dexec.mainClass="experiment.Main"

Or simply have a look at the [README](https://github.com/jakubholynet/paho-handshake-error/blob/master/README.md) that also shows the output from both the manual and Paho connections.
---
Please fill out the form below before submitting, thank you!

- [x] Bug exists Release Version 1.1.0 ( Master Branch)
- [? ] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Develop Branch)

**Comment by jpwsutton** [comment]
Hi @jakubholynet,

The `javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure` would suggest that the issue is related to the SSL connection itself. Paho does not do anything with the SSL connection and simply hands over to the Java SSL Socket implementation.

A good place to start would be to run the code using the javax.net.debug flag: `mvn exec:java -Djavax.net.debug=SSL,handshake -Dexec.mainClass="experiment.Main"`

This will give you some extended debug information surrounding the SSL handshake as its happening. This StackOverflow question lists some good possible reasons for the failure as well: http://stackoverflow.com/questions/6353849/received-fatal-alert-handshake-failure-through-sslhandshakeexception

> 

> The handshake failure could have occurred due to various reasons:
> 
>  - Incompatible cipher suites in use by the client and the server. This would require the client to use (or enable) a cipher suite that is supported by the server.
> Incompatible versions of SSL in use (the server might accept only TLS v1, while the client is capable of only using SSL v3). Again, the client might have to ensure that it uses a compatible version of the SSL/TLS protocol.
>  - Incomplete trust path for the server certificate; the server's certificate is probably not trusted by the client. This would usually result in a more verbose error, but it is quite possible. Usually the fix is to import the server's CA certificate into the client's trust store.
>  - The cerificate is issued for a different domain. Again, this would have resulted in a more verbose message, but I'll state the fix here in case this is the cause. The resolution in this case would be get the server (it does not appear to be yours) to use the correct certificate.
> 
> Since, the underlying failure cannot be pinpointed, it is better to switch on the -Djavax.net.debug=all flag to enable debugging of the SSL connection established. With the debug switched on, you can pinpoint what activity in the handshake has failed.

**Comment by ghost** [comment]
Hi @jakubholynet,

I tested your example project.
In your SSLTunnelSocketFactory in line 233 you try to start an SSL handshake on this connection (https://github.com/jakubholynet/paho-handshake-error/blob/master/src/main/java/experiment/tunnel/SSLTunnelSocketFactory.java#L233) 

After removing this (result.startHandshake();) your example works fine behind my http/https proxy.

**Comment by holyjak** [comment]
Thanks a lot @mgedack , that simple fix works! Awesome, I would have never figured it out!
