### ISSUE TITLE
Where is the ClientComms.class?

### ISSUE THREAD

**Issue by huyuemiss** [eclipse-paho/paho.mqtt.java#338]
Please fill out the form below before submitting, thank you!

- [ √] Bug exists Release Version 1.1.0 ( Master Branch)
- [√ ] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Develop Branch)

I got source code from Maven and it exists, but I can't find is on the github. What's happen..

![image](https://cloud.githubusercontent.com/assets/7851267/23839472/4f2dbefa-07d9-11e7-9a5e-4dad36f236c3.png)

![image](https://cloud.githubusercontent.com/assets/7851267/23839488/69df478c-07d9-11e7-8a39-2722e4cb9cc7.png)

**Comment by jpwsutton** [comment]
Hi, ClientComms is a bit of an odd one. It lives on it's own in the java-templates directory [here](https://github.com/eclipse/paho.mqtt.java/blob/develop/org.eclipse.paho.client.mqttv3/src/main/java-templates/org/eclipse/paho/client/mqttv3/internal/ClientComms.java). There was a reason I'm sure of it, but I have no idea what it is. Either way, we don't really want to move it as it would count as a breaking API change that would generally offer fairly low benefit to anyone.

**Comment by huyuemiss** [comment]
OK,thanks for your help
