### ISSUE TITLE
SUB:The topic name MUST NOT contain any wildcard characters (#+)

### ISSUE THREAD

**Issue by LuckyH28** [eclipse-paho/paho.mqtt.java#340]
MqttTopic.validate(String topicString, boolean wildcardAllowed)
Why the value of  wildcardAllowed is fixed and equal to 'false'?

**Comment by jpwsutton** [comment]
You cannot publish to a wildcard topic. It is only fixed to false when validating topics that will be published to. In the case of subscriptions, the flag is set to true to allow wildcards.

**Comment by LuckyH28** [comment]
when debugger ,find that the value is fixed to false whether to publish a topic or subscribe a topic.
Confirm source code as well.
The use of jar is org.eclipse.paho.client.mqttv3-1.1.0.jar

**Comment by jpwsutton** [comment]
Could you link to the line in the code where you see this please?

**Comment by LuckyH28** [comment]
- 
![wildcard--fixed false](https://cloud.githubusercontent.com/assets/17567078/23946960/84e528a0-09b7-11e7-913d-a74749520952.png)

**Comment by jpwsutton** [comment]
getTopic is only used when checking if a topic is valid to publish to: https://github.com/eclipse/paho.mqtt.java/blob/master/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/MqttAsyncClient.java#L705

**Comment by zhangyangvip** [comment]
![image](https://user-images.githubusercontent.com/5343779/89291367-fdcc1f80-d68c-11ea-82af-0c8db49009fc.png)
![image](https://user-images.githubusercontent.com/5343779/89291577-5e5b5c80-d68d-11ea-8b80-833bfc957f79.png)

when I attempt to sub a topic which contain '#', the code may result this issue
