### ISSUE TITLE
How to disable the server certificate validation in case of connection to port 8883 of broker

### ISSUE THREAD

**Issue by KohliDev** [eclipse-paho/paho.mqtt.java#341]
Please fill out the form below before submitting, thank you!

- [Yes ] Bug exists Release Version 1.1.0 ( Master Branch)

Can someone guide me how to disable certificate validation of server as well as avoid passing client certificate while making SSL connection to broker?

**Comment by miketran78727** [comment]
Most MQTT brokers provide at least one non-secure port.  Why do you want to connect to a secure port without using TLS?  If you have a good reason, please explain.

**Comment by jpwsutton** [comment]
If you really want to do this, you would need to create your own socket factory that ignores the server certificate. You can do this by using MqttConnectOptions.setSocketFactory(SocketFactory).

**Comment by KohliDev** [comment]
Also how can I just disable the client cert check in paho java?

**Comment by jpwsutton** [comment]
I think the server would be checking the client certificate, so you would have to look at the server configuration to see how to disable this. Though by the sounds of it, you may as well just disable certificates altogether..

**Comment by fuomag9** [comment]
> I think the server would be checking the client certificate, so you would have to look at the server configuration to see how to disable this. Though by the sounds of it, you may as well just disable certificates altogether..

Local TLS traffic can still have a valid reason to exist without CA validation (reverse proxies have this as an option for example)
