### ISSUE TITLE
Version 1.1.1 isn't found in Maven Central

### ISSUE THREAD

**Issue by orrsella** [eclipse-paho/paho.mqtt.java#343]
The latest version 1.1.1 doesn't seem to be available in Maven Central:

http://repo1.maven.org/maven2/org/eclipse/paho/org.eclipse.paho.client.mqttv3/

Is that on purpose?

**Comment by jpwsutton** [comment]
Currently having some issues with out hudson build that stages it on the OSSRH, will update this issue once we have successfully deployed it.

**Comment by jpwsutton** [comment]
v1.1.1 is now available on both repo.eclipse.org and Maven Central: https://search.maven.org/#artifactdetails%7Corg.eclipse.paho%7Corg.eclipse.paho.client.mqttv3%7C1.1.1%7Ceclipse-plugin

**Comment by orrsella** [comment]
Thanks!
