### ISSUE TITLE
how to add that library to a gwt project ??

### ISSUE THREAD

**Issue by ilDirettore** [eclipse-paho/paho.mqtt.java#350]
thanks ! :D

**Comment by jpwsutton** [comment]
I'm not too up to date with GWT at the moment, what dependency system are you using? Maven, Gradle?

**Comment by ilDirettore** [comment]
Maven

**Comment by jpwsutton** [comment]
Should be as simple as adding this to your dependencies then:

```
 <dependency>
        <groupId>org.eclipse.paho</groupId>
        <artifactId>org.eclipse.paho.client.mqttv3</artifactId>
        <version>1.1.1</version>
    </dependency>
```

**Comment by ilDirettore** [comment]
Unfortunately GWT needs other files such as a .gwt.xml ...

**Comment by jpwsutton** [comment]
Oh, do you mean you want this to be running on the client side i.e. the Web Browser? In which case you will need to include https://github.com/eclipse/paho.mqtt.javascript in your html /  generated Javascript I think..
