### ISSUE TITLE
Peer verification using certificates

### ISSUE THREAD

**Issue by prmathur-microsoft** [eclipse-paho/paho.mqtt.java#351]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.1.1 ( Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Develop Branch)

If this is a bug regarding the Android Service, please raise the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

I’m using MQTT paho java for my device SDK developed at Microsoft. My IotHub service provides with a certificate when I attempt to connect. On my device I would like to inform my mqtt connection to verify the cert validity (for which I have public key). I could not seem to find an API call that would let me provide certificate (either via certstore or as a file) that will need verification on establishing a connection

Is this currently supported on 1.1.0 and if so can you please point me to the right API ?

**Comment by jpwsutton** [comment]
You should be able to do this by either supplying your own TLS Socket Factory (https://www.eclipse.org/paho/files/javadoc/org/eclipse/paho/client/mqttv3/MqttConnectOptions.html#setSocketFactory-javax.net.SocketFactory-)

Or by setting the SSL Properties(https://www.eclipse.org/paho/files/javadoc/org/eclipse/paho/client/mqttv3/MqttConnectOptions.html#setSSLProperties-java.util.Properties-)
