### ISSUE TITLE
Latest develop branch fails to connect after disconnect

### ISSUE THREAD

**Issue by matsukaz** [eclipse-paho/paho.mqtt.java#355]
Hi, looks like latest develop branch fails to connect after disconnect.
No exception, but callback is not called and MqttConnection#isConnected returns false.

[bbd6dc7](https://github.com/eclipse/paho.mqtt.java/commit/bbd6dc730cc88b09226086998735cfc5867582fc) commit works fine, but when I use [dd7970d](https://github.com/eclipse/paho.mqtt.java/commit/dd7970d1e3010a4af1c1bac76e0a0ce1de57c5d4) commit, it fails.

Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.1.1 ( Master Branch)
- [x] Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Develop Branch)

If this is a bug regarding the Android Service, please raise the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

**Comment by rajeefmk** [comment]
@matsukaz Was AutomaticReconnect enabled when you were testing this ?

**Comment by matsukaz** [comment]
I've tested this with AutomaticReconnect enabled and also disabled.
It happened in both cases.

I'm testing this using paho.mqtt.android's recent develop branch with some patches (to use message buffering)

**Comment by jpwsutton** [comment]
@matsukaz, can you confirm if this is still happening for you? The Integration tests for the Automatic Reconnect functionality seem to all be passing.

**Comment by matsukaz** [comment]
@jpwsutton Latest develop branch works fine now!
