### ISSUE TITLE
Regress: 1.1.1 couldn't resolve host name which contains underscore

### ISSUE THREAD

**Issue by yabooc** [eclipse-paho/paho.mqtt.java#356]
- [ Yes] Bug exists Release Version 1.1.1 ( Master Branch)
- [ Yes] Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Develop Branch)

If there is an underscore in the hostname, test_001.mqtt.iot.gz.baidubce.com for example, broker uri will be resolved as localhost:8883, which is the default value. 

MqttAsyncClient.createNetworkModule uses URI to parse broker uri in 1.1.1, which is quite different from 1.1.0. It's mostly an issue of URI itself. I'm using java8.
`
    URI uri = new URI("ssl://test_001.mqtt.iot.gz.baidubce.com:1884"); 
    uri.getPort();// -1
    uri.getHost();//null
`

**Comment by jpwsutton** [comment]
You're right, an issue has been raised about this against Java, but there hasn't been much movement on it (http://bugs.java.com/view_bug.do?bug_id=6587184). I don't really want to close this issue as it will be blocking a lot of people who are using underscores in their domain names. The URI parsing was added in commit 80f7df4 to enable Basic Auth for Websocket connections. I'll have a look to see if there is a better way to do this.

**Comment by mscheibler** [comment]
Are you aware that underscores are not allowed in host names according to [RFC2396](https://www.ietf.org/rfc/rfc2396.txt)?

**Comment by jpwsutton** [comment]
@mscheibler -  True, but domain names can have underscores in them (https://stackoverflow.com/a/2183140), I always find these two things a bit hard to coalesce personally, but it's probably best to accommodate the majority of users.

**Comment by mscheibler** [comment]
@jpwsutton These RFCs are hard to keep track of. I kept on reading and according to [RFC3986, Appendix A](https://tools.ietf.org/html/rfc3986#page-49) there are a lot more characters allowed than just the underscore.
`a-zA-Z0-9` plus `-._~!$&'()*+,;=` and percent encoded chars.
