### ISSUE TITLE
Publish without Buffering

### ISSUE THREAD

**Issue by ishaansrm** [eclipse-paho/paho.mqtt.java#365]
- [x] Bug exists Release Version 1.1.1 ( Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Develop Branch)

I have an instance of the AsyncClient with _disconnected buffering_ enabled. Now I would like only certain publishes to be exempted from buffering.

Is this supported, maybe via a workaround?

**Comment by jpwsutton** [comment]
I think the best way to accomplish this would be to add a check in your code before you send the message, and only send (buffer) the messages you want.

**Comment by ishaansrm** [comment]
Yes that's what i have done for now, but it's still possible for the publishing to fail even after my initial check showed a valid broker connection.

**Comment by jpwsutton** [comment]
How does the publish fail? If DisconnectedBuffering is enabled, the message should just be buffered until the connection is restored and the message can be sent. If you want to remove the message after buffering, you can always delete it: https://www.eclipse.org/paho/files/javadoc/org/eclipse/paho/client/mqttv3/internal/DisconnectedMessageBuffer.html
