### ISSUE TITLE
Release Version 1.0.2 , Some android system version unable to subscribe the topics 

### ISSUE THREAD

**Issue by fanghuafan** [eclipse-paho/paho.mqtt.java#373]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.1.1 ( Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Develop Branch)

If this is a bug regarding the Android Service, please raise the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

**Comment by jpwsutton** [comment]
If this is a bug against the android client please raise it against that project. Also, without any detail, we can't do anything about the issue.
