### ISSUE TITLE
On re connection call i am getting all the old publish message  with new publish message

### ISSUE THREAD

**Issue by karthik2883** [eclipse-paho/paho.mqtt.java#375]
I am using recent release 

```
org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.0
org.eclipse.paho:org.eclipse.paho.android.service:1.1.1
```

**This is my code**
   ```
final MqttConnectOptions conOpt = new MqttConnectOptions();
      conOpt.setCleanSession(false);
      conOpt.setMqttVersion(MqttConnectOptions.MQTT_VERSION_3_1_1);
      conOpt.setKeepAliveInterval(60);
     ```
on every reconnect call i am getting old publish message with new publish message 

```
 @Override
  public void messageArrived(String topic, MqttMessage message) throws Exception {

    //Get connection object associated with this object
    Connection c = Connections.getInstance(context).getConnection(clientHandle);

    //create arguments to format message arrived notifcation string
    Log.v("messageArrived",message.toString());
  
  }
```

As every time the network fluctuate on every re connection i am getting huge data as message (old publish message and new publish message) on messageArrived callback ..Tested with Vernemq , Hivemq   
Please revert back quickly as it is the major show stopper issue for me....

**Comment by miketran78727** [comment]
Since you set ```conOpt.setCleanSession(false);``` The server will resend un-ACKED QoS 1 & 2 messages when your client reconnects.

**Comment by karthik2883** [comment]
What is  un-ACKED messages  and how to set it properly

**Comment by miketran78727** [comment]
If you don't want to receive old messages, ````setCleanSession(true)````, which is the default.

You can read more about Clean Session flag in the MQTT specification : http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718030
