### ISSUE TITLE
Publishing device events from gateway running android application

### ISSUE THREAD

**Issue by vaquierm** [eclipse-paho/paho.mqtt.java#380]
Hi, I am currently working on an android application.
I have a question regarding what is and isn't supported by this library.
The android phone is connecting to the IoT platform as a terminal registered as a gateway. It then connects to one or multiple peripherals via BluetoothLE. I would like to publish **device** events from the android device **(GATEWAY)** , Is that something that is supported by the paho library?

**Comment by miketran78727** [comment]
Each IoT Platform should have specific instruction to help you develop your MQTT application (gateway, device, applications, ....)
