### ISSUE TITLE
Question : When/how will I get maven packages for Paho Oxygen release 1.1.0

### ISSUE THREAD

**Issue by prmathur-microsoft** [eclipse-paho/paho.mqtt.java#381]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.1.1 ( Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Develop Branch)

If this is a bug regarding the Android Service, please raise the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

I'm able to see Paho oxygen release at 
https://www.eclipse.org/downloads/download.php?file=/paho/releases/1.1.0/Java/plugins/org.eclipse.paho.client.mqttv3_1.1.0.jar 

However I don't see corresponding release on maven : 
http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.eclipse.paho%22

Last release on maven was on 23-Mar-2017 which does not reflect Oxygen Paho release. (July 28th)

org.eclipse.paho | org.eclipse.paho.client.mqttv3 | 1.1.1  all (3) | 23-Mar-2017

I need fixes from the oxygen release in a maven package. How/when can I get it ?

Please consider this as urgent request as this is blocking our release and as per issue #358 I was told that release would happen on July 28th and I still don't see it here.

**Comment by ingomaas** [comment]
I think you may mix up the Paho release version with the Paho Java client release version. The Eclipse Oxygen release includes Paho 1.3.0 (umbrella release of Paho components) which itself includes Paho Java Client 1.1.1 (released in March 2017). See https://projects.eclipse.org/projects/iot.paho/releases/1.3.0-oxygen/plan

**Comment by prmathur-microsoft** [comment]
The fix that I need was fixed after March 23rd. I'm interested in maven package with https://github.com/eclipse/paho.mqtt.java/issues/358 fix. Can you point me to that ?

**Comment by prmathur-microsoft** [comment]
Can anyone please help me get the maven package ? We are waiting on it for our release. Please consider this as urgent request.

**Comment by jpwsutton** [comment]
Hi @prmathur-microsoft, I've been holding back the next release of the Paho Java client in order to resolve some issues that I'd rather not let through until we're sure they are fixed. The next stable release should be some time this week. I'll comment back here once it's done.

**Comment by prmathur-microsoft** [comment]
@jpwsutton - Just to be clear this release will be for Maven package for Paho and not just eclipse package ?

**Comment by jpwsutton** [comment]
@prmathur-microsoft Do you mean on maven central? Yes it will be released on both.

**Comment by prmathur-microsoft** [comment]
@jpwsutton any update on the release to maven central ? We are blocked on this release from you. Can you please treat this as urgent issue and release to maven central ?

**Comment by lbrthld** [comment]
@jpwsutton the Readme.md states that the latest version is 1.2.0, however it is not available at https://repo.eclipse.org/content/repositories/paho-releases/org/eclipse/paho/org.eclipse.paho.client.mqttv3/1.2.0/. Is this an oversight?

**Comment by prmathur-microsoft** [comment]
@jpwsutton  - Can you please let know when will the maven package be released ? As I mentioned earlier, we are in urgent need of it. Appreciate it if you could release it soon.

**Comment by jpwsutton** [comment]
@prmathur-microsoft It's available here: https://search.maven.org/#artifactdetails%7Corg.eclipse.paho%7Corg.eclipse.paho.client.mqttv3%7C1.2.0%7Ceclipse-plugin

**Comment by cleverpig** [comment]
bug still... I rollback to 1.2.0 from 1.2.1
