### ISSUE TITLE
NPE in WebSocketReceiver.stop()

### ISSUE THREAD

**Issue by lbrthld** [eclipse-paho/paho.mqtt.java#382]
Please fill out the form below before submitting, thank you!

- [X] Bug exists Release Version 1.1.1 ( Master Branch)
- [X] Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Develop Branch)

In the IBM Watson Workspace app for Android we got an automated crash report through New Relic:
  location: WebSocketReceiver.java line 85 in org.eclipse.paho.client.mqttv3.internal.websocket.e.a
  exception: java.lang.NullPointerException
  message: Attempt to invoke virtual method 'void java.lang.Thread.join()' on a null object reference

2 MQTT related threads were running at the time:

thread 5793 - WssSocketReceiver:
org.eclipse.paho.client.mqttv3.internal.websocket.e.a()(WebSocketReceiver.java:85)
org.eclipse.paho.client.mqttv3.internal.websocket.e.run()(WebSocketReceiver.java:120)
java.lang.Thread.run()(Thread.java:762)

thread 5794 - MQTT Rec: Android-014489f80da07145c1:
java.lang.Object.wait()(Object.java:-2)
java.lang.Thread.parkFor$()(Thread.java:2128)
sun.misc.Unsafe.park()(Unsafe.java:325)
java.util.concurrent.locks.LockSupport.parkNanos()(LockSupport.java:201)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos()(AbstractQueuedSynchronizer.java:2077)
java.util.concurrent.ThreadPoolExecutor.awaitTermination()(ThreadPoolExecutor.java:1452)
org.eclipse.paho.client.mqttv3.internal.a.n()(ClientComms.java:121)
org.eclipse.paho.client.mqttv3.internal.a.a()(ClientComms.java:230)
org.eclipse.paho.client.mqttv3.h.a()(MqttAsyncClient.java:1323)
com.ibm.watson.workspace.api.a.a.d.a()(OurMqttAsyncClient.java:31)
com.ibm.watson.workspace.api.a.a.a.a()(MqttClient.java:280)
com.ibm.watson.workspace.api.a.a.a.d()(MqttClient.java:269)
com.ibm.watson.workspace.api.a.a.a.a()(MqttClient.java:160)
org.eclipse.paho.client.mqttv3.internal.c.a()(CommsCallback.java:287)
org.eclipse.paho.client.mqttv3.internal.a.a()(ClientComms.java:423)
org.eclipse.paho.client.mqttv3.internal.d.run()(CommsReceiver.java:176)
java.util.concurrent.ThreadPoolExecutor.runWorker()(ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run()(ThreadPoolExecutor.java:607)
java.lang.Thread.run()(Thread.java:762)

We have no further information under which circumstances the crash happened nor why the field "receiverThread" was null.

**Comment by jpwsutton** [comment]
Related to: https://github.com/eclipse/paho.mqtt.android/issues/232
A fix for this has been submitted in commit adc1160
This fix will be available in the SNAPSHOT built

**Comment by lbrthld** [comment]
@jpwsutton Thanks! When can we expect a 1.2.1 release build?

**Comment by nguyenlinhnttu** [comment]
Hi @jpwsutton  I used version 1.1.2-SNAPSHOT, but sometime NPE in WebSocketReceiver.stop(). It still 
appear in logcat and crash app.

**Comment by vineetdigit** [comment]
@jpwsutton same question as @lbrthld. Any update on the 1.2.1 release date?
