### ISSUE TITLE
Question: Is there any way to remove an in-flight publish message?

### ISSUE THREAD

**Issue by redboltz** [eclipse-paho/paho.mqtt.java#392]
- [NO] Bug exists Release Version 1.1.1 ( Master Branch)
- [NO] Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Develop Branch)

I'd like to remove an in-flight publish message.

I connect a broker that has permission control functionality using paho. Permission control means a client can publish only if the client have permission. The permission is defined a pair of ClientId (or Username) and topic.

Permission management is out of scope of MQTT spec, but there are some brokers that support it.

When I publish QoS1 message to a topic that is not permitted, then the broker doesn't return puback because the message is not processed. Some brokers immediately disconnect, but other brokers keep connection and report errors using some special topic like `$SYS/error_report` by publishing back.

I'm using a latter type broker. After the client received the error, I'd like to remove in-flight publish message. Because it still consuming packet id. In addition, when the client disconnect and connect again, the client will resend the message, and will get the same error (if CleanSession=false).

I'm looking for the way to remove in-flight message and to make packet id reusable by client side.

Any ideas?

**Comment by jpwsutton** [comment]
Hi,

I'm afraid that I don't know of any way to remove an in-flight message. The best I can think of at the moment would be to disconnect, then manually de-persist the message from your persistence layer.

**Comment by redboltz** [comment]
@jpwsutton , thank you for the comment. I will write a pull request to add the functionality. Could you review it if I will write it ?
