### ISSUE TITLE
MqttClient publish method take so much time after receive a message

### ISSUE THREAD

**Issue by yanxinyuan** [eclipse-paho/paho.mqtt.java#393]
Release Version 1.1.0

Here is the scenario:
![scenario](https://user-images.githubusercontent.com/13062548/28912114-81879496-7865-11e7-963e-11048a8ce234.png)

I start two JVMs, and each one has a mosquitto client, A client is responsible to publish a message and B client is responsible to receive a message. In the messageArrived method of B client, i just start a thread to publish a new message, but it take much more time(about 50ms) than the first message(about 5ms) from client A which publish to client B.
here is my code of B client:

	@Override
	 public void messageArrived(String topic, MqttMessage msg) throws Exception {
	  try {
              Runnable runnable = new Runnable() {

                @Override
                public void run() {
                    try {
                        MessagingSyncClient.getInstance().publish("/test/abcdef", Mocks.MOCK_1000_BYTE);
                    } catch (Exception e) {
                        // TODO Auto-generated catch block
                        e.printStackTrace();
                    }
                }
            };
            executorService.execute(runnable);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

i have gone through the source code, i found the after the arrive method returned, there still has some steps to finish this message, so during the interval publish a message will block and wait.

i wondering why doing this?

**Comment by jpwsutton** [comment]
Which QoS level are you using for sending these messages? The callbacks will block so it's recommended to return from the callbacks ASAP. It could be possible that the extra threading that you've added is a contributing factor for the delay. It might be worth timing some of the individual steps to see which part is actually causing the extra delay.

**Comment by yanxinyuan** [comment]
sorry for late response, we use qos=2. The delay is because the thread will have a lock conflict with the callback method. so i have to use two client to solve this problem. As it means, one client for send and one client for receive.

**Comment by yanxinyuan** [comment]
Actually i don't know if this is an issue.
