### ISSUE TITLE
Release 1.2.0 missing from repo?

### ISSUE THREAD

**Issue by trehn** [eclipse-paho/paho.mqtt.java#397]
Here on GitHub, a 1.2.0 release has been tagged: 

https://github.com/eclipse/paho.mqtt.java/releases/tag/v1.2.0

However, it is not available as a JAR in the repo:

https://repo.eclipse.org/content/repositories/paho-releases/org/eclipse/paho/org.eclipse.paho.client.mqttv3/

Is that just an oversight or is there something wrong with the release?

Thanks!

**Comment by jpwsutton** [comment]
Hi,

Sorry for the delay, the JAR is now available in the Eclipse repository and on Maven Central: https://search.maven.org/#artifactdetails%7Corg.eclipse.paho%7Corg.eclipse.paho.client.mqttv3%7C1.2.0%7Ceclipse-plugin

**Comment by trehn** [comment]
Great, thank you!
