### ISSUE TITLE
Threads dont exit upon disconnection using 1.2.0 paho client

### ISSUE THREAD

**Issue by prmathur-microsoft** [eclipse-paho/paho.mqtt.java#402]
Please fill out the form below before submitting, thank you!

- [x ] Bug exists Release Version 1.2.0 ( Master Branch)
- [ ] Bug exists in Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)

If this is a bug regarding the Android Service, please raise the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

After updating to latest paho client i.e 1.2.0 we notice that threads don't exit upon disconnect. Eg we still
1. Mqtt Con
2. Mqtt Rec
3. Mqtt call

Still remain active even after calling disconnect.
 
![image](https://user-images.githubusercontent.com/20328314/30079385-e524a7ee-9234-11e7-8754-bd1b9dfabe9a.png)

**Comment by jpwsutton** [comment]
@prmathur-microsoft Could you enable logging (https://wiki.eclipse.org/Paho/Log_and_Debug_in_the_Java_client) and provide the log from the point at which disconnect is called please?

**Comment by dougiman** [comment]
I have attached the log, thank you.

[paho0.log](https://github.com/eclipse/paho.mqtt.java/files/1373856/paho0.log)

**Comment by prmathur-microsoft** [comment]
@jpwsutton - Can you please look at logs above and provide us a fix ?

**Comment by prmathur-microsoft** [comment]
@jpwsutton  - Can you please look at logs that we provided ?

**Comment by aromanelli** [comment]
I too am seeing this problem, and would appreciate @dougiman (or others) review of this issue.  Thank you in advance for your time and efforts, they are appreciated.

**Comment by aromanelli** [comment]
I too am seeing this problem, and would appreciate @jpwsutton (or others) review of this issue. Thank you in advance for your time and efforts, they are appreciated.

**Comment by jpwsutton** [comment]
Thanks for the log, this actually looks a bit similar to issue #330 where the client enters a deadlock state during a disconnection from an unstable connection. In this case it looks like the client had automatically reconnected before disconnecting. This is quite helpful to know as it should help us track down the core issue for this. Once we've found a resolution for #330, I'll commend back here so you can see if it's fixed your problem.

How easy is this for you to recreate reliably? Getting as much info about this problem would be very useful.

**Comment by aromanelli** [comment]
@jpwsutton Wasn't sure if you were addressing me or @prmathur-microsoft with your recreation question, but in my case, I can recreate it 100% of the time with a simple/small three class app/IJ project. In my case I am running the server (embedded) and the client on the same PC, so I don't believe I have any 'unstable connection' issues.  Having said that, I'm newish to MQTT, so I may be doing a self-inflicted wound, but if you think my small app would help, I would be glad to zip it up and email it to you.  Please advise.

Additional: Yesterday, when I first posted, I was getting the same quantity of active threads, MQTTs and a couple of pools, as @prmathur-microsoft , but today, I am only getting a single "pool-2-thread-1" active thread, which is strange as I did not change any of my code from yesterday to today.  Ran a stack trace via YourKit Java Profiler, and got the following on the non-terminating active "pool-2-thread-1" thread ...

> 1) java.util.concurrent.ThreadPoolExecutor.execute(Runnable) ThreadPoolExecutor.java:1367
> 2) io.moquette.spi.impl.BrokerInterceptor.notifyClientConnected(MqttConnectMessage) BrokerInterceptor.java:97
> 3) io.moquette.spi.impl.ProtocolProcessor.processConnect(Channel, MqttConnectMessage) ProtocolProcessor.java:283
> 4) io.moquette.server.netty.NettyMQTTHandler.channelRead(ChannelHandlerContext, Object) NettyMQTTHandler.java:46
> 5) io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Object) AbstractChannelHandlerContext.java:340
> 6) io.moquette.server.netty.metrics.MQTTMessageLogger.channelRead(ChannelHandlerContext, Object) MQTTMessageLogger.java:44
> 7) io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Object) AbstractChannelHandlerContext.java:340
> 8) io.moquette.server.netty.metrics.MessageMetricsHandler.channelRead(ChannelHandlerContext, Object) MessageMetricsHandler.java:48
> 9) io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Object) AbstractChannelHandlerContext.java:340
> 10) io.moquette.server.netty.metrics.BytesMetricsHandler.channelRead(ChannelHandlerContext, Object) BytesMetricsHandler.java:49
> 11) java.lang.Thread.run() Thread.java:748


And the current runtime state of the "pool-2-thread-1" thread ...

> Stacks at 2017-11-08 03:35:08 PM. Uptime is 26m 0s 900ms.
> _pool-2-thread-1_ **State: WAITING** CPU usage on sample: 0ms
> sun.misc.Unsafe.park(boolean, long) Unsafe.java (native)
> java.util.concurrent.locks.LockSupport.park(Object) LockSupport.java:175
> java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await() AbstractQueuedSynchronizer.java:2039
> java.util.concurrent.LinkedBlockingQueue.take() LinkedBlockingQueue.java:442
> java.util.concurrent.ThreadPoolExecutor.getTask() ThreadPoolExecutor.java:1074
> java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) ThreadPoolExecutor.java:1134
> java.util.concurrent.ThreadPoolExecutor$Worker.run() ThreadPoolExecutor.java:624
> java.lang.Thread.run() Thread.java:748

I can also supply a YourKit Java Profiler snapshot file (3Kb), that generated the above information, if you wish.

**Comment by prmathur-microsoft** [comment]
Is there any update on this issue ?

**Comment by prmathur-microsoft** [comment]
@jpwsutton  - Any update on this issue ?

**Comment by frank-montyne** [comment]
I'm having the same problem. Any update? This is a real critical stability issue. Thanks

**Comment by timtay-microsoft** [comment]
A workaround that I just found is to close your mqttAsyncClient after disconnecting it.

```
IMqttToken disconnectToken = mqttAsyncClient.disconnect();
disconnectToken.waitForCompletion();

//add this line
mqttAsyncClient.close();
```

Inside this close call, the Executor Service that is hosting those errant threads is shutdown, so those threads die. It also makes your mqttAsyncClient unusable according to its documentation, so make sure not to reuse an MqttAsyncClient after closing it.

It still seems to me like a bug that the threads survive the disconnect, but if you are in a rush, this workaround worked great for me.

@jpwsutton do you have any comments on using close in this way?

**Comment by aromanelli** [comment]
@timtay-microsoft Thanks for the suggested workaround.  I had already had a close(true) (force the close) call in my code that reproduces the bug.  I tried just calling close() instead, but I still see the same issue, the app never closes, and a thread is left out there running.  So the workaround didn't work in my case.  Do appreciate the effort/knowledge sharing, thank you for that.

**Comment by aromanelli** [comment]
I figured out my issue, where a mqtt thread stays after main() is done.  

If I call Server.startServer, passing in a List for the second argument with a valid AbstractInterceptHandler concrete subclass in the List, the thread will not die when main() is done.  If I call Server.startServer passing in an empty List for the second argument, the app completes normally after main() is done.

Calling Server.remoteInterceptHandler(InterceptHandler) before calling Server.stopServer() does not change the outcome of the thread not dying when main() is done.

So there's something internal about adding an InterceptHandler that keeps the thread running.

[paho4.log](https://github.com/eclipse/paho.mqtt.java/files/1760709/paho4.log)

EDIT: @jpwsutton Looks like BrokerInterceptor.stop() is never called, so executor.shutdown() is never called, so the ExecutorService keeps the thread alive.  I looked for "Shutting down interceptor thread pool..." in my log file (see attached), but its not there.  Also confirmed by setting a breakpoint in IntelliJ, it never got called.

**Comment by GamiiisKth** [comment]
I had the same issue and now threads exits.
```     
mqttClient.disconnectForcibly();

 mqttClient.close(true);
```
add this lines

**Comment by aromanelli** [comment]
@GamiiisKth , for what its worth, I had both disconnectForcibly() and close(true) implemented, and the problem continues for me.

I believe the issue is as I've commented to @jpwsutton on Feb26th.

**Comment by GamiiisKth** [comment]
@aromanelli can you run your mqttClient on the main thread and try disconnect with disconnectForcibly(), close(true) just for test purpose.

**Comment by fguiet** [comment]
Hi,

Moved my Java program to Docker...ok no problem...But I soon realized that I got a memory leak...my program was consuming more and more memory and my java program started to throw : java.lang.OutOfMemoryError: unable to create new native thread

Ok, I used this command to dump Java stack : jstack -l <pid> > /tmp/dump.txt
Then, I uploaded the dump from time to time on http://fastthread.io/index.jsp (nice!)
Saw a lot of MQTT + client id Rec, Con, Call threads still alive and increasing as time passed...
Sucks! 
This is what I did to save my ass:

//Issue :
//https://github.com/eclipse/paho.mqtt.java/issues/402
//client.disconnect();
client.disconnectForcibly();
client.close(true);
client = null;

This bug is really annoying because when maximum thread creation limit is reached Java will throw this exception : java.lang.OutOfMemoryError: unable to create new native thread

**Comment by jpwsutton** [comment]
Hi everyone, thanks for your patience on this, I've just had a look and am currently trying to find a good solution to this. I'll update again tomorrow once I've got some more news.

**Comment by jpwsutton** [comment]
So I've been looking into this a bit more, my first port of call is to modify the async Disconnect and disconnectForcibly to shutdown the executor service. Currently the executor service is only shut down when the client is closed, which is a change from 1.1.0. 

However doing this introduces the issue that once you have manually disconnected a client, you cannot open a new connection as the executor service is shut down.

Because of this, I'm hesitant to commit my changes as it breaks tests and could cause issues for a lot of people. I think the best workaround right now is to close the client once you have disconnected, but I'm open to feedback as to how we could fix this going forwards.

**Comment by gprivalov** [comment]
I found a workaround by supplying my own executor instance when creating MqttClient.  I shutdown the executor explicitly after closing the client.

**Comment by tvasudev007** [comment]
> I found a workaround by supplying my own executor instance when creating MqttClient. I shutdown the executor explicitly after closing the client.

I tired new MqttClient(brokerURL, clientId, new MemoryPersistence(), Executors.newScheduledThreadPool(10); 

		try {
			this.mqttClient.disconnectForcibly();
			this.mqttClient.close(true);

			logger.warn("MQTT disconnected forcibly");
		} catch (MqttException e1) {
			logger.error("MQTT disconnected forcibly failed...");
		} finally {
			this.mqttClientExeService.shutdown();
			this.mqttClient = null;
		}
But still the thread doesnt close.

**Comment by tvasudev007** [comment]
Created a new connection management service for MQTT client connection failures. It takes around 20 threads at all times. 

<CODE>
import java.util.List;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

import org.apache.commons.lang3.StringUtils;
import org.eclipse.paho.client.mqttv3.MqttCallback;
import org.eclipse.paho.client.mqttv3.MqttClient;
import org.eclipse.paho.client.mqttv3.MqttConnectOptions;
import org.eclipse.paho.client.mqttv3.MqttException;
import org.eclipse.paho.client.mqttv3.persist.MemoryPersistence;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import edgeconnector.dto.MQTTTopicSubDTO;
import edgeconnector.execution.manager.ThreadPoolManager;

/**
 * MQTT Reconnection management service
 * 
 * @author vasudev007
 *
 */
public class MQTTConnectionManagementService implements Runnable {

	private final Logger logger = LoggerFactory.getLogger(MQTTConnectionManagementService.class);

	ThreadPoolManager mqttThreadPool = new ThreadPoolManager();

	private MqttClient mqttClient;

	private String brokerURL;
	private String username;
	private String password;
	private Integer RECON_ATTEMPTS = 5;
	private Integer RECON_INITIAL_DELAY = 60;
	private Integer RECON_INTERVAL = 30;
	private TimeUnit RECON_TIME_UNIT = TimeUnit.SECONDS;
	private Boolean RECON_ENABLE = true;
	private MqttCallback MQTT_SUB_CBK;
	private List<MQTTTopicSubDTO> subscriptionList;
	Integer retryCounter = 0;
	private ScheduledExecutorService mqttClientExeService = Executors.newScheduledThreadPool(5);
	private ScheduledExecutorService reconcheduledExecutorService;

	/**
	 * MQTT Connection manager service to manage connection, subscription &
	 * reconnection safely. Default values: RECON_COUNTER=10L,
	 * RECON_INITIAL_DELAY=60, RECON_INTERVAL=30, RECON_TIME_UNIT= SECONDS,
	 * RECON_ENABLE= true
	 * 
	 * @param brokerURL
	 * @param username
	 * @param password
	 * @param RECON_ENABLE
	 * @param RECON_COUNTER
	 * @param RECON_INITIAL_DELAY
	 * @param RECON_INTERVAL
	 * @param RECON_TIME_UNIT
	 * @param MQTT_SUB_CBK
	 */
	public MQTTConnectionManagementService(String brokerURL, String username, String password, Boolean RECON_ENABLE,
			Integer RECON_ATTEMPTS, Integer RECON_INITIAL_DELAY, Integer RECON_INTERVAL, TimeUnit RECON_TIME_UNIT,
			MqttCallback MQTT_SUB_CBK, List<MQTTTopicSubDTO> subscriptionList) {

		this.brokerURL = brokerURL;
		this.username = username;
		this.password = password;
		this.MQTT_SUB_CBK = MQTT_SUB_CBK;
		this.subscriptionList = subscriptionList;

		if (RECON_ATTEMPTS != null)
			this.RECON_ATTEMPTS = RECON_ATTEMPTS;

		if (RECON_INITIAL_DELAY != null)
			this.RECON_INITIAL_DELAY = RECON_INITIAL_DELAY;

		if (RECON_INTERVAL != null)
			this.RECON_INTERVAL = RECON_INTERVAL;

		if (RECON_TIME_UNIT != null)
			this.RECON_TIME_UNIT = RECON_TIME_UNIT;

		if (this.RECON_ENABLE) {
			reconnect();
		}

	}

	public void connect() {

		try {
			String clientId = MqttClient.generateClientId();

			this.mqttClient = new MqttClient(brokerURL, clientId, new MemoryPersistence(), this.mqttClientExeService);

			MqttConnectOptions options = new MqttConnectOptions();
			if (StringUtils.isNotEmpty(username) && StringUtils.isNotEmpty(password)) {
				options.setUserName(username);
				options.setPassword(password.toCharArray());
			}
			options.setCleanSession(true);
			// options.setAutomaticReconnect(true);
			// options.setConnectionTimeout(10);
			options.setMqttVersion(MqttConnectOptions.MQTT_VERSION_3_1);
			if (this.MQTT_SUB_CBK != null) {
				this.mqttClient.setCallback(this.MQTT_SUB_CBK);
			}

			this.mqttClient.connect(options);

			logger.info("Connection status {} to broker : {} ", this.mqttClient.isConnected(), this.brokerURL);
			if (subscriptionList != null && subscriptionList.size() > 0) {
				subscribe();
				logger.debug("Subscribe to {} topics", this.subscriptionList.size());
			}
			this.retryCounter = 0;
		} catch (MqttException e) {
			logger.error("MQTT EXE: {} ", e.getMessage());
			logger.debug("connection failed with broker : {} ...no. of remaining attempts = :{} ", this.brokerURL,
					(this.RECON_ATTEMPTS - this.retryCounter));
			closeConnection();
		}
	}

	private void subscribe() throws MqttException {
		for (MQTTTopicSubDTO sub : this.subscriptionList) {
			this.mqttClient.subscribe(sub.getTopic(), sub.getQos());
			if (logger.isTraceEnabled()) {
				logger.trace("Subscribed to topic : {} with QOS: {}", sub.getTopic(), sub.getQos());
			}
		}
	}

	public void publishAndClose(String topic, String payload) {

		try {
			this.mqttClient.publish(topic, payload.getBytes(), 2, true);
			logger.debug("Published to broker :{} with topic: {} & payload :{} ", this.brokerURL, topic, payload);
		} catch (MqttException e) {
			logger.error("Error publishing to broker :{} with topic: {} & payload :{} ", this.brokerURL, topic,
					payload);
		} finally {
			closeConnection();
		}
	}

	public void publish(String topic, String payload) {

		try {
			this.mqttClient.publish(topic, payload.getBytes(), 2, true);
			logger.info("Published to broker :{} with topic: {} & payload :{} ", this.brokerURL, topic, payload);
		} catch (MqttException e) {
			logger.error("Error publishing to broker :{} with topic: {} & payload :{} ", this.brokerURL, topic,
					payload);
		}
	}

	public void closeConnection() {

		try {
			this.mqttClient.disconnect();
			this.mqttClient.close();
			logger.trace("Disconnected from broker: {}", this.brokerURL);
		} catch (MqttException e1) {
			logger.error("Disconnected failed with broker: {}", this.brokerURL);
			try {
				this.mqttClient.disconnectForcibly();
				this.mqttClient.close(true);
			} catch (MqttException e) {
				logger.error("Force disconnection failed...");
			}
		} finally {
			this.mqttClientExeService.shutdown();
		}

	}

	private void reconnect() {

		if (this.reconcheduledExecutorService == null || this.reconcheduledExecutorService.isShutdown()) {
			logger.info("starting a new reconnection job");
			ScheduledExecutorService ses = Executors.newSingleThreadScheduledExecutor();
			this.reconcheduledExecutorService = ses;
			ses.scheduleAtFixedRate(this, RECON_INITIAL_DELAY, RECON_INTERVAL, RECON_TIME_UNIT);
		}
	}

	@Override
	public void run() {

		if (logger.isTraceEnabled())
			logger.trace("In reconnection job & mqttClient connection with broker :{} status :{}", this.brokerURL,
					this.mqttClient.isConnected());

		if (this.retryCounter > this.RECON_ATTEMPTS) {
			logger.warn("shutting down MQTT connection retry job..ran out of attempts ");
			this.reconcheduledExecutorService.shutdown();
			this.mqttClientExeService.shutdown();
		}

		if (this.mqttClient == null || !this.mqttClient.isConnected()) {
			this.retryCounter++;
			if (logger.isTraceEnabled())
				logger.trace("this.retryCounter : {}  and this.RECON_ATTEMPTs: {}", this.retryCounter,
						this.RECON_ATTEMPTS);
			closeConnection();
			this.mqttClientExeService.shutdown();
			this.mqttClientExeService = Executors.newScheduledThreadPool(5);
			connect();
		}
	}

}

</CODE>

**Comment by tvasudev007** [comment]
> Created a new connection management service for MQTT client connection failures. It takes around 20 threads at all times.
> 
> `` import java.util.List; import java.util.concurrent.Executors; import java.util.concurrent.ScheduledExecutorService; import java.util.concurrent.TimeUnit; import org.apache.commons.lang3.StringUtils; import org.eclipse.paho.client.mqttv3.MqttCallback; import org.eclipse.paho.client.mqttv3.MqttClient; import org.eclipse.paho.client.mqttv3.MqttConnectOptions; import org.eclipse.paho.client.mqttv3.MqttException; import org.eclipse.paho.client.mqttv3.persist.MemoryPersistence; import org.slf4j.Logger; import org.slf4j.LoggerFactory; import edgeconnector.dto.MQTTTopicSubDTO; import edgeconnector.execution.manager.ThreadPoolManager; /** * MQTT Reconnection management service * @author vasudev007 */ public class MQTTConnectionManagementService implements Runnable { ``` private final Logger logger = LoggerFactory.getLogger(MQTTConnectionManagementService.class); ThreadPoolManager mqttThreadPool = new ThreadPoolManager(); private MqttClient mqttClient; private String brokerURL; private String username; private String password; private Integer RECON_ATTEMPTS = 5; private Integer RECON_INITIAL_DELAY = 60; private Integer RECON_INTERVAL = 30; private TimeUnit RECON_TIME_UNIT = TimeUnit.SECONDS; private Boolean RECON_ENABLE = true; private MqttCallback MQTT_SUB_CBK; private List<MQTTTopicSubDTO> subscriptionList; Integer retryCounter = 0; private ScheduledExecutorService mqttClientExeService = Executors.newScheduledThreadPool(5); private ScheduledExecutorService reconcheduledExecutorService; /** * MQTT Connection manager service to manage connection, subscription & * reconnection safely. Default values: RECON_COUNTER=10L, * RECON_INITIAL_DELAY=60, RECON_INTERVAL=30, RECON_TIME_UNIT= SECONDS, * RECON_ENABLE= true * * @param brokerURL * @param username * @param password * @param RECON_ENABLE * @param RECON_COUNTER * @param RECON_INITIAL_DELAY * @param RECON_INTERVAL * @param RECON_TIME_UNIT * @param MQTT_SUB_CBK */ public MQTTConnectionManagementService(String brokerURL, String username, String password, Boolean RECON_ENABLE, Integer RECON_ATTEMPTS, Integer RECON_INITIAL_DELAY, Integer RECON_INTERVAL, TimeUnit RECON_TIME_UNIT, MqttCallback MQTT_SUB_CBK, List<MQTTTopicSubDTO> subscriptionList) { this.brokerURL = brokerURL; this.username = username; this.password = password; this.MQTT_SUB_CBK = MQTT_SUB_CBK; this.subscriptionList = subscriptionList; if (RECON_ATTEMPTS != null) this.RECON_ATTEMPTS = RECON_ATTEMPTS; if (RECON_INITIAL_DELAY != null) this.RECON_INITIAL_DELAY = RECON_INITIAL_DELAY; if (RECON_INTERVAL != null) this.RECON_INTERVAL = RECON_INTERVAL; if (RECON_TIME_UNIT != null) this.RECON_TIME_UNIT = RECON_TIME_UNIT; if (this.RECON_ENABLE) { reconnect(); } } public void connect() { try { String clientId = MqttClient.generateClientId(); this.mqttClient = new MqttClient(brokerURL, clientId, new MemoryPersistence(), this.mqttClientExeService); MqttConnectOptions options = new MqttConnectOptions(); if (StringUtils.isNotEmpty(username) && StringUtils.isNotEmpty(password)) { options.setUserName(username); options.setPassword(password.toCharArray()); } options.setCleanSession(true); // options.setAutomaticReconnect(true); // options.setConnectionTimeout(10); options.setMqttVersion(MqttConnectOptions.MQTT_VERSION_3_1); if (this.MQTT_SUB_CBK != null) { this.mqttClient.setCallback(this.MQTT_SUB_CBK); } this.mqttClient.connect(options); logger.info("Connection status {} to broker : {} ", this.mqttClient.isConnected(), this.brokerURL); if (subscriptionList != null && subscriptionList.size() > 0) { subscribe(); logger.debug("Subscribe to {} topics", this.subscriptionList.size()); } this.retryCounter = 0; } catch (MqttException e) { logger.error("MQTT EXE: {} ", e.getMessage()); logger.debug("connection failed with broker : {} ...no. of remaining attempts = :{} ", this.brokerURL, (this.RECON_ATTEMPTS - this.retryCounter)); closeConnection(); } } private void subscribe() throws MqttException { for (MQTTTopicSubDTO sub : this.subscriptionList) { this.mqttClient.subscribe(sub.getTopic(), sub.getQos()); if (logger.isTraceEnabled()) { logger.trace("Subscribed to topic : {} with QOS: {}", sub.getTopic(), sub.getQos()); } } } public void publishAndClose(String topic, String payload) { try { this.mqttClient.publish(topic, payload.getBytes(), 2, true); logger.debug("Published to broker :{} with topic: {} & payload :{} ", this.brokerURL, topic, payload); } catch (MqttException e) { logger.error("Error publishing to broker :{} with topic: {} & payload :{} ", this.brokerURL, topic, payload); } finally { closeConnection(); } } public void publish(String topic, String payload) { try { this.mqttClient.publish(topic, payload.getBytes(), 2, true); logger.info("Published to broker :{} with topic: {} & payload :{} ", this.brokerURL, topic, payload); } catch (MqttException e) { logger.error("Error publishing to broker :{} with topic: {} & payload :{} ", this.brokerURL, topic, payload); } } public void closeConnection() { try { this.mqttClient.disconnect(); this.mqttClient.close(); logger.trace("Disconnected from broker: {}", this.brokerURL); } catch (MqttException e1) { logger.error("Disconnected failed with broker: {}", this.brokerURL); try { this.mqttClient.disconnectForcibly(); this.mqttClient.close(true); } catch (MqttException e) { logger.error("Force disconnection failed..."); } } finally { this.mqttClientExeService.shutdown(); } } private void reconnect() { if (this.reconcheduledExecutorService == null || this.reconcheduledExecutorService.isShutdown()) { logger.info("starting a new reconnection job"); ScheduledExecutorService ses = Executors.newSingleThreadScheduledExecutor(); this.reconcheduledExecutorService = ses; ses.scheduleAtFixedRate(this, RECON_INITIAL_DELAY, RECON_INTERVAL, RECON_TIME_UNIT); } } @Override public void run() { if (logger.isTraceEnabled()) logger.trace("In reconnection job & mqttClient connection with broker :{} status :{}", this.brokerURL, this.mqttClient.isConnected()); if (this.retryCounter > this.RECON_ATTEMPTS) { logger.warn("shutting down MQTT connection retry job..ran out of attempts "); this.reconcheduledExecutorService.shutdown(); this.mqttClientExeService.shutdown(); } if (this.mqttClient == null || !this.mqttClient.isConnected()) { this.retryCounter++; if (logger.isTraceEnabled()) logger.trace("this.retryCounter : {} and this.RECON_ATTEMPTs: {}", this.retryCounter, this.RECON_ATTEMPTS); closeConnection(); this.mqttClientExeService.shutdown(); this.mqttClientExeService = Executors.newScheduledThreadPool(5); connect(); } } ``` } ``

You can use it by initiating MQTTConnectionManagementService 

<CODE>
MQTTConnectionManagementService mqttClient = new MQTTConnectionManagementService(brokerURL, username,
					password, isreconnectEnabled, RECON_ATTMPT, RECON_INIT_DELAY, RECON_INT, MQTT_RECON_UNIT,
					new IC4CCloudMQTTSubscriber(), cloudSubscription);

mqttClient.connect();
</CODE>

**Comment by icraggs** [comment]
I'm looking at this now.  It seems there are two separate issues, probably.

1) PR #280 introduced the use of the executor service.  This is fine for shared environments when an external executor service is provided.  When no external executor service is provided, if we use an executor service internally it changes the behaviour because now the threads in the thread pool are still running and only closing the client will stop those threads.  

**I propose to only use an executor service if it's supplied, otherwise to revert to the previous implementation of 'normal' threads, which terminate when the run() method does.**  I'm doubtful about the use of an external executor service in any case, as these client threads are not processing single units of work, cannot tolerate significant delays in starting up and in some cases need to run for as long as the MQTT client is connected.  If anyone can tell me under what circumstances it definitely helps, then I'd like to hear about it.

2) If the threads are deadlocked then shutting down the executor service doesn't terminate those threads anyway.  That's a different issue which I expect is covered in other issues (I'll check).

If we use an external executor service then it seems that we shouldn't shut it down on close() anyway.  Any comments on this observation also sought.

Thanks!

**Comment by icraggs** [comment]
I've made the change so that if no executor service is supplied, the library uses normal threads, as it used to, which means that they end when the task ends.  Tests also added.

**Comment by gilzhaiek** [comment]
hi @icraggs 
We just rolled it into production.  We had lots of issues with this, so the fix is welcomed.
We are using AWS AppSync and found that this combination stops the dead threads and also solves a new ANR in the MqttService:
```
implementation files('libs/org.eclipse.paho.client.mqttv3-1.2.1-SNAPSHOT.jar')
implementation 'com.amazonaws:aws-android-sdk-appsync:2.6.28'
implementation('com.amazonaws:aws-android-sdk-s3:2.7.+') { transitive = true }
```
Thank you!

**Comment by icraggs** [comment]
@gilzhaiek Just seen your message - I'm glad to help!

**Comment by valera7979** [comment]
Yes, you did it!!!! Congrats!!! All works fine since 1.3.4 version

'com.amazonaws:aws-iot-device-sdk-java:1.3.4'

It is strange that paho version in sdk library 1.1.0 but it works.
