### ISSUE TITLE
Incompatible change: Test fail just by updating paho 1.1.1 to 1.2.0, 1.2.1-SNAPSHOT 

### ISSUE THREAD

**Issue by ohze** [eclipse-paho/paho.mqtt.java#405]
- [x] Bug exists Release Version 1.2.0 ( Master Branch)
- [x] Bug exists in Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)

See https://travis-ci.org/giabao/paho-akka/builds/274119608
The success builds do not set PAHO_CLIENT_VERSION environment variable, so it will be the [default value 1.1.1](https://github.com/giabao/paho-akka/blob/7c1ce755a79ee12222411f489e70f401a3c0a36f/build.sbt#L20)

**Comment by jpwsutton** [comment]
Hi, I don't think we've ever set that variable anywhere in our library, or in our build. Looks like you might have the wrong repository!
