### ISSUE TITLE
MQTT topic filtering does not conform to spec: filter 'foo/#' won't catch message published to 'foo'

### ISSUE THREAD

**Issue by vickingur** [eclipse-paho/paho.mqtt.java#418]
From http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718107:
 

> For example, if a Client subscribes to “sport/tennis/player1/#”, it would receive messages published using these topic names:
> “sport/tennis/player1”
> “sport/tennis/player1/ranking”
> “sport/tennis/player1/score/wimbledon”

Also, https://www.eclipse.org/paho/files/javadoc/org/eclipse/paho/client/mqttv3/MqttClient.html javadoc claims that Paho client confirms MQTT spec:

> Multi-level wildcard
> The number sign (#) is a wildcard character that matches any number of levels within a topic. For example, if you subscribe to finance/stock/ibm/#, you receive messages on these topics:
>    finance/stock/ibm
>    finance/stock/ibm/closingprice
>    finance/stock/ibm/currentprice
> The multi-level wildcard can represent zero or more levels. Therefore, finance/# can also match the singular finance, where # represents zero levels. The topic level separator is meaningless in this context, because there are no levels to separate.

But it doesn't work this way, [org.eclipse.paho.client.mqttv3.MqttTopic.isMatched(String topicFilter, String topicName) ](https://github.com/eclipse/paho.mqtt.java/blob/master/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/MqttTopic.java#L248) doesn't account for situation when topic filter is longer than topic name.

Checked mosquitto client and it works correctly. It actually has an explicit check for this situation: http://git.eclipse.org/c/mosquitto/org.eclipse.mosquitto.git/tree/lib/util_mosq.c#n246

- [x] Bug exists Release Version 1.2.0 ( Master Branch)
- [x] Bug exists in Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)

**Comment by vickingur** [comment]
@jpwsutton, any comments on this?

**Comment by jpwsutton** [comment]
Hi,
I just tried this using the latest version and it seems to work as expected:

```
Connecting to broker: tcp://localhost:1883
Subscribing to topic [foo/#]
Connected
Publishing message to topic [foo] : [This is a message from foo to foo/#]
Delivery complete
Message arrived: This is a message from foo to foo/#
Disconnected
```

Do you have an example of this not working?

**Comment by vickingur** [comment]
Hi,

I tried sample apps in the project and I see subscriber is receiving and printing message from foo topic.
But tracing down the code I see it's receiving it through 'default' callback:
CommsCallback.java
```
protected boolean deliverMessage(String topicName, int messageId, MqttMessage aMessage) throws Exception
	{		
		boolean delivered = false;
		
		Enumeration keys = callbacks.keys();
		while (keys.hasMoreElements()) {
			String topicFilter = (String)keys.nextElement();
			if (MqttTopic.isMatched(topicFilter, topicName)) {
				aMessage.setId(messageId);
				((IMqttMessageListener)(callbacks.get(topicFilter))).messageArrived(topicName, aMessage);
				delivered = true;
			}
		}
		
		/* if the message hasn't been delivered to a per subscription handler, give it to the default handler */
		if (mqttCallback != null && !delivered) {
			aMessage.setId(messageId);
			mqttCallback.messageArrived(topicName, aMessage);
			delivered = true;
		}
		
		return delivered;
	}
```
No listeners would match the topic filter and the message will be delivered to mqttCallback.My app was not setting that default callback, so I was not getting the message at all.
The problem with this is when this callback receives the message - it doesn't know where to route it (which listeners).

**Comment by vickingur** [comment]
@jpwsutton, so this is not like the client is not receiving the message at all - broker will send it and default callback may handle it. But subscribed listener won't get the message, so I still believe this is an issue

**Comment by gsteen** [comment]
when do you release this fix? I need it too.

I tried your commit and it works. 
if someone publishes to sport/ the message arrives at the client but MqttTopic.matches returns false.

**Comment by swarwick** [comment]
This still doesnt fix another pattern like
`+/topic1/#`
I tried that and it still did not validate against
`/test/topic1/demo`

**Comment by swarwick** [comment]
It does however match if the topic filter is
`/+/topic1/#`
so the initial slash still seems to be an issue but I believe that not having the initial slash and just a plus is a valid topic filter.

**Comment by swarwick** [comment]
I believe this change should fix it
`if (topicName.charAt(topicPos) == '/' && !(topicFilter.charAt(filterPos) == '/' || topicFilter.charAt(filterPos) == '+'))`

**Comment by swarwick** [comment]
If missing a '/' at the start is invalid then the validate topic method should be updated to check for that.

**Comment by swarwick** [comment]
Ignore all that, I believe I was not thinking correctly about the starting / and how the + matches.

**Comment by dwimberger** [comment]
Why is there a System.err output within the code block for this fix?
https://github.com/eclipse/paho.mqtt.java/blob/master/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/MqttTopic.java#L305
