### ISSUE TITLE
Message Id never get incremented for publish in QoS 0

### ISSUE THREAD

**Issue by fengsongAWS** [eclipse-paho/paho.mqtt.java#421]
Please fill out the form below before submitting, thank you!

- [X] Bug exists Release Version 1.2.0 ( Master Branch)
When publish message in QoS 0, the message Id never get incremented because of this line.
https://github.com/eclipse/paho.mqtt.java/blob/75594f0b226b14911f397b69059c18a50eaabb54/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/internal/ClientState.java#L487
Is there any reason we want to differentiate between QoS 1 and QoS 0? 
- [ ] Bug exists in Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)

If this is a bug regarding the Android Service, please raise the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

**Comment by jpwsutton** [comment]
The reason we don't assign them is because they don't really have any use as QoS 0 messages are fire and forget and we didn't want to use up message IDs on messages that didn't need them. Is there a specific reason for requiring a message ID for QoS 0 messages?

**Comment by fengsongAWS** [comment]
Using the same message id for QoS0 async publish will fail the request due to overwritten internal token and callbacks.

**Comment by fengsongAWS** [comment]
If we keep publishing in async publish QoS 0, because it never increment the message ID, the token of first message will get overridden and therefore the callback will not get invoked. This does not happen if user keep time interval between each publish. Is this an expected behavior?

**Comment by jpwsutton** [comment]
@fengsongAWS Ok, thanks, that does sound like a reasonable use case. I wouldn't want to change the behaviour permanently though, rather I'd add a switch in the MqttConnectOptions that could enable QoS 0 Message IDs.

I'm currently quite busy working on MQTTv5 right now, so won't get round to adding this for a little while. You're more than welcome to submit a PR if you'd like though?

**Comment by matsujun** [comment]
If this (overwritten internal token and callbacks) happen, we cannot get token [here](https://github.com/eclipse/paho.mqtt.java/blob/75594f0b226b14911f397b69059c18a50eaabb54/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/internal/CommsSender.java#L134)
so we cannot enter [this if brace](https://github.com/eclipse/paho.mqtt.java/blob/75594f0b226b14911f397b69059c18a50eaabb54/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/internal/CommsSender.java#L138) 
I think, it means [notifySent](https://github.com/eclipse/paho.mqtt.java/blob/75594f0b226b14911f397b69059c18a50eaabb54/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/internal/ClientState.java#L856) is not called, and [decrementInFlight](https://github.com/eclipse/paho.mqtt.java/blob/75594f0b226b14911f397b69059c18a50eaabb54/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/internal/ClientState.java#L890) is not executed.
And finally, it cause MqttException(MqttException.REASON_CODE_MAX_INFLIGHT) every time at [here](https://github.com/eclipse/paho.mqtt.java/blob/75594f0b226b14911f397b69059c18a50eaabb54/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/internal/ClientState.java#L509-L514)

Is this right ?

**Comment by efiko12** [comment]
I had the same problem.
Solved it by override `ClientComms.sendNoWait` method and set the message id with a unique value.
It's ugly but it does the job

Scala code:

```

  //Message id is an unsigned int16 so the max value is 65535
  private def nextMessageId() = Math.abs(messageIdGenerator.getAndIncrement % 65535)

  private def buildPahoClient = new MqttAsyncClient(url.toString, UUID.randomUUID().toString, new MemoryPersistence()) {

    val persistence = new MemoryPersistence()
    persistence.open(getClientId, getServerURI)

    this.comms = new ClientComms(this, persistence, new TimerPingSender, Executors.newScheduledThreadPool(10)) {

      override def sendNoWait(message: MqttWireMessage, token: MqttToken): Unit = {
        if (message.isInstanceOf[MqttPublish] || message.isInstanceOf[MqttSubscribe]) {
          message.setMessageId(nextMessageId())
        }
        super.sendNoWait(message, token)
      }
    }

    persistence.close()
  }

```

**Comment by hylkevds** [comment]
It's also a major issue for multi threaded applications, since two threads can call publish at the same time. One thread will hang because `waitForCompletion(getTimeToWait())` never returns, because its token is overwritten.

**Comment by hylkevds** [comment]
Besides giving QoS0 messages an ID I see only one other option, and that is giving the message a reference to the token.

This would also have the advantage that the CommsSender.run() does not have to hit the HashMap to find the token (and just a few calls later, ClientState.notifySend() again). QoS0 Tokens should simply never be added to the TokenManager, since they have no ID.
