### ISSUE TITLE
Port number is required for AWS IoT Device SDK.

### ISSUE THREAD

**Issue by fengsongAWS** [eclipse-paho/paho.mqtt.java#422]
Please fill out the form below before submitting, thank you!

- [X] Bug exists Release Version 1.2.0 ( Master Branch)
- [ ] Bug exists in Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)
The AWS IoT requires explicit port number even if it is 443. https://github.com/eclipse/paho.mqtt.java/blob/75594f0b226b14911f397b69059c18a50eaabb54/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/internal/websocket/WebSocketHandshake.java#L102 This is breaking the functionality of AWS IoT Device SDK in Java. Is there any reason we are ignoring the port number here? This was not changed before v1.1.0. Can we change it back?

If this is a bug regarding the Android Service, please raise the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

**Comment by jpwsutton** [comment]
Hi,
Under which circumstances does this break the SDK? I'd prefer not to change it back as it is currently valid behaviour (The port is an optional field in the HTTP host header), but if there is a valid edge case, we can certainly accommodate it.

**Comment by jpwsutton** [comment]
@fengsongAWS Is this still an issue? Or can I close it?
