### ISSUE TITLE
API changes report for Paho Client MQTTv3

### ISSUE THREAD

**Issue by lvc** [eclipse-paho/paho.mqtt.java#423]
Hi,

I'd like to share my results on API changes analysis for the library: https://abi-laboratory.pro/java/tracker/timeline/org.eclipse.paho.client.mqttv3/

The report is generated by the https://github.com/lvc/japi-compliance-checker tool for jars found at http://central.maven.org/maven2/org/eclipse/paho/org.eclipse.paho.client.mqttv3/ according to https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Thank you.

![org eclipse paho client mqttv3-2](https://user-images.githubusercontent.com/1517837/31161462-eb1f4598-a8df-11e7-82a2-0629366f9d0d.png)
![org eclipse paho client mqttv3-1](https://user-images.githubusercontent.com/1517837/31161463-eb4a3244-a8df-11e7-8bb0-521379fd05ce.png)

**Comment by jpwsutton** [comment]
Thanks @lvc, very interesting!
