### ISSUE TITLE
Connection to MQTT broker lost!

### ISSUE THREAD

**Issue by bosen365** [eclipse-paho/paho.mqtt.java#431]
I use MqttClient to subscribe to themes. When one or two items are consumed, the connectionLost method will be invoked.

My mqttclient pom.xml
`<dependency>
        <groupId>org.eclipse.paho</groupId>
        <artifactId>org.eclipse.paho.client.mqttv3</artifactId>
	<version>1.1.0</version>
</dependency>`

**Comment by bosen365** [comment]
`<dependency>
			<groupId>org.eclipse.paho</groupId>
			<artifactId>org.eclipse.paho.client.mqttv3</artifactId>
			<version>1.1.0</version>
		</dependency>`

**Comment by jpwsutton** [comment]
What is the error provided to connectionLost?

**Comment by bosen365** [comment]
`MemoryPersistence persistence = new MemoryPersistence();
MqttClient client = new MqttClient(bro, cid, persistence);
MqttConnectOptions connOpts = new MqttConnectOptions();
connOpts.setServerURIs(new String[] { bro });
connOpts.setCleanSession(true);
connOpts.setKeepAliveInterval(120); //  heartbeat interval 120s
connOpts.setAutomaticReconnect(true); // set reconnect automatic`

**But the override 'connectionLost' method will still be called。。**

`@Override
	public void connectionLost(Throwable throwable) {
		System.out.println("Connection lost");
	}`

**Comment by bosen365** [comment]
`MqttClient client = new MqttClient(bro, cid, persistence);`

the 'cid' is form `MqttClient.generateClientId()`。

Is it because of this reason that reconnection is unsuccessful?

**Comment by jpwsutton** [comment]
What version of MQTT broker are you using? And do you have a copy of the connection lost error message (from the Throwable)?

**Comment by icraggs** [comment]
I imagine this is now out of date.  Please reopen if there is more info.
