### ISSUE TITLE
Race Condition when subscribing to a topic with a retained message

### ISSUE THREAD

**Issue by bergph** [eclipse-paho/paho.mqtt.java#432]
Please fill out the form below before submitting, thank you!

- [x] Bug exists Release Version 1.2.0 ( Master Branch)
- [x] Bug exists in Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)

The method 

`IMqttToken subscribe(String[] topicFilters, int[] qos, Object userContext, IMqttActionListener callback, IMqttMessageListener[] messageListeners) throws MqttException`

in the MqttAsyncClient.java contains a race condition when subscribing to a topic with a retained message. As the message listener is added to the according data structure AFTER the subscription has been made, it can (and does so in our case quite often) happen that the retained message of a topic arrives BEFORE the subscribing thread returns from the subscribe(...) call and therefore before the listener has been actually registered. So the retained message is basically lost (i.e. delivered to the default handler).
Simply changing the order in this method does not help, as the downstream subscribe(...) method removes all potentially available listeners from the data structure. So you would end up with no listener registered at all.

**Comment by FrVaBe** [comment]
This might be the cause for my problem which I describe on StackOverflow:
[MQTT Retained messages not received when subscribing same topic from different applications at the same time](https://stackoverflow.com/questions/48769220/mqtt-retained-messages-not-received-when-subscribing-same-topic-from-different-a)

There is a repro on github here: [FrVaBe/MQTT/mqtt-client-showcase](https://github.com/FrVaBe/MQTT/tree/master/mqtt-client-showcase)

**Comment by chxiaowu** [comment]
face the same issue，currently give fixed clientId and  set  cleanSession to false.
Then looks ok.

**Comment by icraggs** [comment]
Fix added to 1.2.1
