### ISSUE TITLE
FilePersistence keeps file descriptor open for lockfile

### ISSUE THREAD

**Issue by konradmichael** [eclipse-paho/paho.mqtt.java#435]
- [true] Bug exists Release Version 1.2.0 ( Master Branch)
- [untested] Bug exists in Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)

We found out that one device ran out of file handles. Running `lsof` showed that plenty file descriptors where blocked by the lock file of the `MqttDefaultFilePersistence`

### result
$ lsof +D /directory
COMMAND   PID    USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
...
java    19590 devteam   80uW  REG  253,1        0 15728646 /directory/ID-tcplocalhost1883/.lck
java    19590 devteam   82uW  REG  253,1        0 15728646 /directory/ID-tcplocalhost1883/.lck
java    19590 devteam   83uW  REG  253,1        0 15728646 /directory/ID-tcplocalhost1883/.lck
java    19590 devteam   85uW  REG  253,1        0 15728646 /directory/ID-tcplocalhost1883/.lck
java    19590 devteam   86uW  REG  253,1        0 15728646 /directory/ID-tcplocalhost1883/.lck
java    19590 devteam   88uW  REG  253,1        0 15728646 /directory/ID-tcplocalhost1883/.lck
java    19590 devteam   89uW  REG  253,1        0 15728646 /directory/ID-tcplocalhost1883/.lck
java    19590 devteam   91uW  REG  253,1        0 15728646 /directory/ID-tcplocalhost1883/.lck
... (more of the same kind, if you wait long enough)

## Error Situation

One of the Broker was in a bad state and keept restarting. The device continuously connected to the broker by creating a new `MqttAsyncClient` (reconnect feature is not in use) and sending a message to the broker. It seems that while sending the message the client gets disconnected.

## Reproduction

I am able to reproduce an equal situation with the attached snippet.
[snippet.txt](https://github.com/eclipse/paho.mqtt.java/files/1421344/snippet.txt)

I also attached a logfile with Java and SLF4J logging (modified). I do not see anything that seems to help.
[log.txt](https://github.com/eclipse/paho.mqtt.java/files/1421319/log.txt)

Feedback is appreciated

**Comment by jpwsutton** [comment]
Are you closing the connection in the old MqttAsyncClient's? I would imagine that you probably have a lot of extra threads piling up with that method as well. I'd suggest closing the clients and nulling them if you're creating more. Otherwise, I'd suggest enabling automatic reconnect.

**Comment by konradmichael** [comment]
The client is disconnected and closed, like in my snippet file. Using reconnect is a possible workaround but does not solve the problem.
Your problem still is, that the file handles are not closed correctly with a bad mqtt broker.

**Comment by phils-ingenuity** [comment]
Hi. We're also experiencing this issue, except we are using the auto reconnect feature. What we see is that  multiple file descriptors are created for the same lock file whenever the client is disconnected from the server and messages are persisted to disk. Over time this means that the file descriptor limit is reached. Even on re-connection these are not recovered.

**Comment by alexmantaut** [comment]
@jpwsutton  Is there any workaround for this issue? Reconnecting does not seem to fix it for us, and it makes our application crash after a while because of the file descriptor limit...

**Comment by alexmantaut** [comment]
I did some research into the issue... It seems that on open() MqttDefaultFilePersistence creates a new FileLock, overwriting the existing file and losing the current file descriptor. Upon re-connection, this causes losing open file descriptors, as the GC does not call the release method.

Comparing to MemoryPersistance, and based on #178, I think that the MqttClientPersistence interface should allow for the open() method to be called again on a MqttClientPersistence that is already open... 

I submitted a PR with the suggested changes, please tell me if it is correct.

**Workaround**

As a workaround for @konradmichael and @phils-ingenuity, you can define a custom MqttClientPersistence based on  MqttDefaultFilePersistence to release the file on reconnection.

_Custom MqttClientPersistence_:

```
 class CustomMqttClientPersistence extends MqttDefaultFilePersistence{

    CustomMqttClientPersistence(String str){
      super(str);
    }

    @Override
    public void open(String clientId, String theConnection) throws MqttPersistenceException {

      try {
        close();
      }catch(MqttException e){
      }

      super.open(clientId,theConnection);
    }
  }
```


and include 
```
mqttClientPersistence = new CustomMqttClientPersistence(persistenceDir);
 asyncClient =new MqttAsyncClient(server, clientId, mqttClientPersistence);
```

**Comment by konradmichael** [comment]
Thank you for your research and resolution.
