### ISSUE TITLE
Why AlarmManager.cancle() throw a NPE？

### ISSUE THREAD

**Issue by JNYoung** [eclipse-paho/paho.mqtt.java#441]
When Clientcomms.connect is called,  an exception occurs due to some reasons, leads to shutdownConnection(conToken, mqttEx), then pingSender.stop() is called, in the method AlarmPingSender.stop()， alarmManager.cancel(pendingIntent) using a nulled pendingIntent,  and lead the throwed NPE "cancel() called with a null PendingIntent" only when the targetSdkVersion>=N, sourceCode below 
` if (mTargetSdkVersion >= Build.VERSION_CODES.N) {
                throw new NullPointerException(msg);
            } else {
                Log.e(TAG, msg);
                return;
            }`

this lead a crash sometimes, so could fix this problem?

**Comment by jpwsutton** [comment]
This sounds like an issue with the Android client, not the Java client, could you check the issues [here](https://github.com/eclipse/paho.mqtt.android/issues) please.
