### ISSUE TITLE
MQTTV5 - org.osgi.util.promise.PromiseExecutors does not exist

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.java#449]
Looks like org.osgi.util.promise.PromiseExecutors has been removed from the org.osgi.util.promise library, causing the MQTTv5 client to no longer compile. @timothyjward - Do you know if this has been removed from the OSGI Promise project? Should we refactor it away?

**Comment by timothyjward** [comment]
PromiseExecutors was renamed to PromiseFactory in the last round of specification updates.

**Comment by jpwsutton** [comment]
Thanks for the PR @timothyjward, that explains everything!

**Comment by timothyjward** [comment]
> Thanks for the PR @timothyjward, that explains everything!

I'm hopeful that will be the last change to OSGi Promises now - the final release build is due early in 2018.
