### ISSUE TITLE
pahov5 should match the MQTT spec terminology

### ISSUE THREAD

**Issue by borgendale** [eclipse-paho/paho.mqtt.java#458]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.2.0 ( Master Branch)
- [ ] Bug exists in Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)
- [x] Bug exists in MQTTv5 Version (mqttv5-new Branch)

If this is a bug regarding the Android Service, please raise the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

There are a number of cases where the pahov5 client uses terminology which does not match MQTT terminology.  It would be best to stay away form arbitrary differences:  In the case of property names:

pahov5: PublicationExpiryInterval   MQTT: MessageExpiryInterval
pahov5: UserDefinedProperties   MQTT: UserProperties
pahov5: RetainAvailableAdvertisement  MQTT: RetainAvailable
pahov5: AuthMethod  MQTT; AuthenticationMethod
pahov5: AuthData   MQTTT: AuthenticationData

Another case is the confusion about the term message.  This should be used only to describe the Application Message, and not to describe a packet.  Thus the callback authMessageArrived() should be authPacketArrived().

**Comment by jpwsutton** [comment]
Thanks @borgendale, Commit ce44d1d has updated the properties to have the correct terminology. Another one that I picked up was `payloadFormat` which was originally `isUTF8`, this has also been fixed.
