### ISSUE TITLE
In pahov5 the properties should be attached to the MqttMessage object

### ISSUE THREAD

**Issue by borgendale** [eclipse-paho/paho.mqtt.java#459]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.2.0 ( Master Branch)
- [ ] Bug exists in Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)
- [x] Bug exists in MQTTv5 Version (mqttv5-new Branch)

If this is a bug regarding the Android Service, please raise the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

The MQTT properties associated with a Message should be attached to the MqttMessage object, rather than being specified on the publish() method.  It is somewhat arbitrary what attributes of the message are properties and which are not.  It is really just whether they existed before MQTTv5.

At the current level (as of 20171208) the message properties are not attached to the message, and are not passed on the messageArrived() callback.  Thus they are not available when the message is received.

**Comment by jpwsutton** [comment]
This has been implemented and the MqttMessage Object now has the MqttProperties Object within it as well as a getProperties() and setProperties(MqttProperties) functions.
