### ISSUE TITLE
ANR Broadcast of Intent { act=MqttService.pingSender.1266f6b0-99ff-4ac1-ae8a-c4368b62218f flg=0x14

### ISSUE THREAD

**Issue by wqnmlgbe** [eclipse-paho/paho.mqtt.java#465]
Broadcast of Intent { act=MqttService.pingSender.1266f6b0-99ff-4ac1-ae8a-c4368b62218f flg=0x14
ANR Broadcast of Intent { act=MqttService.pingSender.1266f6b0-99ff-4ac1-ae8a-c4368b62218f flg=0x14 (has extras) }

1 android.os.MessageQueue.nativePollOnce(Native method)
--
2 android.os.MessageQueue.next(MessageQueue.java:323)
3 android.os.Looper.loop(Looper.java:135)
4 com.android.server.SystemServer.run(SystemServer.java:286)
5 com.android.server.SystemServer.main(SystemServer.java:171)
6 java.lang.reflect.Method.invoke!(Native method)
7 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:731)
8 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:621)

**Comment by jpwsutton** [comment]
Hi, This looks like it's related to the Android service (https://github.com/eclipse/paho.mqtt.android), could you raise this there please? Also, we will need more detail as the original issue template asked for before we can take a look at your issue. Thanks.
