### ISSUE TITLE
IMqttClient and IMqttAsyncClient don't have `reconnect()`

### ISSUE THREAD

**Issue by redboltz** [eclipse-paho/paho.mqtt.java#483]
Please fill out the form below before submitting, thank you!

- [x] Bug exists Release Version 1.2.0 ( Master Branch)
- [ ] Bug exists in Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)
- [ ] Bug exists in MQTTv5 Version (mqttv5-new Branch)

If this is a bug regarding the Android Service, please raise the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

I've checked bug the checkbox above. But it is confirmation for 1.2.0.

`MqttClient` has `reconnect()`.
https://github.com/eclipse/paho.mqtt.java/blob/master/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/MqttClient.java#L723

And `MqttAsyncClient` has `reconnect()` too.

https://github.com/eclipse/paho.mqtt.java/blob/master/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/MqttAsyncClient.java#L1369

The comment implies `reconnect()` is for users.

```java
	/**
	 * User triggered attempt to reconnect
	 * 
	 * @throws MqttException
	 *             if there is an issue with reconnecting
	 */
	public void reconnect() throws MqttException {
```

However, interface `IMqttClient` and `IMqttAsyncClient` don't have `reconnect()`. I think that they should have `reconnect()`.

Any ideas?

**Comment by icraggs** [comment]
Added to develop branch for 1.3
