### ISSUE TITLE
MqttClientPersistence, offset=6

### ISSUE THREAD

**Issue by SergioMejiaAragon** [eclipse-paho/paho.mqtt.java#490]
Hi 

java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=org/eclipse/paho/client/mqttv3/MqttClientPersistence, offset=6

Is there a version for java 6?

Kind regards

**Comment by jpwsutton** [comment]
Hi, We dropped support for older versions of Java last year, however version 1.1.0 of the Java client should work with Java 6 as that was compatible with Java 1.4.2 and above.
