### ISSUE TITLE
Resubscribe after reconnection

### ISSUE THREAD

**Issue by hermioone** [eclipse-paho/paho.mqtt.java#493]
Hi, I have a question. When the mqtt server restarts, the client should automatically reconnect to the server. This could be achieved by setting the automaticReconnect param. But after the clients reconnect to the server, it will not subscribe the topic before disconnection automatically. So is there any method to achieve this function? Thank you.

**Comment by jpwsutton** [comment]
This depends on a few factors, but assuming that the MQTT server is loosing all state between restarts and you are on a cleanSession=True connection, then you will want to add some code in the connectComplete callback that re-subscribes to the topics you want. You can also use the reconnect boolean to check whether it's an initial connection, or a successful reconnection.

On the other hand, if the MQTT server retains state between restarts and you are using a cleanSession=False connection, then your subscription *may* have been persisted and you will continue to receive messages, YMMV as it really depends on the implementation of the Server and how it's configured.

Of course, there is never any harm in just re-subscribing in either case as it will just override the previous subscription if it does exist.

**Comment by viulian** [comment]
@jpwsutton 

> Of course, there is never any harm in just re-subscribing in either case as it will just override the previous subscription if it does exist.

Could you please refine what to do with the MqttException thrown when calling `client.submit()` ? `connectComplete` role seems just to notify about the onSuccess() and is not intended for 'heavy lifting' since it does not allow throwing an Exception (that in turn could trigger the automaticReconnect.

**Comment by siepkes** [comment]
@jpwsutton What makes it somewhat harder to re-subscribe (when reconnecting) is that the `MqttCallback` only offers a `connectionLost` callback and no `connectionEstablished`. As far as I can tell there is currently no way to get notified when Paho has performed a reconnection.

**EDIT:** Right, scrap the above; I totally missed the `MqttCallbackExtended` interface...
