### ISSUE TITLE
Too many publication with QOS 0

### ISSUE THREAD

**Issue by xi67** [eclipse-paho/paho.mqtt.java#509]
Hi,

We use only Qos 0 messages.
Regularly we get error "Too many publications".
App restart resolve it.

From the docs, it only store QOS > 0 message.
So why iget this with Qos 0 ?

**Comment by xi67** [comment]
Some tests :
@Test
    void tooManyPublicationSyncTest() {
        MqttClient mqttClient;
        int i = 0;
        MqttMessage message = new MqttMessage(sMsg.getBytes());
        message.setQos(0);

        try {
            mqttClient = new MqttClient("tcp://localhost:2013", "PahoTest");
            mqttClient.connect();
            for (; i < 500; i++)
                mqttClient.publish(topic, message);
        } catch (MqttException e) {
            fail("Messages " + i + " : " + e.getMessage());
        }
    }

@Test
    void tooManyPublicationAsyncTest() {
        MqttAsyncClient mqttAsyncClient = null;
        int i = 0;
        MqttMessage message = new MqttMessage(sMsg.getBytes());
        message.setQos(0);

        try {
            mqttAsyncClient = new MqttAsyncClient("tcp://localhost:2013", "PahoTest");
            mqttAsyncClient.connect();

            while(!mqttAsyncClient.isConnected()) {
                try {
                    Thread.sleep(1);
                } catch (InterruptedException e) {
                    fail(e.getMessage());
                }
            }

            for (; i < 500; i++)
                mqttAsyncClient.publish(topic, message);
        } catch (MqttException e) {
            fail("Messages " + i + " : " + e.getMessage());
        }
    }

Results :
Paho Java v1.1.1 :
  tooManyPublicationSyncTest Pass
  tooManyPublicationAsyncTest Pass

Paho Java v1.2.0 :
  tooManyPublicationSyncTest Pass
  tooManyPublicationAsyncTest Failed with Messages 11 : Too many publications

**Comment by DannySchumann** [comment]
I have the same issue. The inflight messages don't decrease properly and will exceed the max in flight messages at some point.

**Comment by hylkevds** [comment]
I suspect this is the same issue as #421

**Comment by icraggs** [comment]
I think this is fixed by PR #563 which is now merged, and in release 1.2.1

**Comment by xi67** [comment]
Execution of tooManyPublicationAsyncTest() with 1.2.1 with success confirm the fix.
Thank you.

**Comment by icraggs** [comment]
@xi67 thank you for confirming
