### ISSUE TITLE
Provide an option to set maxReconnectDelay

### ISSUE THREAD

**Issue by inder123** [eclipse-paho/paho.mqtt.java#517]
Right now, paho client uses 128000 as the maximum reconnect delay (see MqttAsyncClient Line 1498). It would be useful for a developer to configure this delay value.

- [Y] Bug exists Release Version 1.2.0 ( Master Branch)
- [Y] Bug exists in Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)
- [Y] Bug exists in MQTTv5 Version (mqttv5-new Branch)

**Comment by jpwsutton** [comment]
Thanks @inder123, I've merged that to develop now. We are looking to release properly in June along with Eclipse Photon
