### ISSUE TITLE
Can MQTT v5 be on the top of okio? 

### ISSUE THREAD

**Issue by ghost** [eclipse-paho/paho.mqtt.java#529]
https://github.com/square/okio

**Comment by jpwsutton** [comment]
Hi, I'm not sure I understand the question, could you elaborate please?

**Comment by ghost** [comment]
Okio is a library that complements java.io and java.nio to make it much easier to access, store, and process data. So can MQTTv5 use it to improve the IO performance? Just like the OkHttp library https://github.com/square/okhttp
