### ISSUE TITLE
MQTTv5 QoS 0 publish fails when too quick

### ISSUE THREAD

**Issue by borgendale** [eclipse-paho/paho.mqtt.java#531]
When publishing at QoS 0 the newly created messages are all assigned packetID=0.  If a new message is published before the previous one is fully processed, the message is overlayed in the packetID table.  This can lead to an almost 100% message loss.

The key for a QoS 0 message needs to be something other than "0".

- [ ] Bug exists Release Version 1.2.0 ( Master Branch)
- [ ] Bug exists in MQTTv3 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)
- [x] Bug exists in MQTTv5 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)

If this is a bug regarding the Android Service, please raise the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

**Comment by seekforwings** [comment]
@jpwsutton could I ask why not changing the same code to avoid this problem(qos0 message may be overlayed  for too quick) on v3 ?
