### ISSUE TITLE
MQTTv5 does not implement variable byte integer checking

### ISSUE THREAD

**Issue by borgendale** [eclipse-paho/paho.mqtt.java#532]
The code in MqttDataTypes.readVariableByteInteger does not limit the length of the value, or limit the value in the range 0 to 2**28-1 (including allowing negative values to be decoded).  It also does not enforce that the smallest representation of a variable byte integer is used.

As this code does not check in incoming value, the code in MqttDataTYpes.encodeVariableByteInteger can encode invalid variable byte integers if the value of the input variable is not in the range 0 to 2**28-1.  

- [ ] Bug exists Release Version 1.2.0 ( Master Branch)
- [ ] Bug exists in MQTTv3 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)
- [x] Bug exists in MQTTv5 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)

If this is a bug regarding the Android Service, please raise the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

**Comment by icraggs** [comment]
I think there is a question in my mind as to whether clients have to implement this check on messages sent from the broker.  If the client library ensures that outgoing packets conform, and the server is compliant and does the check, then clients would not have to worry.  Certainly for the very smallest client implementations, it might seem like overkill.

**Comment by borgendale** [comment]
First, we are talking about two lines of code, one for the length and a second to check that the smallest encoding is used.

I accept that the smallest client is allowed to not do any error checking of t he input on the wire.  However, I do not classify paho-mqtt-java in that category.  In cases of an external client library such as paho, the client needs to protect the client application from bad servers, and the server protects other clients from a bad client.

**Comment by jpwsutton** [comment]
I think this was resolved under Issue #540, commit dfca976 where the validateVariableByteInt was added as the first step in encodeVariableByteInteger, as well as adding the same form of validation in readVariableByteInteger
