### ISSUE TITLE
MQTTv5 UTF-8 strings are not correctly validated

### ISSUE THREAD

**Issue by borgendale** [eclipse-paho/paho.mqtt.java#533]
The code in MqttDataTypes.decodeUTF8() does not actually validate that the UTF-8 is valid nor does it validate that the null (\u0000) character is not used.  It also should validate control and non-characters are not used.
 
While the MQTTv5 spec gave clients the ability to choose not to validate strings, this was intended for roll your own clients, and not for full function clients such as paho.  A client library is responsible for shielding the client application from bad input just as servers are required to shield clients from bad data.

The encodeUTF8 is likewise quite willing to send invalid strings to the server in violation of the MUST clause of the MQTTv5 spec.

While you are looking at this code, you might want to use StandardCharsets.UTF_8 rather than using a character set name.

- [ ] Bug exists Release Version 1.2.0 ( Master Branch)
- [ ] Bug exists in MQTTv3 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)
- [x ] Bug exists in MQTTv5 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)

If this is a bug regarding the Android Service, please raise the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

**Comment by icraggs** [comment]
Latest changes 

On line 182 reverse the test
On line 194: change the if statement logic
On line 199: put out the char as a 4 digit hex value
