### ISSUE TITLE
MQTTv5 does not implement QoS 2 according to the spec

### ISSUE THREAD

**Issue by borgendale** [eclipse-paho/paho.mqtt.java#535]
The MQTTv5 spec requires that an QoS 2 message be released before sending the PUBREC.  The current paho code releases the message when the PUBREL is received.  This is a change between the MQTTv3.1.1 and MQTTv5 spec.   In the earlier version it was allowed to do it either way, but since the sender did not know which way the receiver implemented it, could not correctly integrate with a 2 phase commit.

- [ ] Bug exists Release Version 1.2.0 ( Master Branch)
- [ ] Bug exists in MQTTv3 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)
- [x] Bug exists in MQTTv5 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)

If this is a bug regarding the Android Service, please raise the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

**Comment by jpwsutton** [comment]
Fixed in Issue #540, commit: 65340a3
