### ISSUE TITLE
How to add online and offline status functionality and block unblock api

### ISSUE THREAD

**Issue by KulbhushanSingh-Dev** [eclipse-paho/paho.mqtt.java#552]
Am new in mqqt implementation and i want to learn basics of its api with check user online/offline status in  and block/unblock functionality in android.

Thanks
Regards
Watson

**Comment by jpwsutton** [comment]
Hi @ChrisWatson12,

To check whether the client is connected, you can use the .isConnected() function. This is available in both the Blocking and Asynchronous APIs.

**Comment by Wanchen7** [comment]
@ChrisWatson12  

you can define a topic like this:
topicName: /online/state/clinetId
body: {
	"id":"clinetId",
	"isOnline":true
}
isRetained:true

and set a will topic like this:
topicName: /online/state/clinetId
body: {
	"id":"clinetId",
	"isOnline":false
}
isRetained:true

each client subscribe topic: "/online/state/+"
