### ISSUE TITLE
MQTT subscribe Offline message

### ISSUE THREAD

**Issue by Crimey** [eclipse-paho/paho.mqtt.java#558]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.2.0 ( Master Branch)
- [* **] Bug exists in MQTTv3 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)
- [ ] Bug exists in MQTTv5 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)

If this is a bug regarding the Android Service, please raise the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

When I subscribe to a topic,I just can only receive 120 offline messages.But real-time messages can be received.I use qos 1 and message retained is true.
![1](https://user-images.githubusercontent.com/40791910/42213775-4baeb7e4-7eec-11e8-9077-c4226e8661f6.png)
Only 120 offline messages can be received,But i can get real-time messge.
Is it something I missed?

**Comment by hylkevds** [comment]
How many off-line messages are retained seems more of a server-issue than a client-issue. How many messages a server will maximally retain for you while you are offline is not something the client has influence over.

**Comment by Crimey** [comment]
@hylkevds please see #559

**Comment by jpwsutton** [comment]
Hi @Crimey  What type of MQTT broker are you using? This does sound like a server side restriction rather than an issue with the Paho Client.

**Comment by icraggs** [comment]
No answer, so closing.
