### ISSUE TITLE
MQTT subscribe and publish

### ISSUE THREAD

**Issue by Crimey** [eclipse-paho/paho.mqtt.java#559]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.2.0 ( Master Branch)
- [*] Bug exists in MQTTv3 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)
- [ ] Bug exists in MQTTv5 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)

If this is a bug regarding the Android Service, please raise the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

i use qos 1 send 3485 message first,
![2](https://user-images.githubusercontent.com/40791910/42254605-00c01604-7f7a-11e8-96aa-1a65740aa062.png)
![3](https://user-images.githubusercontent.com/40791910/42254614-06bfa33a-7f7a-11e8-9312-149435f01553.png)
and subscribe not running, when i  use qos 1 receive 120 message ,use qos 0 receive 3485 message.
i use qos 0 send 7000 message first,
and subscribe not running, i use qos 1 and qos 0  all receive 7000 message.
look at #558

**Comment by StevenSalazarM** [comment]
I noticed about a similar problem, i'm sending messages with quality of service 0 and i receive all of  them as 1

**Comment by Crimey** [comment]
@StevenSalazarM not the same problem , I'm actively using qos 0 or 1 to receive  messages,the state of the message will not change,message state that was set when it was sent.

**Comment by hylkevds** [comment]
Can you make a minimal test project that shows the problem, because it's not quite clear what you are doing.

**Comment by jpwsutton** [comment]
@Crimey, As @hylkevds said, an example application that we can test locally would be a great help, thanks.

**Comment by icraggs** [comment]
No answer, so closing.
