### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by djbr-david** [eclipse-paho/paho.mqtt.java#560]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.2.0 ( Master Branch)
- [ ] Bug exists in MQTTv3 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)
- [ ] Bug exists in MQTTv5 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)

If this is a bug regarding the Android Service, please raise the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

Not an issue as such, but wondering when the next version is planned to be available. V1.2.0 was released almost a year ago and there have been a number of important fixes applied since then. Using SNAPSHOT versions in our codebase isn't really viable so a new release would be very handy.

Thanks to all who have contributed to the project.

**Comment by jpwsutton** [comment]
Hi @djbr-david, Sorry for the delay, we've just been polishing a few last things off with V5. The answer is: very soon!

**Comment by djbr-david** [comment]
Many thanks for the reply - much appreciated.
