### ISSUE TITLE
I wonder why I use "jar -xvf" to decompress the jar and use "jar cf" to recompress it after modify a class. but it can't use in my project again when I copy it to libs directory

### ISSUE THREAD

**Issue by linguokun1** [eclipse-paho/paho.mqtt.java#561]
I wonder why I use "jar -xvf" to decompress the jar and use "jar cf" to recompress it after modify a class. but it can't be used in my project again when I copy it to libs directory

I just want chage "executorService.awaitTermination(1L, TimeUnit.MILLISECOND)"  to 
 executorService.awaitTermination(200, TimeUnit.SECONDS).
because I find that it will 100% block the main thread in Android app about 2 Seconds.This is not good for the app users

![somepic](https://user-images.githubusercontent.com/16397362/42391136-fc971a06-8180-11e8-9e9f-3d4c7b105fcd.png)

**Comment by jpwsutton** [comment]
Hi @linguokun1,

We could always expose a property to allow you to change this value without having to recompress the JAR?
I would imagine though that the signature of the JAR will have changed, and so it will no longer be correctly signed. If you need to change this value now and can't wait, I'd recommend just compiling the JAR yourself from source.

**Comment by linguokun1** [comment]
@jpwsutton It is the best that if you can expose a property to allow me to change this value without having to recompress the JAR. Thanks
