### ISSUE TITLE
Why MqttException.REASON_CODE_SUBSCRIBE_FAILED

### ISSUE THREAD

**Issue by hugh282003** [eclipse-paho/paho.mqtt.java#565]
```
public void subscribe(String[] topicFilters, int[] qos) throws MqttException {
	IMqttToken tok = aClient.subscribe(topicFilters, qos, null, null);
	tok.waitForCompletion(getTimeToWait());
	int[] grantedQos = tok.getGrantedQos();
	for (int i = 0; i < grantedQos.length; ++i) {
		qos[i] = grantedQos[i];
	}
	if (grantedQos.length == 1 && qos[0] == 0x80) {
		throw new MqttException(MqttException.REASON_CODE_SUBSCRIBE_FAILED);
	}
}
```
what reason caused MqttException.REASON_CODE_SUBSCRIBE_FAILED?
why the logic is as below:
```
if (grantedQos.length == 1 && qos[0] == 0x80) {
	throw new MqttException(MqttException.REASON_CODE_SUBSCRIBE_FAILED);
}
```

**Comment by jpwsutton** [comment]
Hi @hugh282003,

When a subscription fails for any reason, the broker will return 0x80 in the SUBACK, the client will then throw the REASON_CODE_SUBSCRIBE_FAILED exception to the application. 

There is more detail about the SUBACK return codes here (http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718071).

To see why the subscription failed, you'll want to look at your server logs, alternatively if you can post the details of the subscription and it's properties you are trying to make, we might be able to identify why it would be failing.

**Comment by icraggs** [comment]
I think this question is answered.
