### ISSUE TITLE
PAHO V5 Traps in PUBLISH yet resposne is RC=0(?!) with exception=Untranslated MqttException - RC: 51001 (51001)

### ISSUE THREAD

**Issue by joelcdunn** [eclipse-paho/paho.mqtt.java#567]
- [ ] Bug exists Release Version 1.2.0 ( Master Branch)
- [ ] Bug exists in MQTTv3 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)
- [X] Bug exists in MQTTv5 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)

Local TC: mqttv5_reasoncode/testmqttv5_MPSwRC (just for reference)

disconnectMPSNoRc
1. MQTTv5 CONNECT with MaxPacketSize = 65 and RequestProblemInfo and RequestResponseInfo both 0x01
2. Send a Message that will cause a failure with the extra response info being larger than the MaxPacketSz
3. but before that can happen, PAHO traps during the PUBLISH and the PACKET NEVER Arrives at the MQTT Server.

I never see the Publish Packet arrive at the server and have attached the PAHO Trace from from the CONNECT to the END Of File.
The message had the follow parameters:
        
        <Action name="CreateMessage" type="CreateMessage">
            <ActionParameter name="structure_id">txmsg</ActionParameter>
            <ActionParameter name="connection_id">CF1</ActionParameter>
            <ApiParameter name="msgType">TEXT</ApiParameter>
            <ApiParameter name="payload">TEXT: Publish A Message that is larger than MAXIMUM PACKET SIZE specified on CONNECT and the CONNECTion will be dropped.</ApiParameter>
            <ApiParameter name="userprop.0">First40=0000000000111111111122222222223333333333</ApiParameter>
            <ApiParameter name="userprop.1">Second40=4444444444555555555566666666667777777777</ApiParameter>

            <ActionParameter name="topic">/bigmessages</ActionParameter>
            <ActionParameter name="QoS">2</ActionParameter>
	    <ActionParameter name="waitForAck">true</ActionParameter>
            <ApiParameter name="expectedrcv5">149</ApiParameter>
        </Action>
 
**Test Case LOG:**
[23/07/18 19:44:35:629 GMT] 000015 I ISMTEST2517: Publishing message at QoS=2 on topic '/bigmessages'
[23/07/18 19:44:35:643 GMT] 000018 V ISMTEST2517: Disconnected: MqttDisconnectResponse [returnCode=0, reasonString=null, userProperties=null, serverReference=null, exception=Untranslated MqttException - RC: 51001 (51001)]
Untranslated MqttException - RC: 51001 (51001)
Untranslated MqttException - RC: 51001 (51001)
	at org.eclipse.paho.mqttv5.common.ExceptionHelper.createMqttException(ExceptionHelper.java:25)
	at org.eclipse.paho.mqttv5.client.wire.MqttOutputStream.write(MqttOutputStream.java:83)
	at org.eclipse.paho.mqttv5.client.internal.CommsSender.run(CommsSender.java:141)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:191)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:811)

The response with  returnCode=0 is rather inaccurate.
I have not idea what exception=Untranslated MqttException - RC: 51001 (51001)  means

**MQTT Server Log:**
MQTT receive 10 CONNECT connect=24 rc=0: len=42 
0004 4d515454 05 02 0023 0c 17 01 19 01 22 0000 27 00000041  0011 646973 636f6e6e 6563744d 50534e6f 5243 
[..MQTT...#....."..'...A..disconnectMPSNoRC]

MQTT send 20 CONNACK connect=24: len=14 00 00 0b 21 0100 22 0008 27 00400000 [...!.."..'.@..]

**I get a connection and then the next thing I see is that connection FAILED!!**
Set error "The connection was closed by the client." (91)
mqtt_closing: connect=24 client=disconnectMPSNoRC rc=91 clean=0 reason=The connection was closed by the client.
close MQTT connection: connect=24

**PAHO LOG:**
....
FINE	 18-07-23  21:16:39.0839 	nternal.ClientComms	 connectComplete        	24	disconnectMPSNoRC: state=CONNECTED
FINE	 18-07-23  21:16:39.0839 	ient.internal.Token	 markComplete           	24	disconnectMPSNoRC: >key=Con response=MqttConnAck [returnCode=0, sessionPresent=false, properties=MqttProperties [validProperties=[17, 33, 36, 37, 39, 18, 34, 40, 41, 42, 19, 26, 28, 21, 22, 31, 38], receiveMaximum=256, maximumPacketSize=4194304, topicAliasMaximum=8]] excep=null
FINE	 18-07-23  21:16:39.0840 	ient.internal.Token	 notifyComplete         	24	disconnectMPSNoRC: >key=Con response=MqttConnAck [returnCode=0, sessionPresent=false, properties=MqttProperties [validProperties=[17, 33, 36, 37, 39, 18, 34, 40, 41, 42, 19, 26, 28, 21, 22, 31, 38], receiveMaximum=256, maximumPacketSize=4194304, topicAliasMaximum=8]] excep=null
FINE	 18-07-23  21:16:39.0840 	nternal.ClientState	 notifyResult           	24	disconnectMPSNoRC: keyCon, msg=MqttConnAck [returnCode=0, sessionPresent=false, properties=MqttProperties [validProperties=[17, 33, 36, 37, 39, 18, 34, 40, 41, 42, 19, 26, 28, 21, 22, 31, 38], receiveMaximum=256, maximumPacketSize=4194304, topicAliasMaximum=8]], excep=null
FINE	 18-07-23  21:16:39.0841 	ernal.CommsCallback	 asyncOperationComplete 	24	disconnectMPSNoRC: new workAvailable. key=Con
FINE	 18-07-23  21:16:39.0841 	nal.CommsTokenStore	 removeToken            	24	disconnectMPSNoRC: key=Con
FINE	 18-07-23  21:16:39.0842 	ernal.CommsReceiver	 run                    	24	disconnectMPSNoRC: network read message
FINE	 18-07-23  21:16:39.0842 	nternal.ClientState	 get                    	23	disconnectMPSNoRC: new work or ping arrived 
FINE	 18-07-23  21:16:39.0842 	ernal.CommsCallback	 handleActionComplete   	25	disconnectMPSNoRC: callback and notify for key=Con
FINE	 18-07-23  21:16:39.0843 	nternal.ClientState	 get                    	23	disconnectMPSNoRC: wait for new work or for space in the inflight window
FINE	 18-07-23  21:16:39.0843 	nternal.ClientState	 notifyComplete         	25	disconnectMPSNoRC: received key=0 token=org.eclipse.paho.mqttv5.client.MqttToken@c968a686 message=MqttConnAck [returnCode=0, sessionPresent=false, properties=MqttProperties [validProperties=[17, 33, 36, 37, 39, 18, 34, 40, 41, 42, 19, 26, 28, 21, 22, 31, 38], receiveMaximum=256, maximumPacketSize=4194304, topicAliasMaximum=8]]
FINE	 18-07-23  21:16:39.0844 	ient.internal.Token	 notifyComplete         	25	disconnectMPSNoRC: >key=Con response=MqttConnAck [returnCode=0, sessionPresent=false, properties=MqttProperties [validProperties=[17, 33, 36, 37, 39, 18, 34, 40, 41, 42, 19, 26, 28, 21, 22, 31, 38], receiveMaximum=256, maximumPacketSize=4194304, topicAliasMaximum=8]] excep=null
FINE	 18-07-23  21:16:39.0845 	ernal.CommsCallback	 fireActionEvent        	25	disconnectMPSNoRC: call onSuccess key=Con
FINE	 18-07-23  21:16:39.0845 	ient.internal.Token	 markComplete           	25	disconnectMPSNoRC: >key=null response=MqttConnAck [returnCode=0, sessionPresent=false, properties=MqttProperties [validProperties=[17, 33, 36, 37, 39, 18, 34, 40, 41, 42, 19, 26, 28, 21, 22, 31, 38], receiveMaximum=256, maximumPacketSize=4194304, topicAliasMaximum=8]] excep=null
FINE	 18-07-23  21:16:39.0846 	ient.internal.Token	 notifyComplete         	25	disconnectMPSNoRC: >key=null response=MqttConnAck [returnCode=0, sessionPresent=false, properties=MqttProperties [validProperties=[17, 33, 36, 37, 39, 18, 34, 40, 41, 42, 19, 26, 28, 21, 22, 31, 38], receiveMaximum=256, maximumPacketSize=4194304, topicAliasMaximum=8]] excep=null
FINE	 18-07-23  21:16:39.0847 	ient.internal.Token	 waitForResponse        	21	disconnectMPSNoRC: key=null response=MqttConnAck [returnCode=0, sessionPresent=false, properties=MqttProperties [validProperties=[17, 33, 36, 37, 39, 18, 34, 40, 41, 42, 19, 26, 28, 21, 22, 31, 38], receiveMaximum=256, maximumPacketSize=4194304, topicAliasMaximum=8]]
FINE	 18-07-23  21:16:39.0848 	ernal.CommsCallback	 run                    	25	disconnectMPSNoRC: notify spaceAvailable
FINE	 18-07-23  21:16:39.0849 	ernal.CommsCallback	 run                    	25	disconnectMPSNoRC: wait for workAvailable
FINE	 18-07-23  21:16:39.0874 	nal.CommsTokenStore	 getOutstandingDelTokens	21	disconnectMPSNoRC: >
**FINE	 18-07-23  21:16:39.0875 	ent.MqttAsyncClient	 publish                	21	disconnectMPSNoRC: < topic=/bigmessages message=nulluserContext=null callback=null**
FINE	 18-07-23  21:16:39.0877 	nternal.ClientComms	 internalSend           	21	disconnectMPSNoRC: 200
FINE	 18-07-23  21:16:39.0878 	nternal.ClientState	 send                   	21	disconnectMPSNoRC: pending publish key=1 qos=2 message=MqttPublish [, qos=2, messageId=1, retained=false, duplicate=false, topic=/bigmessages, payload=[hex=544558543a205075626c6973682041204d657373, utf8=TEXT: Publish A Mess, length=120], properties=MqttProperties [validProperties=[1, 2, 35, 8, 9, 38, 3, 126, 11], topicAlias=1, userProperties=[UserProperty [key=First40, value=0000000000111111111122222222223333333333], UserProperty [key=Second40, value=4444444444555555555566666666667777777777]]]
FINE	 18-07-23  21:16:39.0879 	nal.CommsTokenStore	 saveToken              	21	disconnectMPSNoRC: key=1 message=MqttPublish [, qos=2, messageId=1, retained=false, duplicate=false, topic=/bigmessages, payload=[hex=544558543a205075626c6973682041204d657373, utf8=TEXT: Publish A Mess, length=120], properties=MqttProperties [validProperties=[1, 2, 35, 8, 9, 38, 3, 126, 11], topicAlias=1, userProperties=[UserProperty [key=First40, value=0000000000111111111122222222223333333333], UserProperty [key=Second40, value=4444444444555555555566666666667777777777]]]
FINE	 18-07-23  21:16:39.0880 	nal.CommsTokenStore	 saveToken              	21	disconnectMPSNoRC: key=1 token=org.eclipse.paho.mqttv5.client.MqttDeliveryToken@b02de821
FINE	 18-07-23  21:16:39.0881 	ent.MqttAsyncClient	 publish                	21	disconnectMPSNoRC: <
FINE	 18-07-23  21:16:39.0881 	nternal.ClientState	 get                    	23	disconnectMPSNoRC: new work or ping arrived 
FINE	 18-07-23  21:16:39.0882 	nternal.ClientState	 get                    	23	disconnectMPSNoRC: +1 actualInFlight=1
FINE	 18-07-23  21:16:39.0882 	nternal.CommsSender	 run                    	23	disconnectMPSNoRC: network send key=1 msg=MqttPublish [, qos=2, messageId=1, retained=false, duplicate=false, topic=/bigmessages, payload=[hex=544558543a205075626c6973682041204d657373, utf8=TEXT: Publish A Mess, length=120], properties=MqttProperties [validProperties=[1, 2, 35, 8, 9, 38, 3, 126, 11], topicAlias=1, userProperties=[UserProperty [key=First40, value=0000000000111111111122222222223333333333], UserProperty [key=Second40, value=4444444444555555555566666666667777777777]]]
SEVERE	 18-07-23  21:16:39.0883 	nternal.CommsSender	 handleRunException     	23	disconnectMPSNoRC: exception
Throwable occurred: Untranslated MqttException - RC: 51001 (51001)
	at org.eclipse.paho.mqttv5.common.ExceptionHelper.createMqttException(ExceptionHelper.java:25)
	at org.eclipse.paho.mqttv5.client.wire.MqttOutputStream.write(MqttOutputStream.java:83)
	at org.eclipse.paho.mqttv5.client.internal.CommsSender.run(CommsSender.java:141)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:191)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:811)
FINE	 18-07-23  21:16:39.0887 	nternal.ClientComms	 shutdownConnection     	23	disconnectMPSNoRC: state=DISCONNECTING
FINE	 18-07-23  21:16:39.0888 	ernal.CommsCallback	 run                    	25	disconnectMPSNoRC: notify spaceAvailable
FINE	 18-07-23  21:16:39.0889 	ernal.CommsCallback	 run                    	25	disconnectMPSNoRC: wait for workAvailable
FINE	 18-07-23  21:16:39.0889 	ernal.CommsCallback	 stop                   	23	disconnectMPSNoRC: stopping
FINE	 18-07-23  21:16:39.0890 	ernal.CommsCallback	 stop                   	23	disconnectMPSNoRC: notify workAvailable and wait for run
FINE	 18-07-23  21:16:39.0890 	ernal.CommsCallback	 run                    	25	disconnectMPSNoRC: notify spaceAvailable
FINE	 18-07-23  21:16:39.0891 	ernal.CommsCallback	 stop                   	23	disconnectMPSNoRC: stopped
FINE	 18-07-23  21:16:39.0893 	ernal.CommsReceiver	 stop                   	23	disconnectMPSNoRC: stopping
FINE	 18-07-23  21:16:39.0893 	ernal.CommsReceiver	 stop                   	23	disconnectMPSNoRC: stopped
FINE	 18-07-23  21:16:39.0894 	ernal.CommsReceiver	 run                    	24	disconnectMPSNoRC: Stopping due to IOException
FINE	 18-07-23  21:16:39.0894 	ernal.CommsReceiver	 run                    	24	disconnectMPSNoRC: <
FINE	 18-07-23  21:16:39.0895 	nal.CommsTokenStore	 quiesce                	23	disconnectMPSNoRC: resp=Client is currently disconnecting (32102)
FINE	 18-07-23  21:16:39.0896 	nternal.ClientComms	 handleOldTokens        	23	disconnectMPSNoRC: >
FINE	 18-07-23  21:16:39.0896 	nternal.ClientState	 resolveOldTokens       	23	disconnectMPSNoRC: reason Untranslated MqttException - RC: 51001 (51001)
FINE	 18-07-23  21:16:39.0897 	nal.CommsTokenStore	 getOutstandingTokens   	23	disconnectMPSNoRC: >
FINE	 18-07-23  21:16:39.0898 	ernal.CommsCallback	 handleActionComplete   	23	disconnectMPSNoRC: callback and notify for key=1
FINE	 18-07-23  21:16:39.0899 	ient.internal.Token	 notifyComplete         	23	disconnectMPSNoRC: >key=1 response=null excep=Untranslated MqttException - RC: 51001 (51001)
FINE	 18-07-23  21:16:39.0899 	nternal.ClientState	 disconnected           	23	disconnectMPSNoRC: disconnected
FINE	 18-07-23  21:16:39.0900 	nternal.ClientState	 clearState             	23	disconnectMPSNoRC: >
FINE	 18-07-23  21:16:39.0901 	nal.CommsTokenStore	 clear                  	23	disconnectMPSNoRC: > 1 tokens
FINE	 18-07-23  21:16:39.0901 	nternal.ClientState	 clearConnectionState   	23	disconnectMPSNoRC: Clearing Connection State (Topic Aliases)
FINE	 18-07-23  21:16:39.0902 	nternal.CommsSender	 stop                   	23	disconnectMPSNoRC: stopping sender
FINE	 18-07-23  21:16:39.0903 	nternal.CommsSender	 stop                   	23	disconnectMPSNoRC: stopped
FINE	 18-07-23  21:16:39.0907 	ent.TimerPingSender	 stop                   	23	disconnectMPSNoRC: stop
FINE	 18-07-23  21:16:39.0907 	nternal.ClientComms	 shutdownConnection     	23	disconnectMPSNoRC: state=DISCONNECTED
FINE	 18-07-23  21:16:39.0908 	ernal.CommsCallback	 connectionLost         	23	disconnectMPSNoRC: call connectionLost
<end of log>

**Comment by joelcdunn** [comment]
This is still an issue with the UPDATED PAHO Driver.
[paho0.log.0.log](https://github.com/eclipse/paho.mqtt.java/files/2295204/paho0.log.0.log)
Here is the updated PAHO TRACE using that new Driver.

One note that might not have been clear is there is only 1 client which SUBs and PUBs to itself in same session/connection.

**Comment by jpwsutton** [comment]
Exception 51001, is for incoming / outgoing message size too large. I've added the correct Exception messages in commit d462aeb. It looks though like the Publish you were sending was going to be too large. Now that I've added the correct Exception message, you can try re-running this test case to see if it performs correctly.
