### ISSUE TITLE
Information about 1.2.1 release: date, stability, nightly builds.

### ISSUE THREAD

**Issue by kami4ka** [eclipse-paho/paho.mqtt.java#570]
Hello.
I'm totally satisfied with Paho library and it's a pretty great thing for my projects, but I've faced the problem when tried to fix crashes, that occurred in lib.
A lot of crash fixes and changes are already committed and merged to develop branch, but in case of "nightly" label, it seems not suitable for production usage.

So, community, any hope about 1.2.1 version at an early date or at some fixed point in time?

Thanks for a great job!

**Comment by LeoDroidCoder** [comment]
+1 really waiting for an update

**Comment by KulykOleg** [comment]
+1 more frequent releases will be very useful

**Comment by icraggs** [comment]
The usual maintainer, @jpwsutton is on vacation until next week.  The plan is to get a new release out in the next week or two, along with the MQTT V5 support.

**Comment by kami4ka** [comment]
@icraggs nice to hear such great news. Waiting for release!

**Comment by jpwsutton** [comment]
Hi all, we're working on getting a stable release out ASAP. Currently there are some tests that although seem to pass on a normal machine, fail on Travis due to suspected timing issues.  I'm going to see if I can resolve these this week as well as going through all of the open issues to make sure they are up to date.

**Comment by ghost** [comment]
@jpwsutton Any update on this?

**Comment by jpwsutton** [comment]
Hi @LaurenceBonney, We are looking at getting a release built by the end of next week.

**Comment by IntellectSoftDeveloper** [comment]
@jpwsutton nice to hear such great news!
Can you, please, keep us informed, because this is really great improvement for IoT community!

**Comment by frittentheke** [comment]
Any update on at least a bugfixing 1.2.1? There are so many known/fixed issues with 1.2.0...

**Comment by kami4ka** [comment]
+1

Waiting for the official fix https://github.com/eclipse/paho.mqtt.java/issues/382 because of high crash impact.

**Comment by ghost** [comment]
@jpwsutton @icraggs  Any update on this?

**Comment by nrktkt** [comment]
Hey @icraggs, do you know if v5 support will be in 1.2.1 or a separate release?

**Comment by icraggs** [comment]
@kag0 v5 support will be in 1.3.0.  1.2.1 will be a service release of the 1.2 branch.  That's my plan anyway - I hope they can closely follow each other.  I'll be looking after them for the time being, as @jpwsutton has moved on, so you'll have to bear with me as I try to fit everything in (other client libraries, etc) 

Update - I got that wrong.  It seems the V5 support has already been merged into the develop branch, so I'll probably end up releasing 1.3.0 with all the updates.

**Comment by kami4ka** [comment]
@icraggs I'm sorry for being a bit annoying, but is there any chances to have any library update in the nearest future? Thanks.

**Comment by icraggs** [comment]
@kami4ka it's not annoying :-).  I've been working on the 1.3 release (https://github.com/eclipse/paho.mqtt.java/milestone/2) for a while now, addressing some existing V3 high priority issues and finishing the V5 support, including, and most of all, tests.  The updates are in the develop branch.  I've just got test coverage measurements working to guide the addition of new tests. 

I hope to have the release done by the end of next week, at least in a beta form.

**Comment by icraggs** [comment]
Ok.  I've created a 1.2.1 service release, as I'm still working on an MQTT V5 implementation.  There could be more service releases of the V3 client (1.2.2) before we I make the 1.3 V5 release.

**Comment by loffa** [comment]
Hello @icraggs,
Do you know if paho.mqtt.android will also follow a release with the updates?
I can see now that the latest paho-java referenced in the android-lib is 1.1.0 ([here](https://github.com/eclipse/paho.mqtt.android/blob/master/build.gradle#L29)) and it seems like quite a lot of bugfixes have been made since then.

**Comment by icraggs** [comment]
@loffa I'd have to look at the Android library to figure that out.  I've been concentrating on MQTT V5 support for now.  If we don't have an issue open to remind me to look at the Android lib, then we should have one.  Would you like to open one?
