### ISSUE TITLE
Missing up to date releases at http://download.eclipse.org/paho

### ISSUE THREAD

**Issue by jliang1010** [eclipse-paho/paho.mqtt.java#579]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.2.0 ( Master Branch)
- [ ] Bug exists in MQTTv3 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)
- [ ] Bug exists in MQTTv5 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)

I am using this link http://download.eclipse.org/paho/ to check out the paho artifact in my project. Found out that the compositeArtifacts.xml and compositeContent.xml doesn't include 1.1.0 version even though 1.1.0 version exists in the releases folder already. Is there any particular reason for this? I have some required features relying on version 1.1.0+. Many thanks.

**Comment by icraggs** [comment]
This is now at 1.2.0.  I did it in January.  Thanks, and sorry for the delay.
