### ISSUE TITLE
Wrong release and snapshot version at: https://www.eclipse.org/paho/clients/java/

### ISSUE THREAD

**Issue by kami4ka** [eclipse-paho/paho.mqtt.java#580]
When I visit the following link (https://www.eclipse.org/paho/clients/java/) from the main README.md  I can see that the "The latest release version is 1.0.2 and the current snapshot version is 1.0.3." but it seems like not the truth, because now the latest release version is 1.2.0 and snapshot version is 1.2.1.

It would be quite nice to update that page.
Thanks.

**Comment by icraggs** [comment]
Thanks

**Comment by icraggs** [comment]
I've done it now.  Thanks for pointing it out.
