### ISSUE TITLE
Messages not being deleted from disk after reconnection, while using MqttDefaultFilePersistence

### ISSUE THREAD

**Issue by alexmantaut** [eclipse-paho/paho.mqtt.java#594]
Please fill out the form below before submitting, thank you!

- [*] Bug exists Release Version 1.2.0 ( Master Branch)
- [*] Bug exists in MQTTv3 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)

**How to reproduce:**
- Create a client with MqttDefaultFilePersistence, set the persistance dir to a known location.
- Set a DisconnectedMessageBuffer with small buffer size (i.e 10) and isDeleteOldestMessages = true
- Disconnect the connection to the broker.
- Start queuing messages after the disconnection is detected. The client queues N messages
- Reconnect to the broker.

**Expected:**
The library successfully connects and sends the 10 messages.
The persistence dir should be empty after sending the files.
While the broker is disconnected, we should never have more than 10 messages on disk.

**What happens:**
The library successfully connects and sends the 10 messages.
But if you go to the persistence dir, you will find lots of .msg files (N-10 specifically). If I restart the client, it deletes those files.
While disconnected, the number of files on the persistence dir keeps growing.

**Analysis:** 
By looking at the source code DisconnectedMessageBuffer::putMessage(), it seems like the buffer deletes the oldest message if the buffer size is met. There does not seem to be anything similar being done on the persistence class.
This also means that if the connection is down, the persistence class is going to keep generating files until it fills the disk is filled.

**Questions:**
Am I using the library incorrectly, or is there a bug while using persistence and default file persistence?
Is there any other way to prevent MqttDefaultFilePersistence from filling the disk?

Thanks in advance,

**Comment by jpwsutton** [comment]
Hi, when you say that you are disconnecting and reconnecting to the broker, is this a manual call that you are making? Or is this an unexpected disconnection i.e. network loss, and the reconnection is completed by the automatic reconnect functionality?

**Comment by alexmantaut** [comment]
The disconnection is caused by a network loss.
Automatic reconnect is on.

**Comment by alexmantaut** [comment]
I checked the code, and messages where being discarded in DisconnectedMessageBuffer, but they were not being discarded from the Persistence class.

The solution I came up with was adding a callback to be called if a message is discarded from the buffer, and used that to un-persist the message.

Can you please review my PR and check if if makes sense? I am open to suggestions on the issue.

**Comment by rdasgupt** [comment]
Created PR #760 to fix conflicts in original PR #596.
