### ISSUE TITLE
Programmatically acknowledge the publisher

### ISSUE THREAD

**Issue by sushanth-s** [eclipse-paho/paho.mqtt.java#597]
Hi,

We would like to know is there way that the subscriber can be programmatically acknowledge the publisher
with a message.

**Comment by icraggs** [comment]
In a pub-sub system such as MQTT, it is deliberate design to disassociate senders and receivers.  A publisher does not know if a particular message is going to be sent to any subscribers.

You can always have the subscriber send an MQTT message to a response topic for the original publisher to receive.  This is a common model when using QoS 0 messages.
