### ISSUE TITLE
Changes from PR#554 on gradle

### ISSUE THREAD

**Issue by desokroshan** [eclipse-paho/paho.mqtt.java#607]
Please fill out the form below before submitting, thank you!

- [*] Bug exists Release Version 1.2.0 ( Master Branch)
- [*] Bug exists in MQTTv3 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)
- [*] Bug exists in MQTTv5 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)

@icraggs I want to be able to consume the changes that were merged as part of [PR#554](https://github.com/eclipse/paho.mqtt.java/pull/554) through gradle on Android Studio. Is there a plan to release these changes anytime soon?

If this is a bug regarding the Android Service, please raise the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

**Comment by icraggs** [comment]
I'm working on the 1.3 release (https://github.com/eclipse/paho.mqtt.java/milestone/2) which will incorporate these changes.   I hope to have this done by the end of January.

You could use the develop branch in the meantime - most of my changes will be on the MQTT V5 client.

**Comment by desokroshan** [comment]
Great, thanks. Just for the context, I am working on adding custom authorizer support in  [aws-sdk-android](https://github.com/aws-amplify/aws-sdk-android). Since the SDK uses paho java client, we need custom header support in paho(Changes in PR#554) to be able to release the changes to our customers.
I have been working off of the develop branch and would like to point out an additional blocker to our release. The develop branch has the required custom header support but additionally also has a known issue in connecting to AWS IoT Broker. See https://github.com/eclipse/paho.mqtt.java/issues/345 for details. So even though the 1.3 release would have custom header support, we cannot really use it and release our changes. Currently we are using paho version 1.1.0 and have not been able to update our dependency to the latest version because of https://github.com/eclipse/paho.mqtt.java/issues/345. I assume the fix for this is not planned for 1.3 release as I don't see it in the list of issues milestone addresses. It would be great to have it as part of the release since there has been quite a few customer requests for custom authorization support in the SDK. If it would not be possible to include it in this release can you share some tentative timeline on when we can have these changes?

**Comment by rubyrose-alexis** [comment]
@icraggs I do not see the fix for custom authorization headers in the milestone for 1.3.0 (https://github.com/eclipse/paho.mqtt.java/milestone/2). Will this change be included in 1.3.0?

**Comment by frankmuellr** [comment]
Hi @icraggs,

Is there an ETA for when custom authorization headers support will be released? We have several customers requesting the feature. Please let us know if there's anything we can do to help.

**Comment by icraggs** [comment]
I'm happy to include a fix for the issue of 'custom authorisation headers'.    From reading the issues and PR, I think that the fix is already in the develop branch.  Does anyone want to confirm or deny that assumption?

Everything in the develop branch will be included in the next release.  I'm hoping to make a 1.2.1 service release with all the fixes included so far, as I'm refactoring the MQTT V5 client lib.

**Comment by desokroshan** [comment]
Yes, I can confirm that the changes to support 'Custom authorization headers' are already in develop branch([Relevant Commit](https://github.com/eclipse/paho.mqtt.java/commit/fcd8e516d52ec085623b728d07dc82d1fc0a1be2)). A service release would be great for our purpose.

**Comment by icraggs** [comment]
I'm trying to create a 1.2.1 release with all the fixes in the develop branch.  At the moment I'm dealing with an issue in the Eclipse infrastructure which is stopping the jars from being signed.  I hope this will be resolved in the next day or so.

**Comment by desokroshan** [comment]
Thanks for the update.

**Comment by icraggs** [comment]
1.2.1 released.  Should be in all repos.

**Comment by rubyrose-alexis** [comment]
Thank you @icraggs !

**Comment by frankmuellr** [comment]
@icraggs - The release is not listed here btw: https://github.com/eclipse/paho.mqtt.java/releases

**Comment by icraggs** [comment]
@muellerfr I was waiting a couple of days to make sure I hadn't messed anything up... I'll probably tag it on the weekend. The jars are in the maven/nexus repos
