### ISSUE TITLE
the client can not receive messages after reconnected, once the count of offline messages exceeded 10

### ISSUE THREAD

**Issue by flagon1986** [eclipse-paho/paho.mqtt.java#608]
- [*] Bug exists Release Version 1.2.0 ( Master Branch)
- [ ] Bug exists in MQTTv3 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)
- [ ] Bug exists in MQTTv5 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)

I use org.eclipse.paho.client.mqttv3 V1.2.0 in my java project, and with mosquitto V1.5.5 as the broker on server side.

just as the subject, with the preconditions below, if at the time when the client reconnected to the broker, the count of offline messages have exceeded 10, for example 15, the client would have no ability to handle the messages arrived.

precondition:
1. Static client ID per instance
2. QoS 1
3. clean session = false
4. auto reconnect = true

I found maybe similar issues just as #589  #595  #348, but still not sure how to fix this.

I have debuged into the org.eclipse.paho.client.mqttv3, and found there is a function messageArrived in the file CommsCallback.java just as below:

```
public void messageArrived(MqttPublish sendMessage) {
		final String methodName = "messageArrived";
		if (mqttCallback != null || callbacks.size() > 0) {
			// If we already have enough messages queued up in memory, wait
			// until some more queue space becomes available. This helps 
			// the client protect itself from getting flooded by messages 
			// from the server.
			synchronized (spaceAvailable) {
				while (running && !quiescing && messageQueue.size() >= INBOUND_QUEUE_SIZE) {
					try {
						// @TRACE 709=wait for spaceAvailable
						log.fine(CLASS_NAME, methodName, "709");
						spaceAvailable.wait(200);
					} catch (InterruptedException ex) {
					}
				}
			}
                    ...
```
when these maybe 15 offline messages arrived after reconnected, it would enter the while loop at once, and never break the loop (unless the client disconneted, so the param running would change to false). At this time, the messages arrived would cannot be handled.

and at the time this issue happening, the second issue would appear like below:
if i set keepAliveInterval as 30 seconds, then after 1 minute(two cycles of keepAliveInterval), the client will disconnect the broker with cause "Timed out waiting for a response from the server (32000)", and before it reconnected to the broker it may consume 1 message in the messageQueue that buffered occasionally.

if need, i could upload my demo and the descriptions to help recreate this issue.
please help, or is there anything wrong in my code.

**Comment by flagon1986** [comment]
I think i need to create new thread to subscribe the topics after the client connected, it should work.

**Comment by hvincente** [comment]
Hi,

@flagon1986, in your last comment, you made an assumption that subscribing in a new thread will fix your problem, did it work ?

same problem here and i think this issue is not resolved.
