### ISSUE TITLE
connOpts.setKeepAliveInterval(300) cut no ice

### ISSUE THREAD

**Issue by PingWei1314** [eclipse-paho/paho.mqtt.java#611]
I set the heartbeat time to 300s, but it didn't work in practice. I still used the default value.

**Comment by icraggs** [comment]
Which version of the library did you use?  MQTTClient or MQTTAsync?  What symptoms did you see - lack of pings, or inability to detect a closed connection?

**Comment by icraggs** [comment]
No answer, so closing.
