### ISSUE TITLE
Method "ConnectionLost" never firing!

### ISSUE THREAD

**Issue by leon-lourenco** [eclipse-paho/paho.mqtt.java#624]
So, that's my code:

```
 public void connect() throws MqttException {
        MqttConnectOptions options = new MqttConnectOptions();
        options.setUserName("user");
        options.setPassword("pass".toCharArray());
        options.setAutomaticReconnect(true);
        MqttClient client = new MqttClient("tcp://broker:8884", MqttClient.generateClientId(), handlerPahoDirs());
        client.setCallback(callback);
        client.connect(options);
        client.subscribe(this.topic);
    }
```

and connectionLost on MqttCallback:

```
 public void connectionLost(Throwable throwable) {
            try {
                connect();
            } catch (MqttException e) {
                //Logger
            }
        }

```

It turns out that the "connectionLost" method is never called! Sometimes I disconnected the internet and none of this method was called (I was in debug mode). What can it be?

**Comment by icraggs** [comment]
The first observation I'd make is that you have automatic reconnect set to true.  You should either reconnect in the connectionLost callback, or use automatic reconnect.  Automatic reconnect is meant to avoid the application having to issue the reconnect.

The second one is that if you disconnect the internet connection, then it can take some time for that loss to be recognized.  This will happen when a packet is attempted to be sent, for instance a PING.  The keep alive interval connect option controls how frequently a ping is sent.  The default is 60 seconds, which means it could take more than a minute for a broken TCP connection to be observed by the client library.

**Comment by leon-lourenco** [comment]
@icraggs So, I should use AutomaticReconnect OR connectionLost, not both?

**Comment by icraggs** [comment]
Yes.  It looks like connectionLost should still be fired (probably), but you should definitely not use both to reconnect.

**Comment by llakhch** [comment]
> The first observation I'd make is that you have automatic reconnect set to true. You should either reconnect in the connectionLost callback, or use automatic reconnect. Automatic reconnect is meant to avoid the application having to issue the reconnect.
> 
> The second one is that if you disconnect the internet connection, then it can take some time for that loss to be recognized. This will happen when a packet is attempted to be sent, for instance a PING. The keep alive interval connect option controls how frequently a ping is sent. The default is 60 seconds, which means it could take more than a minute for a broken TCP connection to be observed by the client library.

are you saying, if automatic reconnect set to true, in connectionlost, would not have called connect logic? whereas client.reconnect() is ok?

**Comment by icraggs** [comment]
@llakhch yes.   Automatic reconnect did not exist originally, the way to reconnect was to call connect in the connection lost callback.  Automatic reconnect was added to replace that method.  If you activate automatic reconnect and also connect in the connection lost callback, it would at the very least be confusing and unnecessary.
