### ISSUE TITLE
What's the current release version of the Paho MQTT Client?

### ISSUE THREAD

**Issue by veita** [eclipse-paho/paho.mqtt.java#628]
Maven Central has (stable) version 1.2.1.

The latest GitHub release is 1.2.0 (https://github.com/eclipse/paho.mqtt.java/releases). The readme file of the project says `The latest release version is 1.2.0 and the current snapshot version is 1.2.1-SNAPSHOT`

So both sources contradict each other. We don't know if it is safe to include 1.2.1 in our product.

**Comment by icraggs** [comment]
I just released the 1.2.1 version, but haven't tagged the repo yet.  I forgot that the readme explicitly states the current versions - that seems like a mistake to me.

**Comment by icraggs** [comment]
Ok, I've now tagged the repo and updated the readme.  Thanks.
