### ISSUE TITLE
NullPointerException on MqttPersistentData.<init>

### ISSUE THREAD

**Issue by allofmex** [eclipse-paho/paho.mqtt.java#634]
- [x] Bug exists Release Version 1.2.0 ( Master Branch)
- [x] Bug exists in MQTTv3 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)

I experience a NullPointerException here:
https://github.com/eclipse/paho.mqtt.java/blob/f30e10b26320d63649904d163dced2b4f4330c97/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/internal/MqttPersistentData.java#L63

if called from here (argument `payload` is null):
https://github.com/eclipse/paho.mqtt.java/blob/5af7b53499e7dbe45b7227b3d41fc870089c0033/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/persist/MqttDefaultFilePersistence.java#L219

There should be a null check in MqttPersistentData constructor.

StackTrace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object byte[].clone()' on a null object reference
     at org.eclipse.paho.client.mqttv3.internal.MqttPersistentData.<init>(MqttPersistentData.java:63)
     at org.eclipse.paho.client.mqttv3.persist.MqttDefaultFilePersistence.get(MqttDefaultFilePersistence.java:219)
     at org.eclipse.paho.client.mqttv3.internal.ClientState.restoreState(ClientState.java:342)
     at org.eclipse.paho.client.mqttv3.internal.ClientState.<init>(ClientState.java:172)
     at org.eclipse.paho.client.mqttv3.internal.ClientComms.<init>(ClientComms.java:108)
     at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<init>(MqttAsyncClient.java:470)
     at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<init>(MqttAsyncClient.java:320)
     at org.eclipse.paho.android.service.MqttConnection.connect(MqttConnection.java:289)
     at org.eclipse.paho.android.service.MqttService.connect(MqttService.java:329)
     at org.eclipse.paho.android.service.MqttAndroidClient.doConnect(MqttAndroidClient.java:467)
     at org.eclipse.paho.android.service.MqttAndroidClient.access$200(MqttAndroidClient.java:76)
     at org.eclipse.paho.android.service.MqttAndroidClient$MyServiceConnection.onServiceConnected(MqttAndroidClient.java:115)
     at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1223)
     at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1240)
     at android.os.Handler.handleCallback(Handler.java:739)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:148)
```

**Comment by fguiet** [comment]
Hi! 
Just delete your "user.dir" environment variable directory and you will be good to go
Fred

**Comment by goldschmidtcm** [comment]
Hi,

I got the same issue. I would like to use the persistence to bypass offline-times and power downs. The MqttPersistentData constructor is always called with null-payload and throws an exception. So the persisted data can never be recovered?

Regards,
Chris

**Comment by msqr** [comment]
I think commit 635a8c6 introduced this particular NPE, as it [added](https://github.com/eclipse/paho.mqtt.java/commit/635a8c61e0c7f39741a9ba37e6e6dc723d7d8bf6#diff-1c43c493dc2f257c59e741e3a5e97f7f) the `.clone()` calls to MqttPersistentData.java.

**Comment by shoyu666** [comment]
copy MqttDefaultFilePersistence and MqttPersistentData (add payload null check) as your persistence
new MqttAsyncClient(your persistence)

**Comment by cvb941** [comment]
This is an obvious NPE that can be statically detected and easily fixed. There's already a PR for it too.
It's 5 months and still hasn't been fixed (issue is still open).

**Comment by gouldner** [comment]
Still happening in v1.2.2 Unfortunately this issue breaks MqttDefaultFilePersistence making it unusable.

**Comment by flystarts** [comment]
result = new MqttPersistentData(key, data, 0, data.length, data, 0, 0);

**Comment by christianrowlands** [comment]
I am having the same problem.  A fix would be much appreciated!

**Comment by rdasgupt** [comment]
PR is merged and develop branch build passed:
https://travis-ci.org/github/eclipse/paho.mqtt.java/builds/671724738

**Comment by rajeshnailwal** [comment]
@rdasgupt I see that in new build -

result = new MqttPersistentData(key, data, 0, data.length, null, 0, 0); in MqttDefaultFilePersistence.get(String)

and you are checking this.payload = (payload != null ? payload.clone() : null); in the constructor of MqttPersistentData

Just want to understand why would you keep payload null if  there is valid message payload in disk data.

**Comment by rdasgupt** [comment]
The original code (payload.clone) was throwing NPE for null payload.
Fix is to check payload before cloning the payload.

**Comment by rajeshnailwal** [comment]
> The original code (payload.clone) was throwing NPE for null payload.
> Fix is to check payload before cloning the payload.

Yes, that is understood and it solves the NPE but it is still passing null argument in constructor whereas it should have been actual payload. You are going to mis the payload if a message exists and there can be some consequence of this when messages are read.

We resolved our problem by inhereting MqttDefaultFilePersistence class and overriding its get function. This function passes payload instead of null in MqttPersistentData constructor

**Comment by rdasgupt** [comment]
@rajeshnailwal 
I am sorry, I still don't understand your point about this statement:
this.payload = (payload != null ? payload.clone() : null)
It is passing null only if payload is null.

Could you please submit a PR with your solution.

If you are expecting that the issue #759 opened by you will get resolved with this fix, then I don't know because #759 is not investigated yet.

**Comment by rajeshnailwal** [comment]
@rdasgupt no I am not saying #759 will be resolved with this. This is a different issue. I am just trying to understand what is the impact of setting payload value null when a message is found in persistent storage and it has valid content. It is the constructor invocation that is passing null value. Shouldn't it pass a valid value which should be 

`result = new MqttPersistentData(key, data, 0, data.length, data, 0, 0);` in `MqttDefaultFilePersistence.get(String)`

instead of 

`result = new MqttPersistentData(key, data, 0, data.length, null, 0, 0);` in `MqttDefaultFilePersistence.get(String)`

**Comment by pstanton** [comment]
> @rdasgupt no I am not saying #759 will be resolved with this. This is a different issue. I am just trying to understand what is the impact of setting payload value null when a message is found in persistent storage and it has valid content. It is the constructor invocation that is passing null value. Shouldn't it pass a valid value which should be
> 
> `result = new MqttPersistentData(key, data, 0, data.length, data, 0, 0);` in `MqttDefaultFilePersistence.get(String)`
> 
> instead of
> 
> `result = new MqttPersistentData(key, data, 0, data.length, null, 0, 0);` in `MqttDefaultFilePersistence.get(String)`

I must say, this makes perfect sense and the fact that this was missed in the analysis of the original issue is an oversight. pretty bloody obvious!

**Comment by pstanton** [comment]
> 
> 
> @rdasgupt no I am not saying #759 will be resolved with this. This is a different issue. I am just trying to understand what is the impact of setting payload value null when a message is found in persistent storage and it has valid content. It is the constructor invocation that is passing null value. Shouldn't it pass a valid value which should be
> 
> `result = new MqttPersistentData(key, data, 0, data.length, data, 0, 0);` in `MqttDefaultFilePersistence.get(String)`
> 
> instead of
> 
> `result = new MqttPersistentData(key, data, 0, data.length, null, 0, 0);` in `MqttDefaultFilePersistence.get(String)`

Actually, the `null` you are replacing with `data` is the payload, whereas `data` is actually the `header`. you can see it is already used in the 2nd parameter.
