### ISSUE TITLE
no NetworkModule installed for scheme "tcp" of URI "tcp://129.1.99.8:1883"

### ISSUE THREAD

**Issue by i402097836** [eclipse-paho/paho.mqtt.java#672]
Please fill out the form below before submitting, thank you!

- [yes ] Bug exists Release Version 1.2.1 ( Master Branch)

If this is a bug regarding the Android Service, please raise the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new
 

This seems like a bug in a multithreaded environment

**Comment by icraggs** [comment]
Hi.  This is a duplicate of #572 - please follow there.  Thanks.
