### ISSUE TITLE
connectComplete be triggered when connectionLost

### ISSUE THREAD

**Issue by roychen11232357** [eclipse-paho/paho.mqtt.java#680]
When I use connectComplete like below, the callback will be trigger before connectionLost,
```
	@Override
	public void connectComplete(boolean reconnect, String serverURI) {
		System.out.println("connectComplete");
	}
```

But when I changed the coed like this, it works correctly, connectComplete will not be fired when connectionLost 

```
	@Override
	public void connectComplete(boolean reconnect, String serverURI) {
		System.out.println("connectComplete");
		try {
			client.subscribe("#", 1);
		} catch (MqttException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
```

I used org.eclipse.paho.sample.mqttv3app:SampleAsyncCallBack.java to make this case. Is this a bug?

**Comment by xiangwangcheng** [comment]
I encounter this kind of problem too. The connectComplete was invoked whenever connection lost. 
Anyone help to explain this?

**Comment by rdasgupt** [comment]
@roychen11232357 @xiangwangcheng 

I am not sure if we need to merge the PR.  I could not recreate the problem with the latest develop branch. I have the following callbacks in my Async client:

        @Override
        public void connectionLost(Throwable cause) {
                System.out.printf(String.format("Connection to Server is lost: %s.\n", cause.getMessage()));
        }
        @Override
        public void connectComplete(boolean arg0, String arg1) {
            if ( arg0 == true ) {
                System.out.println("Reconnecting to Server: " + arg1);
            } else {
                System.out.println("Connected to Server: " + arg1);
            }
        }

----------------

Test Results

---> Start broker, connect client and subscribe to a topic ---
Connecting AsyncClient to:tcp://xxx.xxx.xxx.xxx:1883 ClientID:IBMIoTClient01 ReconFlag:1
Connected to Server: tcp://xxx.xxx.xxx.xxx:1883
Client is connected.
Subscribing to iot-2/evt/test/fmt/json, with QoS 1
---> Stopped the broker ---
Connection to Server is lost: Connection lost.
---> Restarted the broker after 2 minutes ---
Reconnecting to Server: tcp://xxx.xxx.xxx.xxx:1883

---------

Please try your client using latest 1.2.2 develop stream. If you see the problem again, provide the paho logs with log level set to FINE.

**Comment by xiangwangcheng** [comment]
@rdasgupt  I still have this problem.
![image](https://user-images.githubusercontent.com/8049014/78888890-281e1f80-7a95-11ea-9e2a-9c72460588d9.png)

Sorry, I didn't make it find the location of the log file.

Here is the code:
```
public class TuxedoMqttConsumer {

    private static Logger log = LoggerFactory.getLogger(TuxedoMqttConsumer.class);

    public static void main(String[] args) throws NoSuchAlgorithmException, InvalidKeyException, InterruptedException {
        System.setProperty("java.util.logging.config.file", "/Users/chengxiangwang/Documents/git/miaosha/miaosha1/src/main/resources/jsr47min.properties");
        System.setProperty("user.home", "/Users/chengxiangwang/");
        String broker = "tcp://localhost:1883";
        String clientId = "GID_cxw@@@cxw002";
        MqttConnectOptions mqttConnectOptions = new MqttConnectOptions();
        mqttConnectOptions.setCleanSession(false);
        mqttConnectOptions.setKeepAliveInterval(3000000);
        mqttConnectOptions.setAutomaticReconnect(false);
        mqttConnectOptions.setMqttVersion(MQTT_VERSION_3_1_1);
        mqttConnectOptions.setConnectionTimeout(100);

        MemoryPersistence persistence = new MemoryPersistence();

        try {
            MqttAsyncClient sampleClient = new MqttAsyncClient(broker, clientId, persistence);

            sampleClient.setCallback(new MqttCallbackExtended() {
                @Override
                public void connectComplete(boolean reconnect, String serverURI) {
                    System.out.println("connect success");
                }

                @Override
                public void connectionLost(Throwable throwable) {
                    System.out.println("Connect lost: " + throwable.getMessage());
                }

                @Override
                public void messageArrived(String s, MqttMessage mqttMessage) throws Exception {
                    System.out.println(
                        "receive msg from topic " + s + " , body is " + new String(mqttMessage.getPayload()) + "packetId is " + mqttMessage.getId());
                }

                @Override
                public void deliveryComplete(IMqttDeliveryToken iMqttDeliveryToken) {
                    System.out.println("send msg succeed topic is : " + iMqttDeliveryToken.getTopics()[0]);
                }
            });

            System.out.println("Connecting to broker: " + broker);
            sampleClient.connect(mqttConnectOptions).waitForCompletion();
            Thread.sleep(Integer.MAX_VALUE);
        } catch (MqttException me) {
            System.out.println("reason " + me.getReasonCode());
            System.out.println("msg " + me.getMessage());
            System.out.println("loc " + me.getLocalizedMessage());
            System.out.println("cause " + me.getCause());
            System.out.println("excep " + me);
            me.printStackTrace();
            System.exit(1);
        }
    }
}
```

**Comment by rdasgupt** [comment]
@xiangwangcheng 
Thanks for checking again.
I will check if I can recreate the issue using your sample.

**Comment by rdasgupt** [comment]
PR #703 is merged.
