### ISSUE TITLE
How to know if a publish is success ? 

### ISSUE THREAD

**Issue by ajith-om** [eclipse-paho/paho.mqtt.java#692]
Dear Team,
I'm successfully using mqtt client to publish and subscribe data. I have tried it with java and windows cmd and its properly working fine. When i publish some message from java,I'm successfully able to see that in cmd and subsequently I get a message from the logger I have added in delivery completed method(override from mqttcallback). Now, I need help on implementing on getting response/some message or atleast knowing if it was success or failure when i publish. Kindly help me.
Thanks 
Ajith

**Comment by rdasgupt** [comment]
If I understood your question correctly, you want to know if the message is delivered to the broker. You have added deliveryComplete() callback which is good. The delivery complete callback is invoked based on QoS. 
Refer to deliveryComplete() callback documentation that explains the behavior:
https://www.eclipse.org/paho/files/javadoc/org/eclipse/paho/client/mqttv3/MqttCallback.html#deliveryComplete-org.eclipse.paho.client.mqttv3.IMqttDeliveryToken-

This callback is called when delivery for a message has been completed, and all acknowledgments have been received. For QoS 0 messages it is called once the message has been handed to the network for delivery. For QoS 1 it is called when PUBACK is received and for QoS 2 when PUBCOMP is received. The token will be the same token as that returned when the message was published.

Note that the token is the same token that is used when message was published. So you can compare the token to verify delivery.

**Comment by rdasgupt** [comment]
@ajith-om 
We didn't hear back on the answer provided, from you for almost two months now. I am closing this issue. If you think your question is not answered or need more information, please reopen the issue with your comments.

**Comment by ryanjanborja** [comment]
I'm also looking for this. I want to check if the message was published successfully. If not then I need to retry publishing again
