### ISSUE TITLE
mqttv5 - function subscribe calls itself

### ISSUE THREAD

**Issue by misau** [eclipse-paho/paho.mqtt.java#695]
MqttClient.java:
	public IMqttToken subscribe(String[] topicFilters, int[] qos, IMqttMessageListener[] messageListeners)
			throws MqttException {
		return this.subscribe(topicFilters, qos, messageListeners);
	}

**Comment by icraggs** [comment]
I'm writing a new MQTT V5 client library - it's in the vert.x branch.  I intend that to be the one that's released.
