### ISSUE TITLE
Can this be made to work over WebSockets?

### ISSUE THREAD

**Issue by blalockch** [eclipse-paho/paho.mqtt.java#7]
Hi, I'm currently using this library in an app and thanks for all the hard work.

We were thinking of moving all our backend communication to ports 80/443 (since enterprise environments usually only allow those outgoing ports) but unfortunately this library does not use WebSockets so it doesn't look possible currently.

It would be nice if this client provided MQTT over WebSockets with an option.

**Comment by jpwsutton** [comment]
Hi @blalockch WebSocket functionality was implemented a few months ago, however it is still only in the develop branch. I recommend following the instructions here: https://github.com/eclipse/paho.mqtt.java/blob/develop/README.md to switch to the SNAPSHOT version.

Once you've done that, all you need to do is change your server uri to use the ws prefix like the example here: https://github.com/jpwsutton/EclipsePahoMavenExample/blob/master/src/main/java/org/eclipse/paho/App.java

Hope that helps!
