### ISSUE TITLE
NullPointerException when working with persistence

### ISSUE THREAD

**Issue by iacco** [eclipse-paho/paho.mqtt.java#713]
Please fill out the form below before submitting, thank you!

- [ x] Bug exists Release Version 1.2.2 ( Master Branch)
- [ x] Bug exists in MQTTv3 Client on Snapshot Version 1.2.3-SNAPSHOT (Develop Branch)
- [ x] Bug exists in MQTTv5 Client on Snapshot Version 1.2.3-SNAPSHOT (Develop Branch)

In the MQTTv3 client, in line 219 of MqttDefaultFilePersistence.java a new instance of MqttPersistentData is created passing a null for the payload argument, and in the Constructor in line 63 a clone method is invoked on this null payload object, hence throwing a NullPointerException.

Is this an expected behaviour?

**Comment by RedShift1** [comment]
Duplicate of https://github.com/eclipse/paho.mqtt.java/issues/634

**Comment by ogis-yamazaki** [comment]
Duplicate of  PR #653

**Comment by jensli** [comment]
Ping!

This is a serious problem with a trivial fix. It should be solved as soon as possible.

**Comment by rdasgupt** [comment]
Duplicate of #634 
The fix for 634 is now merged. Closing this issue.
