### ISSUE TITLE
v5 gradle not build

### ISSUE THREAD

**Issue by BrokenWingsIcarus** [eclipse-paho/paho.mqtt.java#723]
C:\Users\Administrator\Desktop\test1>gradle build
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':compileClasspath'.
> Could not resolve org.eclipse.paho:org.eclipse.paho.mqttv5.client:1.2.1-SNAPSHOT.
  Required by:
      project :
   > Could not resolve org.eclipse.paho:org.eclipse.paho.mqttv5.client:1.2.1-SNAPSHOT.
      > Could not parse POM https://repo.eclipse.org/content/repositories/paho-snapshots/org/eclipse/paho/org.eclipse.paho.mqttv5.client/1.2.1-SNAPSHOT/org.eclipse.paho.mqttv5.client-1.2.1-20190221.050721-75.pom
         > Could not find org.eclipse.paho:java-parent:1.2.1-SNAPSHOT.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by BrokenWingsIcarus** [comment]
maven not build. [INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.179 s
[INFO] Finished at: 2019-12-12T16:42:42+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project mqtt5_learn: Could not resolve dependencies for project com.wanke.mqtt.test:mqtt5_learn:jar:1.0-SNAPSHOT: Failed to collect dependencies at org.eclipse.paho:org.eclipse.paho.mqttv5.client:ja
r:1.2.1-SNAPSHOT: Failed to read artifact descriptor for org.eclipse.paho:org.eclipse.paho.mqttv5.client:jar:1.2.1-SNAPSHOT: Failure to find org.eclipse.paho:java-parent:pom:1.2.1-SNAPSHOT in https://repo.eclipse.org/content/reposit
ories/paho-snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of Eclipse paho snapshots has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

D:\个人学习\mqtt5_learn>

**Comment by BrokenWingsIcarus** [comment]
where java parent 1.2.2????

**Comment by huayicheng2015** [comment]
你有手动下载相关的jar包么？如果没有，建议把依赖此库的gradle文件代码贴出来。不过，我还是建议你手动下载，省事儿。

**Comment by BrokenWingsIcarus** [comment]
- - 心塞

**Comment by rdasgupt** [comment]
@huayicheng2015 It will help everyone if you could add your comments in English.

This is what @huayicheng2015 trying to say:
"Do you manually download the relevant jar packages? If not, it is recommended to paste the gradle file code that depends on this library. However, I still recommend that you download it manually to save effort."
