### ISSUE TITLE
ClientComms#shutdownConnection method called twice

### ISSUE THREAD

**Issue by ogis-yamazaki** [eclipse-paho/paho.mqtt.java#726]
Please fill out the form below before submitting, thank you!

- [x] Bug exists Release Version 1.2.2 ( Master Branch)
- [x] Bug exists in MQTTv3 Client on Snapshot Version 1.2.3-SNAPSHOT (Develop Branch)
- [ ] Bug exists in MQTTv5 Client on Snapshot Version 1.2.3-SNAPSHOT (Develop Branch)

ClientComms#shutdownConnection method called twice when proceeding as follows.

1. MqttAsyncClient#disconnect
2. Thread:disconnect call ClientComms#shutdownConnection.
3. Thread:disconnect call receiver.stop()
4. Thread:disconnect call Socket#close()
5. Execute close callback.
6. Catch SocketException in Thread:receiver.
7. Thread:receiver call ClientComms#shutdownConnection.

Therefore, calling reconnect after disconnect may result in an error. 
Throws MqttException(MqttException.REASON_CODE_CLIENT_DISCONNECTING)

## code for reproducing

```java
import java.net.URI;
import org.junit.Test;
import org.junit.Assert;
import org.eclipse.paho.client.mqttv3.IMqttAsyncClient;
import org.eclipse.paho.client.mqttv3.IMqttToken;
import org.eclipse.paho.client.mqttv3.MqttAsyncClient;
import org.eclipse.paho.client.mqttv3.test.properties.TestProperties;

public class ConAndDisconTest {

    @Test
    public void testConAndDiscon() throws Exception {
        int max_loop_count = 1000;
        URI serverURI = TestProperties.getServerURI();
        IMqttAsyncClient mqttClient = new MqttAsyncClient(serverURI.toString(), "someoen", null);
        IMqttToken token = null;
        try {
            for (int i = 0 ; i < max_loop_count; i++ ) {
                token = mqttClient.connect();
                token.waitForCompletion();  
                token = mqttClient.disconnect();
                token.waitForCompletion();
            }
        }
        catch(Exception e) {
            e.printStackTrace();
            Assert.fail();
        }
        finally {
            if (mqttClient.isConnected()) {
                mqttClient.disconnectForcibly();;
            }
            mqttClient.close();
        }  
    
    }
}
```

**Comment by rdasgupt** [comment]
PR #727 is merged.
PR #758 to add test case is merged.
