### ISSUE TITLE
MQTT benchmark

### ISSUE THREAD

**Issue by tanyz91** [eclipse-paho/paho.mqtt.java#728]
Hi all,

I've been testing mqtt(mosquitto broker v1.6.8 with eclipse paho MQTTv3 client 1.2.2-SNAPSHOT)for performance.
All I wanted to do was to get the rate of publish and subscription in terms of msg/s (110-140byte message each).

Server specs:
CPU: Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz
RAM: 8GB

Setup:
Server publishing and subscribing is on 2 different servers.
Server subscribing has got a broker in it.
Broker settings are:
max_queued_messages 1000
max_queued_bytes 536870910
message_size_limit 268435455
max_inflight_messages 0

I've tested on: 
1 client publish and 1 client subscribe, the maximum publish rate acheived is about ~62kmsg/s
2 client publish and 1 client subscribe, the maximum subscribe rate acheived is about ~80kmsg/s 
2 client publish and 2 client shared subscription, the maximum publish rate acheived is about ~100kmsg/s 
3 client publish and 2 client shared subscription, the maximum publish rate acheived is about ~100kmsg/s (Realizing that the rate mosquitto broker can handle is ~100kmsg/s)

I am trying to find out how to improve the broker capability to allow more than 100kmsg/s
Is this the maximum performance? Can I optimize it further?

Also in my test case above, I've tested with both QoS 0 and QoS 1.
I've begin to see some message loss when using shared subscription under both cases QoS 0 & QoS 1(Not suppose to happen in this case) with QoS 1 having a much lower publish rate.
Is this a behavior of shared subscription? If no, is there a bench mark setting for using shared subscription?

**Comment by rdasgupt** [comment]
Since your questions are related to mosquitto, please use the following link to open issue or ask question about eclipse/mosquitto project:
https://github.com/eclipse/mosquitto/issues

You can also ask questions in Eclipse Community Forum:
https://www.eclipse.org/forums/index.php/f/247/
