### ISSUE TITLE
about the topic that I have subscribed ，but I can't receive message。

### ISSUE THREAD

**Issue by ming8916** [eclipse-paho/paho.mqtt.java#733]
- [x] Bug exists Release Version 1.2.0 ( Master Branch)

I subscribe the topic such as ' topic/# '  ，when I send message to the topic  named 'topic' or 'topic/'
,the client can't reveice message . 
but when I change the jar version to 1.2.2.the problem do not appear。
I plan to update the version,but I don't know what different between the version 1.2.0 and 1.2.2.

**Comment by rdasgupt** [comment]
@ming8916 For details on the changes made in releases refer to:
https://github.com/eclipse/paho.mqtt.java/releases

**Comment by rdasgupt** [comment]
@ming8916 
I am closing this issue. If you didn't get the information, you were looking for, please reopen the issue with your comments.
