### ISSUE TITLE
Hi is there anyway that we can delete a message that has been published but not yet subscribed,

### ISSUE THREAD

**Issue by devtar** [eclipse-paho/paho.mqtt.java#737]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.2.2 ( Master Branch)
- [ ] Bug exists in MQTTv3 Client on Snapshot Version 1.2.3-SNAPSHOT (Develop Branch)
- [ ] Bug exists in MQTTv5 Client on Snapshot Version 1.2.3-SNAPSHOT (Develop Branch)

If this is a bug regarding the Android Service, please raise the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

**Comment by devtar** [comment]
Hi is there anyway that we can delete a message that has been published but not yet subscribed, in my case if there is a message which has been published but not subscribed so can we delete that message which is in the mqtt broker

**Comment by rdasgupt** [comment]
Since you have not provided information about clean session flag, retain flag and QoS set in your publisher and subscriber, it is difficult to say if you can delete any published message. 

Here are some information that may help you.

If you are publishing a retained message (i.e. retained flag is True), you can delete the message as long as the message is not yet delivered to a subscriber. You can delete a retained message by publishing a zero-byte payload on the topic. 

If you have configured your clients for persisted session (i.e. clean session flag is False), messages are persisted in the broker and delivered to subscriber based on QoS set on Subscriber and Publisher. Client can not delete persisted message in the broker. The broker can implement delete message feature.

**Comment by devtar** [comment]
hi rdasgupt,

The clean session flag is false, the retain is false, and QOS is 1 . I am talking about Persistent connection. I somehow know its not possible but still am not 100% sure on this.



> Since you have not provided information about clean session flag, retain flag and QoS set in your publisher and subscriber, it is difficult to say if you can delete any published message.
> 
> Here are some information that may help you.
> 
> If you are publishing a retained message (i.e. retained flag is True), you can delete the message as long as the message is not yet delivered to a subscriber. You can delete a retained message by publishing a zero-byte payload on the topic.
> 
> If you have configured your clients for persisted session (i.e. clean session flag is False), messages are persisted in the broker and delivered to subscriber based on QoS set on Subscriber and Publisher. Client can not delete persisted message in the broker. The broker can implement delete message feature.

**Comment by rdasgupt** [comment]
In your use case, you can not delete message from publisher. 

Depending on your use case, you can explore the following options:

1. Leverage option provided by broker, but there could be some issues associated with broker option. Broker will basically delete the subscription. This will also make all persisted messages for the subscription, in the broker to get deleted.
2. You can do the same thing from an administrative application by connected to the broker using clientID of the subscriber and unsubscribe from the topic. This will make the broker to delete all pending messages for the subscriber. There is a drawback with this option. If the subscriber client whose clientID you are using from administrative application, is connected when administrative application is trying to connect and unsubscribe, the broker may disconnect the subscriber (clientID steal case). 

Both, broker option to delete subscription or unsubscribe from the topic from an administrative application will work as long as messages are not delivered to the subscriber and deletion of all pending messages is acceptable.
 
You may get more suggestion, if you post your question in Eclipse Community Forum for Paho:
https://www.eclipse.org/forums/index.php?t=thread&frm_id=247

Please close this issue, if you got your answers.

**Comment by rdasgupt** [comment]
@devtar 
I am closing this issue. If you need more information or clarification, please reopen the issue with your comments.
