### ISSUE TITLE
NullpointerException in org.eclipse.paho.client.mqttv3.CommsCallback#deliverMessage

### ISSUE THREAD

**Issue by babymotte** [eclipse-paho/paho.mqtt.java#740]
- [x] Bug exists Release Version 1.2.2 ( Master Branch)
- [x] Bug exists in MQTTv3 Client on Snapshot Version 1.2.3-SNAPSHOT (Develop Branch)
- [ ] Bug exists in MQTTv5 Client on Snapshot Version 1.2.3-SNAPSHOT (Develop Branch)

In my application I get frequent NullpointerExceptions coming from org.eclipse.paho.client.mqttv3.CommsCallback#deliverMessage. The method iterates over the keys of callbacks and then, without any further synchronization, retrieves a callback using those keys and invokes them without checking if they are even still in the map.

I'm issuing a P&R that should solve the problem.

**Comment by rdasgupt** [comment]
PR #741 is merged.
