### ISSUE TITLE
Logger is not thread friendly

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.java#75]
migrated from Bugzilla [#465985](https://bugs.eclipse.org/bugs/show_bug.cgi?id=465985)
status NEW severity _normal_ in component _MQTT-Java_ for _1.1_
Reported in version _1.1_ on platform _All_
Assigned to: Bin Zhang

On 2015-04-30 16:30:30 -0400, Wes Johnson wrote:

> When instantiating a MqttAsyncClient a Logger is also created and is declared static/final.  Then the instantiated class sets the static loggers resourceName as the clientId.  If multiple clients are instantiated all threads will erroneously report logs are coming from clientId of the last instantiated client.
> 
> This mistake is repeated in other classes such as ClientState and ClientComms as well.
> 
> Thanks,
> Wes

**Comment by icraggs** [comment]
This sounds like the trace problem that was confusing us in the output today.

**Comment by icraggs** [comment]
I think just making the log instantiation non-static should do the trick:

private Logger log = LoggerFactory.getLogger(LoggerFactory.MQTT_CLIENT_MSG_CAT, CLASS_NAME);
