### ISSUE TITLE
Add "connected" support to MqttCallback

### ISSUE THREAD

**Issue by xiemeilong** [eclipse-paho/paho.mqtt.java#751]
- [ ] Bug exists Release Version 1.2.2 ( Master Branch)

If I want to subscribe some topics on connected everytime, then I can't use reconnect feature , because the connected action callback will not be called when reconnected.

**Comment by rdasgupt** [comment]
@xiemeilong 
You can use MqttCallbackExtended()
https://www.eclipse.org/paho/files/javadoc/org/eclipse/paho/client/mqttv3/MqttCallbackExtended.html
This callback is invoked when connection to the server is completed successfully.

void connectComplete(boolean reconnect, java.lang.String serverURI)
reconnect - If true, the connection was the result of automatic reconnect.

This callback will work for both if you are using automatic reconnect, or reconnecting using reconnect() method.
