### ISSUE TITLE
deliverycomplete();  not triggered?

### ISSUE THREAD

**Issue by eliot9876** [eclipse-paho/paho.mqtt.java#755]
I'm using the release 1.2.1,  when I'm implementing th MQTTCallBack methods in my subscriber I'm notcing that only the messagearrived() method is triggered but not the deliverycomplete();
It's worth the mention that on my mosquitto logs  it seems that the server is sending PUBReland PUBCOMP

**Comment by rdasgupt** [comment]
The deliverycomplete() is triggered in a publisher application. This method is not triggered in a subscriber application.

**Comment by eliot9876** [comment]
@rdasgupt  Thanks fro your response!!
I was running some tests and I noticed this,  but how to  check the delivery is complete from the subscriber side. Thanks in advance as I need this information for some measurement

**Comment by eliot9876** [comment]
@rdasgupt the deliverycomplete(); from the publisher side will give information from the publisher until the broker I'm more interested in the  E2E  delivery.

**Comment by rdasgupt** [comment]
I think what you are looking for is like a request-response pattern in MQTT. Publisher publishes a message and publisher wants to make sure that the message is delivered to the subscriber. 

MQTT v3 didn't have any spec for request-response whereas MQTT v5 does support request-response pattern. Refer to the following document (bullet 7) for details:

https://github.com/mqtt/mqtt.github.io/wiki/Differences-between-3.1.1-and-5.0

Paho MQTT java client version 1.2.2 conforms to MQTT v3 specs. In this version you can design your own request-response pattern. Subscriber can publish a message with some unique message ID (set by the publisher of the message) on a topic (say receivedMessage). Publisher can subscribe to the topic and co-relate ID to mark pub-sub complete.

Development and test work for MQTT v5 compliant client is still going on. This will be released soon. You can try development branch "vertx".

**Comment by rdasgupt** [comment]
@eliot9876 
If you have got answer to your question, please close this issue.

**Comment by rdasgupt** [comment]
@eliot9876 
I am closing this issue. If you didn't get your answer or need more information, please reopen the issue with your comments.
