### ISSUE TITLE
how to check E2E  delivery?

### ISSUE THREAD

**Issue by eliot9876** [eclipse-paho/paho.mqtt.java#756]
Deliverycomplete();  callback method return when delivery  is complete from Publisher side. I'm wondering if there is   any callback method to check  the delivery  from Subscriber side.

**Comment by rdasgupt** [comment]
@eliot9876 See my comments in #755 
Since both #755 and #756 is for the same issue, I would suggest you to close this issue.

**Comment by eliot9876** [comment]
see  #755
