### ISSUE TITLE
System.nanoTime() runs slow on Android

### ISSUE THREAD

**Issue by powturns** [eclipse-paho/paho.mqtt.java#774]
Please fill out the form below before submitting, thank you!

- [x] Bug exists Release Version 1.2.4 ( Master Branch)
- [x] Bug exists in MQTTv3 Client on Snapshot Version 1.2.4-SNAPSHOT (Develop Branch)
- [x] Bug exists in MQTTv5 Client on Snapshot Version 1.2.3-SNAPSHOT (Develop Branch)

According to the [SystemClock Documentation](https://developer.android.com/reference/android/os/SystemClock.html) (emphasis mine):
> uptimeMillis() is counted in milliseconds since the system was booted. This **clock stops when the system enters deep sleep** (CPU off, display dark, device waiting for external input)... This is the basis for most interval timing such as... [**System.nanoTime()**]

This bug manifests itself as incorrect ping scheduling on android when the device is in a low-power state (eg: unplugged with the screen off), ultimately culminating in a client disconnect.

The culprit appears to be the change to `System.nanoTime` in `ClientState`.

Relevant logs:
```
D/AlarmPingSender: Checking if ping required at: 1589862395516
D/nt.mqttv3.internal.ClientState: checkForActivity:4a7d686b-5d31-46f8-83c4-a906a11df121: checkForActivity entered
D/nt.mqttv3.internal.ClientState: checkForActivity:4a7d686b-5d31-46f8-83c4-a906a11df121: ping not needed yet. Schedule next ping.
ms:1589862395661 -- time:248146711582786 lastOutboundActivity:248138888845393
elapsedSinceLastActivityMillis:7822
D/nt.mqttv3.internal.ClientState: checkForActivity:4a7d686b-5d31-46f8-83c4-a906a11df121: Schedule next ping at 52,178
D/AlarmPingSender: Schedule next alarm at 1589862448143
D/AlarmPingSender: Alarm schedule using setExactAndAllowWhileIdle, next: 52178
D/AlarmPingSender: No Ping required. Release lock(AlarmPingSender.client.4a7d686b-5d31-46f8-83c4-a906a11df121): 1589862395973
D/.mqttv3.internal.CommsReceiver: run:4a7d686b-5d31-46f8-83c4-a906a11df121: network read message
Socket Read:1589862396058
D/.mqttv3.internal.CommsReceiver: run:4a7d686b-5d31-46f8-83c4-a906a11df121: network read message
Socket Read:1589862409389
D/.mqttv3.internal.CommsReceiver: run:4a7d686b-5d31-46f8-83c4-a906a11df121: network read message
Socket Read:1589862415969
D/.mqttv3.internal.CommsReceiver: run:4a7d686b-5d31-46f8-83c4-a906a11df121: network read message
Socket Read:1589862417227
D/.mqttv3.internal.CommsReceiver: run:4a7d686b-5d31-46f8-83c4-a906a11df121: network read message
Socket Read:1589862434783
D/AlarmPingSender: Checking if ping required at: 1589862448509
D/nt.mqttv3.internal.ClientState: checkForActivity:4a7d686b-5d31-46f8-83c4-a906a11df121: checkForActivity entered
D/nt.mqttv3.internal.ClientState: checkForActivity:4a7d686b-5d31-46f8-83c4-a906a11df121: ping not needed yet. Schedule next ping.
D/.mqttv3.internal.CommsReceiver: run:4a7d686b-5d31-46f8-83c4-a906a11df121: network read message
ms:1589862448679 -- time:248156914385282 lastOutboundActivity:248138888845393
Socket Read:1589862448753
elapsedSinceLastActivityMillis:18025
D/nt.mqttv3.internal.ClientState: checkForActivity:4a7d686b-5d31-46f8-83c4-a906a11df121: Schedule next ping at 41,975
```

Note the following lines (of non-standard logging), placed on `ClientState:710` (`nextPingTime = Math.max(1,  getKeepAlive() - elapsedSinceLastActivityMillis)`)
```
ms:1589862395661 -- time:248146711582786 lastOutboundActivity:248138888845393
ms:1589862448679 -- time:248156914385282 lastOutboundActivity:248138888845393
```
Where:
* ms = Wall clock time (from `System.currentTimeMillis()`)
* time = `time` local variable (from `System.nanoTime()`)
* lastOutboundActivity = `lastOutboundActivity` field on `ClientState`

Notably, just over 50 seconds of wall clock time has elapsed between these two log statements, but only 10 seconds of  `System.nanoTime()` (The device was in a deep sleep, pausing this time source). 

This can be observed in the standard logs as well:
```
D/nt.mqttv3.internal.ClientState: checkForActivity:4a7d686b-5d31-46f8-83c4-a906a11df121: Schedule next ping at 52,178
D/nt.mqttv3.internal.ClientState: checkForActivity:4a7d686b-5d31-46f8-83c4-a906a11df121: Schedule next ping at 41,975
```

Even though the value of `lastOutboundActivity` has not changed, the ping gets scheduled 52 seconds in the future on the first check, followed by 41 seconds on the second pass (corresponding to the 10 seconds of `System.nanoTime()` that has passed)

I think the most elegant solution may be to provide a high-resolution timer interface to `ClientState` that has platform-specific implementations. If this is an agreeable solution I will produce a pull request.

**Comment by rdasgupt** [comment]
@51systems 
Thanks for detailed analysis.

Any PR to resolve the issue is welcome. As long as your proposed solution doesn't make Java Client dependent on Android SDK to make the solution platform-dependent.
