### ISSUE TITLE
When will mqttv5 be released ？

### ISSUE THREAD

**Issue by flowclouds** [eclipse-paho/paho.mqtt.java#790]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.2.3 ( Master Branch)
- [ ] Bug exists in MQTTv3 Client on Snapshot Version 1.2.4-SNAPSHOT (Develop Branch)
- [ ] Bug exists in MQTTv5 Client on Snapshot Version 1.2.3-SNAPSHOT (Develop Branch)

I can't build the MQTTv5 -dev barnch ,also I can use the dependency 。

**Comment by rdasgupt** [comment]
Service Release v1.2.5 includes MQTTv5.
You can use master branch. Jars are also available in Maven.
Develop branch has 1.2.6-SNAPSHOT
