### ISSUE TITLE
Where to download the most current & stable (so NO nightly build / dev / testing version!!) .jar of "paho" ?

### ISSUE THREAD

**Issue by jayjupdhig** [eclipse-paho/paho.mqtt.java#806]
"Replace %REPOURL% with either https://repo.eclipse.org/content/repositories/paho-releases/ for the official releases, or https://repo.eclipse.org/content/repositories/paho-snapshots/ for the nightly snapshots. Replace %VERSION% with the level required. The latest release version is 1.2.0 and the current snapshot version is 1.2.1."

I can only see a 0.4 version here, nothing else:
`https://repo.eclipse.org/content/repositories/paho-releases/org/eclipse/paho/mqtt-client/`

So what's written on `https://www.eclipse.org/paho/clients/java/` seems to be wrong. (?)

So where to download the most current & stable (so NO nightly build / dev / testing version!!) .jar of "paho"...?

Thank you for your feedbacks.

With best regards,
Jan

**Comment by jayjupdhig** [comment]
"Replace %REPOURL% with either https://repo.eclipse.org/content/repositories/paho-releases/ for the official releases ... "

I don't want to use eclipse for that, i just want to download the .jar file directly - that's all!! ;-)


Regards,
Jan

**Comment by jayjupdhig** [comment]
When i look at your GitHub page, i can only download source:
https://github.com/eclipse/paho.mqtt.java/releases/tag/v1.2.5

-> On `https://repo.eclipse.org/content/repositories/paho-releases/org/eclipse/paho/mqtt-client/` i read that version 1.2.0 is the must current stable version, but there is v 1.2.5 on release.

Why? That makes no sense i.m.o...

Thank you for your feedbacks.


Regards,
Jan

**Comment by jayjupdhig** [comment]
Is THAT the correct one??
-> https://repo.eclipse.org/content/repositories/paho-releases/org/eclipse/paho/org.eclipse.paho.mqttv5.client/1.2.5/org.eclipse.paho.mqttv5.client-1.2.5.jar

Thx for feedback,
Jan

**Comment by rdasgupt** [comment]
@martijintro 
Refer to the following page to download the latest version (1.2.5) of Paho MQTT Java client libraries:

https://projects.eclipse.org/projects/iot.paho/downloads

Download links for both MQTTv3 and MQTTv5 are specified in this page.

**Comment by jayjupdhig** [comment]
OK thx

**Comment by jayjupdhig** [comment]
Additional info for other users: Library for MQTT protocol V3.x is here:
https://repo.eclipse.org/content/repositories/paho-releases/org/eclipse/paho/org.eclipse.paho.client.mqttv3/1.2.5/org.eclipse.paho.client.mqttv3-1.2.5.jar
