### ISSUE TITLE
Why directories like `0a6a92ec-1281-4a7c-a890-4214ae2d427a-tcp192168302471883` will be created in the app directory?

### ISSUE THREAD

**Issue by jayjupdhig** [eclipse-paho/paho.mqtt.java#810]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.2.3 ( Master Branch)
- [ ] Bug exists in MQTTv3 Client on Snapshot Version 1.2.4-SNAPSHOT (Develop Branch)
- [ ] Bug exists in MQTTv5 Client on Snapshot Version 1.2.3-SNAPSHOT (Develop Branch)

First: I don't know what you mean with the text above. Current release version seems to be 1.2.5. (???)

Now the question: Why directories like `0a6a92ec-1281-4a7c-a890-4214ae2d427a-tcp192168302471883` will be created in the app directory?

Thanks for feedbacks.

Kind regards from Switzerland,
Jan

**Comment by rdasgupt** [comment]
Could you please provide more details on this. 
May be a sample APP that can reproduce this problem. 
What is  MqttClientPersistence set to?

**Comment by jayjupdhig** [comment]
Now i've set the persistence argument to null with that code, it decides it will be enabled or not with the `caUseMemoryPersistance` boolean argument parameter: 

```
MemoryPersistence lMemoryPersistence = null;

if (caUseMemoryPersistance) {
				lMemoryPersistence = new MemoryPersistence();
			}

			this.mMqttClient = new MqttClient(clMqttUrl, aIdentifier, lMemoryPersistence);
````

Instead of only that:

```
this.mMqttClient = new MqttClient(clMqttUrl, aIdentifier);
```

-> That code with 2 arguments seems to enable the memory persistance by default, right?

Maybe there is a relation between that issue...

https://github.com/eclipse/paho.mqtt.java/issues/794

...and the issue i've descibed here.

Now i use JVM 8 and paho without the memory persistance parameter the the problem seems to be gone.

But you can investigate that issue closer. If you have some questions, so please don't hesitate to ask me for more informations. Thanks.

**Comment by jayjupdhig** [comment]
So closed, but just re-open it if you want.

**Comment by sp193** [comment]
As you have found, not explicitly specifying that you want in-memory persistence, will result in file-based persistence.

From the Javadoc for the 2-argument [MqttClient(String, String)](https://www.eclipse.org/paho/files/javadoc/org/eclipse/paho/client/mqttv3/MqttClient.html#MqttClient-java.lang.String-java.lang.String-) constructor:
``An instance of the default persistence mechanism MqttDefaultFilePersistence is used by the client. To specify a different persistence mechanism or to turn off persistence, use the MqttClient(String, String, MqttClientPersistence) constructor.``
