### ISSUE TITLE
Versions 1.2.3 vs. 1.2.4 vs. 1.2.5

### ISSUE THREAD

**Issue by jayjupdhig** [eclipse-paho/paho.mqtt.java#811]
`Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.2.3 ( Master Branch)
- [ ] Bug exists in MQTTv3 Client on Snapshot Version 1.2.4-SNAPSHOT (Develop Branch)
- [ ] Bug exists in MQTTv5 Client on Snapshot Version 1.2.3-SNAPSHOT (Develop Branch)`

So what is the current release version now? 1.2.3 or 1.2.4 or 1.2.5??

Thx for feedback,
Jan

**Comment by rdasgupt** [comment]
Template file is updated to reflect correct version.
The current released version is 1.2.5.
