### ISSUE TITLE
memory leak on mqttV3 （version 1.0.2）

### ISSUE THREAD

**Issue by zhangjiapu** [eclipse-paho/paho.mqtt.java#814]
Please fill out the form below before submitting, thank you!

- [x] Bug exists Release Version 1.0.2 ( Master Branch)
- [ ] Bug exists in MQTTv3 Client on Snapshot Version 1..0.2-SNAPSHOT (Develop Branch)
- [ ] Bug exists in MQTTv5 Client on Snapshot Version 1.0.2-SNAPSHOT (Develop Branch)

we have a memory leak problem in our projecet and it's really hard to figure out ,if i use client.publish() to send msg , the memorry will leak at rate of 4K/30s unit our project shut down,can anyone can help us ?

**Comment by sp193** [comment]
1.0.2 is very old. Why not upgrade? The bug, if it exists, could have already been fixed.

**Comment by zhangjiapu** [comment]
> 1.0.2 is very old. Why not upgrade? The bug, if it exists, could have already been fixed.

because jdk in some of mechines is not support
