### ISSUE TITLE
MqttCallbackExtended.connectComplete() not called

### ISSUE THREAD

**Issue by lorenx** [eclipse-paho/paho.mqtt.java#831]
I'm using **MQTTv3 v1.2.4** (I tried from version `1.1.1` up to `1.2.4`) and my `connectComplete()` callback doesn't get called on first connection (not sure about the connection lost event).

For project reasons, I have to use Java 7 (so I guess I cannot try version`1.2.5` in case) with an old [**Moquette broker** version](https://github.com/moquette-io/moquette/releases/tag/v0.9), in case this was important to know.

This is my simplified code:

```java
public class ClientWrapper implements MqttCallbackExtended {

    public ClientWrapper() {
        try {
            client = new MqttClient(URI, CLIENT_ID, null);
            client.connect(getConnectOptions());
            client.setCallback(this);
            client.subscribe(SUBSCRIBE_TOPIC, SUBSCRIBE_QOS);
        } catch (MqttException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void connectComplete(boolean b, String s) {
        Utils.debug(TAG, "connectComplete");
    }

    @Override
    public void messageArrived(final String topic, MqttMessage mqttMessage) {
        String payload = new String(mqttMessage.getPayload());
        int qos = mqttMessage.getQos();

        Utils.debug(TAG, String.format("Topic: %s, Message: %s, Qos: %d", topic, payload, qos));
    }
}
```

The client is actually able to subscribe the broker successfully, I can see all `messageArrived()` logs but I don't see any `connectComplete()` output.
What am I missing?

Thank you.

**Comment by lorenx** [comment]
Code refactoring fixed my issue, not sure what happened. Closing, thank you.

**Comment by timbersea** [comment]
you should invoke the setCallback(), before connect()
