### ISSUE TITLE
Can add a reconnect callback method in `MqttCallback `?

### ISSUE THREAD

**Issue by wwhai** [eclipse-paho/paho.mqtt.java#832]
Hello,Can add a reconnect callback on here method(MqttAsyncClient lines 529):
```java
    //…….
    private void startReconnectCycle() {
        String methodName = "startReconnectCycle";
        this.log.fine(CLASS_NAME, methodName, "503", new Object[]{this.clientId, (long)reconnectDelay});
        this.reconnectTimer = new Timer("MQTT Reconnect: " + this.clientId);
        this.reconnectTimer.schedule(new MqttAsyncClient.ReconnectTask((MqttAsyncClient.ReconnectTask)null), (long)reconnectDelay);
    }
    //……..

```
add this callback can output log when try to reconnect,such this:
```java

public interface MqttCallback {
    void connectionLost(Throwable var1);

    void messageArrived(String var1, MqttMessage var2) throws Exception;

    void deliveryComplete(IMqttDeliveryToken var1);
    // reconnect method
    void tryReconnect();
}

```

```java
    private void startReconnectCycle() {
     //…
     //…
        callback.tryReconnect();
    }

**Comment by sp193** [comment]
If you disable automatic reconnection and manually initiate reconnection from [MqttCallbackExtended#connectionLost(java.lang.Throwable cause)](https://www.eclipse.org/paho/files/javadoc/org/eclipse/paho/client/mqttv3/MqttCallback.html#connectionLost-java.lang.Throwable-), will that also do the same thing?

**Comment by wwhai** [comment]
> If you disable automatic reconnection and manually initiate reconnection from [MqttCallbackExtended#connectionLost(java.lang.Throwable cause)](https://www.eclipse.org/paho/files/javadoc/org/eclipse/paho/client/mqttv3/MqttCallback.html#connectionLost-java.lang.Throwable-), will that also do the same thing?

Thanks, I have resolved.
