### ISSUE TITLE
Frequent disconnection with broker!

### ISSUE THREAD

**Issue by iAmSKU** [eclipse-paho/paho.mqtt.java#848]
Please fill out the form below before submitting, thank you!

- [X] Bug exists Release Version 1.2.4 ( Master Branch)
- [ ] Bug exists Release Version 1.2.5 ( Master Branch)
- [ ] Bug exists in MQTTv3 Client on Snapshot Version 1.2.6-SNAPSHOT (Develop Branch)
- [ ] Bug exists in MQTTv5 Client on Snapshot Version 1.2.6-SNAPSHOT (Develop Branch)

While connecting to the broker I have observed 

> FINE	 20-12-02  10:20:32.0101 	nal.CommsTokenStore	 saveToken              	1290	MyClient: key=Con message=CONNECT clientId MyClient keepAliveInterval 60
> FINE	 20-12-02  10:20:32.0101 	nal.CommsTokenStore	 saveToken              	1290	MyClient: key=Con token=org.eclipse.paho.client.mqttv3.MqttToken@6bf52203
> FINE	 20-12-02  10:20:32.0101 	al.TCPNetworkModule	 start                  	1290	MyClient: connect to host ie-databus port 1,883 timeout 5,000
> FINE	 20-12-02  10:20:32.0102 	ernal.CommsReceiver	 start                  	1290	MyClient: starting
> FINE	 20-12-02  10:20:32.0105 	ernal.CommsReceiver	 run                    	1291	MyClient: network read message
> FINE	 20-12-02  10:20:32.0205 	nternal.ClientState	 get                    	1292	MyClient: wait for new work or for space in the inflight window
> FINE	 20-12-02  10:20:32.0306 	ernal.CommsCallback	 run                    	1293	MyClient: wait for workAvailable
> FINE	 20-12-02  10:20:32.0405 	nternal.ClientComms	 internalSend           	1290	MyClient: 200
> FINE	 20-12-02  10:20:32.0405 	nternal.ClientState	 send                   	1290	MyClient: pending send key=0 message CONNECT clientId MyClient keepAliveInterval 60
> FINE	 20-12-02  10:20:32.0405 	nal.CommsTokenStore	 saveToken              	1290	MyClient: key=Con message=CONNECT clientId MyClient keepAliveInterval 60
> FINE	 20-12-02  10:20:32.0405 	nal.CommsTokenStore	 saveToken              	1290	MyClient: key=Con token=org.eclipse.paho.client.mqttv3.MqttToken@6bf52203
> FINE	 20-12-02  10:20:32.0407 	nternal.ClientState	 get                    	1292	MyClient: new work or ping arrived 
> FINE	 20-12-02  10:20:32.0407 	nternal.CommsSender	 run                    	1292	MyClient: network send key=Con msg=CONNECT clientId MyClient keepAliveInterval 60
> FINE	 20-12-02  10:20:32.0407 	nternal.ClientState	 notifySentBytes        	1292	MyClient: sent bytes count=14
> FINE	 20-12-02  10:20:32.0407 	nternal.ClientState	 notifySentBytes        	1292	MyClient: sent bytes count=28
> FINE	 20-12-02  10:20:32.0407 	re.MqttOutputStream	 write                  	1292	null: Sent CONNECT clientId MyClient keepAliveInterval 60
> FINE	 20-12-02  10:20:32.0408 	nternal.ClientState	 notifySent             	1292	MyClient: key=Con
> FINE	 20-12-02  10:20:32.0408 	ttv3.internal.Token	 notifySent             	1292	MyClient: > key=Con
> FINE	 20-12-02  10:20:32.0408 	nternal.ClientState	 get                    	1292	MyClient: wait for new work or for space in the inflight window
> FINE	 20-12-02  10:20:33.0112 	ernal.CommsReceiver	 run                    	1291	MyClient: Stopping due to IOException
> FINE	 20-12-02  10:20:33.0112 	nternal.ClientComms	 shutdownConnection     	1291	MyClient: state=DISCONNECTING

Not sure is it a BUG or Broker is misbehaving but I have observed in same time other MQTT client are working good and able to connect with the broker.

If this is a bug regarding the Android Service, please raise the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

**Comment by iAmSKU** [comment]
After further looking on this, following is the packet analysis:
- MQTT client has send request to broker.
- Broker has send "Connect Ack" with code  "Return Code: Connection Accepted (0)".
- Immediately after MQTT client has send "TCP Reset"

![image](https://user-images.githubusercontent.com/39804807/101042101-cde14a00-35a2-11eb-9e60-96990ab30003.png)

**Comment by iAmSKU** [comment]
After upgrade issue is fixed.

**Comment by zhubinsheng** [comment]
> 升级后问题解决。
你好 怎么升级的 用的哪个版本
