### ISSUE TITLE
MQTTClient.publish() hangs after MessageSight server stopped

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.java#86]
migrated from Bugzilla [#453948](https://bugs.eclipse.org/bugs/show_bug.cgi?id=453948)
status RESOLVED severity _critical_ in component _MQTT-Java_ for _1.1_
Reported in version _unspecified_ on platform _Other_
Assigned to: Bin Zhang

Original attachment names and IDs:
- _[javacore.20141125.171331.24298.0001.txt](https://bugs.eclipse.org/bugs//attachment.cgi?id=249115)_ (ID 249115)

On 2014-12-02 17:33:59 -0500, Cong Li wrote:

> Created attachment 249115
> javacore taken after issue happens
> 
> We see very often the MqttClient.publish() method hangs when messageSight server stops.
> 
> We have reproduced this issue with following steps
> 1. Start our program.
> 2. Force MessageSight to stop.
> 3. Wait for a short time, then bring up MessageSight server again.
> 4. Half of the time, our program hangs, it happens when the publish() method is in process while MessageSight server stops.
> 
> In this test case, following MqttClient configuration is used
> 
> conOpt = new MqttConnectOptions();
> conOpt.setCleanSession(true);
> conOpt.setKeepAliveInterval(0);
> 
> MqttMessage message = new MqttMessage(payload);
> message.setQos(0);
> 
> Thanks,
> 
> Cong Li

On 2014-12-02 17:35:18 -0500, Cong Li wrote:

> Forgot to mention we are using org.eclipse.paho.client.mqttv3-1.0.1-SNAPSHOT.jar

On 2015-01-14 02:43:16 -0500, Bin Zhang wrote:

> Cannot reproduce this issue with the source on develop branch with the following steps:
> 1. connect to mqtt broker (mosquitto) with CleanSession=true, KeepAliveInterval=0
>    and reconnect on connectionLost with the same connectOptions
> 2. publish qos 0 message with mqttClient.publish(String topic, MqttMessage message)
> 3. stop mqtt broker
> 4. start mqtt broker
> 5. the publish continues to work.
> 
> setKeepAliveInterval is set to 0 (disabled), which means no ping will be sent by client, so client and server cannot detect connection lost because of ping timeout.
> 
> You used sync publish and waitForCompletion without a timeout, it means the publish will just wait until completed or client shutdown, and no clue of connection broken from the dump.
> 
> I don't think we can do anything in this case.
> I would suggest to set KeepAliveInterval and publish with a timeout.

On 2015-01-27 10:29:24 -0500, Ian Craggs wrote:

> Changing state to resolved to reflect Bin's comments

**Comment by k-nar** [comment]
"I would suggest to set KeepAliveInterval and publish with a timeout."
Hello how to publish with a timeout ? I use the MqttAsyncClient  
should I use the synchronous version in a thread and wait/notify mechanism ? or is there an options like  socketTimeout (I only see connectionTimeout)

**Comment by jpwsutton** [comment]
@k-nar this issue has been closed, could you open a new one in the future please? This is also so it's easier for other users to find it if they have the same question as you :-)

So if you use the MqttAsyncClient, when you publish you recieve an IMqttDeliveryToken: http://www.eclipse.org/paho/files/javadoc/org/eclipse/paho/client/mqttv3/MqttAsyncClient.html

With the IMqttDeliveryToken, you can use waitForCompletion with your elected timeout : http://www.eclipse.org/paho/files/javadoc/org/eclipse/paho/client/mqttv3/IMqttToken.html#waitForCompletion()

If the timeout is reached before the message has been delivered, then it will throw an MqttException that you can then catch and deal with appropriately.
