### ISSUE TITLE
StackOverflow in MQTTv5 when subscribing with a topicfilter, qos and a IMqttMessageListener

### ISSUE THREAD

**Issue by Questlog** [eclipse-paho/paho.mqtt.java#863]
- [x] Bug exists Release Version 1.2.5 ( Master Branch)
- [ ] Bug exists in MQTTv3 Client on Snapshot Version 1.2.6-SNAPSHOT (Develop Branch)
- [x] Bug exists in MQTTv5 Client on Snapshot Version 1.2.6-SNAPSHOT (Develop Branch)

https://github.com/eclipse/paho.mqtt.java/blob/develop/org.eclipse.paho.mqttv5.client/src/main/java/org/eclipse/paho/mqttv5/client/MqttClient.java#L523-L525

The subscribe method is calling itself.

```java
public IMqttToken subscribe(String[] topicFilters, int[] qos, IMqttMessageListener[] messageListeners)
			throws MqttException {
	return this.subscribe(topicFilters, qos, messageListeners);
}
```

**Comment by fengyuanhui** [comment]
When will it be fixed? Please repair it ASAP !

**Comment by a983132370** [comment]
It works .....

[https://github.com/eclipse/paho.mqtt.java/blob/240f82f8c99d4b2301cf44c4d3b57f234be5d409/org.eclipse.paho.mqttv5.client/src/main/java/org/eclipse/paho/mqttv5/client/MqttClient.java#L528](https://github.com/eclipse/paho.mqtt.java/blob/240f82f8c99d4b2301cf44c4d3b57f234be5d409/org.eclipse.paho.mqttv5.client/src/main/java/org/eclipse/paho/mqttv5/client/MqttClient.java#L528)

**Comment by Questlog** [comment]
> It works .....
> 
> https://github.com/eclipse/paho.mqtt.java/blob/240f82f8c99d4b2301cf44c4d3b57f234be5d409/org.eclipse.paho.mqttv5.client/src/main/java/org/eclipse/paho/mqttv5/client/MqttClient.java#L528

Yeah, use that one. 
The other two subscribe methods would be more convenient though.
