### ISSUE TITLE
Exception in thread "MQTT Rec: "  java.lang.IllegalArgumentException: Invalid UTF-8 char: [14]

### ISSUE THREAD

**Issue by Unic0rnLien** [eclipse-paho/paho.mqtt.java#905]
I need to subscribe to a large number of device messages from the mqtt server, so I use wildcard subscriptions. However, one of the device topics has illegal characters, so it is difficult for me to shield it alone.

In the validateUtf8String method of MqttWireMessage class, an illegal character is detected and an exception is thrown directly, resulting in the disconnection of mqtt connection and repeated attempts to reconnect.

hope to fix this problem and clear the illegal characters in the topic instead of disconnecting directly.

`
2021/11/27 下午10:39:52Exception in thread "MQTT Rec: a03d2c55-f62d-4dd6-9c36-9e07e5837738" java.lang.IllegalArgumentException: Invalid UTF-8 char: [14]
2021/11/27 下午10:39:52	at org.eclipse.paho.client.mqttv3.internal.wire.MqttWireMessage.validateUTF8String(MqttWireMessage.java:407)
2021/11/27 下午10:39:52	at org.eclipse.paho.client.mqttv3.internal.wire.MqttWireMessage.decodeUTF8(MqttWireMessage.java:365)
2021/11/27 下午10:39:52	at org.eclipse.paho.client.mqttv3.internal.wire.MqttPublish.<init>(MqttPublish.java:64)
2021/11/27 下午10:39:52	at org.eclipse.paho.client.mqttv3.internal.wire.MqttWireMessage.createWireMessage(MqttWireMessage.java:207)
2021/11/27 下午10:39:52	at org.eclipse.paho.client.mqttv3.internal.wire.MqttWireMessage.createWireMessage(MqttWireMessage.java:182)
2021/11/27 下午10:39:52	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:119)
2021/11/27 下午10:39:52	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:136)
2021/11/27 下午10:39:52	at java.lang.Thread.run(Thread.java:748)
`

**Comment by Vi-Nk** [comment]
MQTT Protocol specification states : 

> The character data in a UTF-8 encoded string MUST be well-formed UTF-8 as defined by the Unicode specification [Unicode] and restated in RFC 3629 [RFC3629]. In particular this data MUST NOT include encodings of code points between U+D800 and U+DFFF. If a Server or Client receives a Control Packet containing ill-formed UTF-8 it MUST close the Network Connection [MQTT-1.5.3-1].

So, if there is a need of creating custom pre-processing of the topic (in your case , the removal of illegal character and placing the request ) , forking the repo and creating proper pre-processing on your own is the best way to go IMO.
