### ISSUE TITLE
Connection Lost at 03:22 everyday

### ISSUE THREAD

**Issue by hutumolu** [eclipse-paho/paho.mqtt.java#910]
In the same server machine, my java MQTT client connects to local mosquitto to subscript some topics. Every night at 03:22, the connection was lost, and reconnect function didn't work. Does anybody know what happened?

Connection lost (32109) - java.io.EOFException

another time throw MqttException

**Comment by ghost** [comment]
did you remember the solution plz ?

**Comment by jsljzn** [comment]
这个问题关闭了，怎么解决的
